// AUTO-GENERATED by scripts/gen-react-types.mjs — do not edit by hand.
// Opt-in React JSX typings for @toolcase/web-components custom elements.
//
// Import via the package's ./react entry point (src/react.ts), which also
// exports the useTc / useTcEvents runtime hooks.
//
// Regenerate after adding/removing a component or attribute:
//     npm -w @toolcase/web-components run gen:react-types

import type * as React from 'react'

/**
 * Props for a toolcase custom element: standard HTML attributes (className,
 * style, ref, event handlers, …) plus the element's own kebab-case attributes
 * in `T` for autocomplete. Typos in attribute names are now a TypeScript error.
 * Use useTc() to wire the on* event handler props at runtime.
 */
export type TcProps<T = {}> = React.DetailedHTMLProps<
    React.HTMLAttributes<HTMLElement> & T,
    HTMLElement
>

export interface ToolcaseIntrinsicElements {
    'tc-ability-card': TcProps<{ 'ability-name'?: string | number; 'cooldown'?: string | number; 'cost'?: string | number; 'description'?: string | number; 'icon'?: string | number; 'keybind'?: string | number; 'range'?: string | number; 'rarity'?: string | number }>
    'tc-accordion': TcProps<{ 'always-open'?: boolean; 'flush'?: boolean }>
    'tc-accordion-item': TcProps<{ 'header'?: string | number; 'open'?: boolean; onTcHidden?: (e: CustomEvent) => void; onTcHide?: (e: CustomEvent) => void; onTcShow?: (e: CustomEvent) => void; onTcShown?: (e: CustomEvent) => void }>
    'tc-action-header': TcProps<{ 'disabled'?: boolean; onTcExec?: (e: CustomEvent) => void }>
    'tc-action-items': TcProps<{ 'label'?: string | number; onTcActionClick?: (e: CustomEvent) => void }>
    'tc-action-row-list': TcProps<{ 'outline'?: boolean; 'trailing-icon'?: string | number; onTcActionClick?: (e: CustomEvent) => void }>
    'tc-activity-card': TcProps<{ 'loading'?: boolean; 'loading-count'?: string | number; 'title'?: string | number }>
    'tc-advanced-table': TcProps<{ 'limit'?: string | number; 'loading'?: boolean; 'offset'?: string | number; 'sticky-first-column'?: boolean; 'sticky-last-column'?: boolean; 'total'?: string | number; onTcFilterChange?: (e: CustomEvent) => void; onTcPageChange?: (e: CustomEvent) => void; onTcSortChange?: (e: CustomEvent) => void }>
    'tc-alert': TcProps<{ 'dismissible'?: boolean; 'variant'?: string | number; onTcClosed?: (e: CustomEvent) => void }>
    'tc-ammo-counter': TcProps<{ 'mag'?: string | number; 'mag-max'?: string | number; 'reloading'?: boolean; 'reserve'?: string | number; 'weapon-name'?: string | number }>
    'tc-anchor': TcProps<{ 'inset'?: string | number; 'position'?: string | number }>
    'tc-announcement-bar': TcProps<{ 'cta-href'?: string | number; 'cta-label'?: string | number; 'dismissible'?: boolean; 'icon'?: string | number; 'icon-name'?: string | number; 'persist-dismiss-key'?: string | number; 'storage-key'?: string | number; 'variant'?: string | number; onTcDismiss?: (e: CustomEvent) => void }>
    'tc-api-reference-table': TcProps<{ 'title'?: string | number }>
    'tc-area-chart': TcProps<{ 'height'?: string | number; 'loading'?: boolean; 'show-grid'?: string | number; 'show-legend'?: string | number; 'stacked'?: boolean; 'subtitle'?: string | number; 'title'?: string | number; onTcPointHover?: (e: CustomEvent) => void }>
    'tc-artboard-backdrop': TcProps<{ 'kind'?: string | number; 'padding'?: string | number }>
    'tc-aspect-ratio-box': TcProps<{ 'ratio'?: string | number }>
    'tc-asset-bundle': TcProps<{ 'build-tag'?: string | number; 'category'?: string | number; 'default-build-tag'?: string | number; 'latest-build-ref'?: string | number; 'loading'?: boolean; 'name'?: string | number; 'target'?: string | number; 'target-icon'?: string | number; onTcAdvancedToggle?: (e: CustomEvent) => void; onTcBuildTagChange?: (e: CustomEvent) => void; onTcMenuClick?: (e: CustomEvent) => void }>
    'tc-asset-row': TcProps<{ 'icon'?: string | number; 'name'?: string | number; 'size'?: string | number }>
    'tc-asset-row-list': TcProps
    'tc-audio-mixer': TcProps<{ 'current-ms'?: string | number; 'disabled'?: boolean; 'loading'?: boolean }>
    'tc-avatar': TcProps<{ 'alt'?: string | number; 'name'?: string | number; 'size'?: string | number; 'src'?: string | number; 'status'?: string | number; 'variant'?: string | number }>
    'tc-badge': TcProps<{ 'pill'?: boolean; 'text'?: string | number; 'variant'?: string | number }>
    'tc-badge-row': TcProps<{ 'size'?: string | number }>
    'tc-banner': TcProps<{ 'cta-href'?: string | number; 'cta-label'?: string | number; 'dismissible'?: boolean; 'icon'?: string | number; 'icon-name'?: string | number; 'persist-dismiss-key'?: string | number; 'storage-key'?: string | number; 'variant'?: string | number; onTcDismiss?: (e: CustomEvent) => void }>
    'tc-bar-chart': TcProps<{ 'height'?: string | number; 'loading'?: boolean; 'orientation'?: string | number; 'show-values'?: boolean; 'subtitle'?: string | number; 'title'?: string | number; onTcBarClick?: (e: CustomEvent) => void }>
    'tc-basic-card': TcProps<{ 'color'?: string | number; 'icon'?: string | number; 'loading'?: boolean; 'text'?: string | number; 'text-a'?: string | number; 'text-b'?: string | number; 'value'?: string | number }>
    'tc-basic-layout': TcProps<{ 'brand'?: string | number }>
    'tc-battle-pass': TcProps<{ 'current-level'?: string | number; 'current-xp'?: string | number; 'has-premium'?: boolean; 'season-end'?: string | number; 'season-name'?: string | number; onTcClaim?: (e: CustomEvent) => void }>
    'tc-benchmark-chart': TcProps<{ 'interactive'?: boolean; 'lower-is-better'?: boolean; 'scale'?: string | number; 'title'?: string | number; onTcBarClick?: (e: CustomEvent) => void }>
    'tc-bitmap-font-generator': TcProps<{ 'auto-generate'?: boolean; 'background'?: string | number; 'border-align'?: string | number; 'border-color'?: string | number; 'border-thickness'?: string | number; 'borders'?: string | number; 'disabled'?: boolean; 'export-format'?: string | number; 'fill-color'?: string | number; 'fill-type'?: string | number; 'font-family'?: string | number; 'font-size'?: string | number; 'glow-color'?: string | number; 'glow-size'?: string | number; 'glyphs'?: string | number; 'glyphs-per-row'?: string | number; 'gradient-angle'?: string | number; 'gradient-colors'?: string | number; 'gradient-type'?: string | number; 'letter-spacing'?: string | number; 'line-height'?: string | number; 'padding'?: string | number; 'power-of-two'?: boolean; 'preview-align'?: string | number; 'preview-background'?: string | number; 'preview-line-gap'?: string | number; 'preview-padding'?: string | number; 'preview-scale'?: string | number; 'scale'?: string | number; 'shadow-blur'?: string | number; 'shadow-color'?: string | number; 'shadow-offset-x'?: string | number; 'shadow-offset-y'?: string | number; 'shadow-size'?: string | number; 'text'?: string | number }>
    'tc-blur-overlay': TcProps<{ 'background'?: string | number; 'blur-amount'?: string | number }>
    'tc-boss-bar': TcProps<{ 'epithet'?: string | number; 'hp'?: string | number; 'hp-max'?: string | number; 'name'?: string | number; 'phase'?: string | number }>
    'tc-brand': TcProps<{ 'color'?: string | number; 'label'?: string | number; 'primary-text'?: string | number; 'secondary-text'?: string | number; 'xlarge'?: boolean }>
    'tc-breadcrumb': TcProps<{ 'divider'?: string | number }>
    'tc-breadcrumb-item': TcProps<{ 'active'?: boolean; 'href'?: string | number }>
    'tc-brief-card': TcProps<{ 'body'?: string | number; 'brief-id'?: string | number; 'clickable'?: boolean; 'difficulty'?: string | number; 'icon'?: string | number; 'meta-left'?: string | number; 'meta-right'?: string | number; 'title'?: string | number; onTcClick?: (e: CustomEvent) => void }>
    'tc-brightness-calibration': TcProps<{ 'value'?: string | number; onTcChange?: (e: CustomEvent) => void }>
    'tc-buff-bar': TcProps<{ 'gap'?: string | number; 'icon-size'?: string | number }>
    'tc-buff-icon': TcProps<{ 'color'?: string | number; 'glyph'?: string | number; 'kind'?: string | number; 'size'?: string | number; 'time'?: string | number }>
    'tc-build': TcProps<{ 'badge'?: string | number; 'badge-variant'?: string | number; 'date'?: string | number; 'duration'?: string | number; 'loading'?: boolean; 'name'?: string | number; 'size'?: string | number; 'status'?: string | number; onTcClick?: (e: CustomEvent) => void; onTcMenuSelect?: (e: CustomEvent) => void }>
    'tc-bundle-bar': TcProps<{ 'filled-segments'?: string | number; 'meta'?: string | number; 'name'?: string | number; 'segments'?: string | number }>
    'tc-button': TcProps<{ 'disabled'?: boolean; 'error'?: string | number; 'field'?: boolean; 'help'?: string | number; 'href'?: string | number; 'loading'?: boolean; 'outline'?: boolean; 'size'?: string | number; 'skin'?: string | number; 'state'?: string | number; 'type'?: string | number; 'variant'?: string | number }>
    'tc-button-group': TcProps<{ 'aria-label'?: string | number; 'size'?: string | number; 'vertical'?: boolean }>
    'tc-callout-quote': TcProps<{ 'attribution'?: string | number; 'quote'?: boolean; 'source'?: string | number; 'source-href'?: string | number }>
    'tc-car-listing-card': TcProps<{ 'category'?: string | number; 'href'?: string | number; 'image-alt'?: string | number; 'image-src'?: string | number; 'layout'?: string | number; 'price-old-text'?: string | number; 'price-text'?: string | number; 'rating'?: string | number; 'rating-count-text'?: string | number; 'seller-avatar-src'?: string | number; 'seller-name'?: string | number; 'title-text'?: string | number; 'wishlisted'?: boolean; onTcWishlistToggle?: (e: CustomEvent) => void }>
    'tc-card': TcProps<{ 'img'?: string | number; 'img-position'?: string | number; 'subtitle'?: string | number; 'title'?: string | number; 'variant'?: string | number }>
    'tc-card-options': TcProps<{ 'columns'?: string | number; 'value'?: string | number; onTcChange?: (e: CustomEvent) => void }>
    'tc-carousel': TcProps<{ 'controls'?: boolean; 'fade'?: boolean; 'indicators'?: boolean; 'interval'?: string | number; 'pause'?: string | number; 'ride'?: string | number; onTcSlid?: (e: CustomEvent) => void; onTcSlide?: (e: CustomEvent) => void }>
    'tc-cdn-map': TcProps<{ 'height'?: string | number }>
    'tc-changelog': TcProps<{ 'loading'?: boolean; 'max-visible'?: string | number; 'read-more-href'?: string | number; 'read-more-label'?: string | number }>
    'tc-character-create': TcProps<{ 'confirm-label'?: string | number; 'heading'?: string | number; 'name'?: string | number; 'name-placeholder'?: string | number; onTcChange?: (e: CustomEvent) => void; onTcConfirm?: (e: CustomEvent) => void; onTcName?: (e: CustomEvent) => void }>
    'tc-character-select': TcProps<{ 'selected-id'?: string | number; onTcConfirm?: (e: CustomEvent) => void; onTcSelect?: (e: CustomEvent) => void }>
    'tc-chart-container': TcProps<{ 'empty'?: boolean; 'loading'?: boolean; 'subtitle'?: string | number; 'title'?: string | number }>
    'tc-chat-window': TcProps<{ 'active-channel'?: string | number; 'height'?: string | number; 'placeholder'?: string | number; 'width'?: string | number; onTcChannelChange?: (e: CustomEvent) => void; onTcSend?: (e: CustomEvent) => void }>
    'tc-check': TcProps<{ 'checked'?: boolean; 'disabled'?: boolean; 'error'?: string | number; 'help'?: string | number; 'indeterminate'?: boolean; 'inline'?: boolean; 'label'?: string | number; 'name'?: string | number; 'required'?: boolean; 'reverse'?: boolean; 'state'?: string | number; 'value'?: string | number; onTcChange?: (e: CustomEvent) => void }>
    'tc-checkbox-group': TcProps<{ 'disabled'?: boolean; 'error'?: string | number; 'help'?: string | number; 'inline'?: boolean; 'label'?: string | number; 'name'?: string | number; 'required'?: boolean; 'state'?: string | number; onTcChange?: (e: CustomEvent) => void }>
    'tc-chip': TcProps<{ 'count'?: string | number; 'disabled'?: boolean; 'icon'?: string | number; 'removable'?: boolean; 'selected'?: boolean; 'static'?: boolean; 'variant'?: string | number; onTcClick?: (e: CustomEvent) => void; onTcRemove?: (e: CustomEvent) => void }>
    'tc-chip-group': TcProps<{ 'border'?: boolean; 'subtitle'?: string | number; 'title'?: string | number; onTcToggle?: (e: CustomEvent) => void }>
    'tc-circular-progress': TcProps<{ 'background'?: string | number; 'color'?: string | number; 'max'?: string | number; 'reverse'?: boolean; 'show-text'?: boolean; 'size'?: string | number; 'thickness'?: string | number; 'value'?: string | number }>
    'tc-close-button': TcProps<{ 'aria-label'?: string | number; 'disabled'?: boolean }>
    'tc-code-label-cell': TcProps<{ 'code'?: string | number; 'name'?: string | number }>
    'tc-code-snippet': TcProps<{ 'code'?: string | number; 'language'?: string | number; 'loading'?: boolean; 'show-copy-button'?: string | number; 'title'?: string | number; onTcCopy?: (e: CustomEvent) => void }>
    'tc-code-with-output': TcProps<{ 'code'?: string | number; 'language'?: string | number; 'layout'?: string | number; 'title'?: string | number }>
    'tc-codex': TcProps<{ 'selected-id'?: string | number; onTcSelect?: (e: CustomEvent) => void }>
    'tc-col': TcProps<{ 'lg'?: string | number; 'md'?: string | number; 'order'?: string | number; 'sm'?: string | number; 'span'?: string | number; 'xl'?: string | number; 'xxl'?: string | number }>
    'tc-collapse': TcProps<{ 'horizontal'?: boolean; 'open'?: boolean; onTcHidden?: (e: CustomEvent) => void; onTcHide?: (e: CustomEvent) => void; onTcShow?: (e: CustomEvent) => void; onTcShown?: (e: CustomEvent) => void }>
    'tc-color-picker': TcProps<{ 'columns'?: string | number; 'disabled'?: boolean; 'error'?: string | number; 'help'?: string | number; 'label'?: string | number; 'loading'?: boolean; 'name'?: string | number; 'required'?: boolean; 'state'?: string | number; 'value'?: string | number; onTcChange?: (e: CustomEvent) => void }>
    'tc-colored-card': TcProps<{ 'color'?: string | number; 'icon'?: string | number; 'loading'?: boolean; 'text'?: string | number; 'text-a'?: string | number; 'text-b'?: string | number; 'value'?: string | number }>
    'tc-combo-box': TcProps<{ 'disabled'?: boolean; 'error'?: string | number; 'help'?: string | number; 'label'?: string | number; 'max-height'?: string | number; 'name'?: string | number; 'placeholder'?: string | number; 'required'?: boolean; 'state'?: string | number; 'value'?: string | number; onTcChange?: (e: CustomEvent) => void }>
    'tc-combo-counter': TcProps<{ 'combo'?: string | number; 'font-size'?: string | number; 'label'?: string | number; 'timer'?: string | number }>
    'tc-command-palette': TcProps<{ 'loading'?: boolean; 'open'?: boolean; 'placeholder'?: string | number; onTcClose?: (e: CustomEvent) => void; onTcSelect?: (e: CustomEvent) => void }>
    'tc-command-reference': TcProps<{ 'search-placeholder'?: string | number; 'searchable'?: string | number; 'title'?: string | number; onTcSearch?: (e: CustomEvent) => void }>
    'tc-community-links': TcProps<{ 'title'?: boolean }>
    'tc-comparator': TcProps<{ 'description'?: string | number; 'loading'?: boolean; 'loading-count'?: string | number; 'show-summary'?: string | number; 'title'?: string | number }>
    'tc-compass-bar': TcProps<{ 'fov'?: string | number; 'heading'?: string | number; 'height'?: string | number; 'show-cardinals'?: boolean; 'width'?: string | number }>
    'tc-compass-rose': TcProps<{ 'heading'?: string | number; 'size'?: string | number }>
    'tc-compatibility-matrix': TcProps<{ 'title'?: string | number }>
    'tc-config-preview': TcProps<{ 'live-label'?: string | number }>
    'tc-confirm-dialog': TcProps<{ 'cancel-label'?: string | number; 'confirm-label'?: string | number; 'danger'?: boolean; 'dialog-title'?: string | number; 'eyebrow'?: string | number; 'message'?: string | number; 'open'?: boolean; onTcCancel?: (e: CustomEvent) => void; onTcConfirm?: (e: CustomEvent) => void }>
    'tc-container': TcProps<{ 'breakpoint'?: string | number; 'fluid'?: boolean }>
    'tc-context-menu': TcProps<{ onTcSelect?: (e: CustomEvent) => void }>
    'tc-contributor-wall': TcProps<{ 'max-visible'?: string | number; 'title'?: string | number }>
    'tc-controller-layout-preview': TcProps<{ 'layout'?: string | number }>
    'tc-controls-rebind-list': TcProps<{ onTcRebind?: (e: CustomEvent) => void }>
    'tc-cookbook-grid': TcProps<{ 'columns'?: string | number; 'title'?: string | number }>
    'tc-cool-button': TcProps<{ 'addon'?: string | number; 'addon-position'?: string | number; 'disabled'?: boolean; 'label'?: string | number; 'loading'?: boolean; 'outline'?: boolean; 'size'?: string | number; 'variant'?: string | number; onTcClick?: (e: CustomEvent) => void }>
    'tc-cool-nav': TcProps<{ 'brand'?: string | number; 'expand-breakpoint'?: string | number; 'login-href'?: string | number; 'login-label'?: string | number; 'login-variant'?: string | number; 'scroll-offset'?: string | number; 'sticky'?: boolean; 'theme'?: string | number; onTcLogin?: (e: CustomEvent) => void; onTcNavToggle?: (e: CustomEvent) => void }>
    'tc-cooldown-badge': TcProps<{ 'label'?: string | number; 'max'?: string | number; 'show-label'?: boolean; 'size'?: string | number; 'value'?: string | number }>
    'tc-countdown-timer': TcProps<{ 'compact'?: boolean; 'label'?: string | number; 'sub-label'?: string | number; 'target'?: string | number; 'units'?: string | number; onTcExpire?: (e: CustomEvent) => void }>
    'tc-crafting-panel': TcProps<{ 'crafting'?: boolean; 'selected-id'?: string | number; onTcCraft?: (e: CustomEvent) => void; onTcSelect?: (e: CustomEvent) => void }>
    'tc-credits-scroll': TcProps<{ 'scroll-title'?: string | number; 'speed'?: string | number; onTcComplete?: (e: CustomEvent) => void }>
    'tc-crosshair': TcProps<{ 'color'?: string | number; 'gap'?: string | number; 'size'?: string | number; 'spread'?: string | number; 'thickness'?: string | number; 'variant'?: string | number }>
    'tc-currency-chip': TcProps<{ 'amount'?: string | number; 'color'?: string | number; 'glyph'?: string | number }>
    'tc-currency-display': TcProps<{ 'amount'?: string | number; 'color'?: string | number; 'currency-icon'?: string | number; 'font-size'?: string | number; 'label'?: string | number }>
    'tc-cycle-wheel': TcProps<{ 'center-label'?: string | number; 'center-pill'?: string | number; 'center-sub'?: string | number; 'center-value'?: string | number; 'current-index'?: string | number; 'paused'?: boolean; 'spin-seconds'?: string | number }>
    'tc-damage-number': TcProps<{ 'crit'?: boolean; 'duration'?: string | number; 'heal'?: boolean; 'miss'?: boolean; 'value'?: string | number; onTcDone?: (e: CustomEvent) => void }>
    'tc-danger-zone-actions': TcProps<{ 'class-name'?: string | number; onTcActionClick?: (e: CustomEvent) => void }>
    'tc-dashboard-content': TcProps
    'tc-dashboard-layout': TcProps<{ 'sidebar-open'?: boolean; onTcToggleSidebar?: (e: CustomEvent) => void }>
    'tc-dashboard-sidebar': TcProps
    'tc-data-list': TcProps<{ 'empty-text'?: string | number; 'list-title'?: string | number; 'selectable'?: boolean; 'selected-id'?: string | number; onTcAction?: (e: CustomEvent) => void; onTcSelect?: (e: CustomEvent) => void }>
    'tc-date-picker': TcProps<{ 'disabled'?: boolean; 'error'?: string | number; 'help'?: string | number; 'label'?: string | number; 'max'?: string | number; 'min'?: string | number; 'name'?: string | number; 'required'?: boolean; 'state'?: string | number; 'value'?: string | number; onTcChange?: (e: CustomEvent) => void }>
    'tc-deadzone-slider': TcProps<{ 'disabled'?: boolean; 'format'?: string | number; 'max'?: string | number; 'min'?: string | number; 'muted'?: boolean; 'step'?: string | number; 'unit'?: string | number; 'value'?: string | number; 'with-mute'?: boolean; onTcChange?: (e: CustomEvent) => void; onTcToggleMute?: (e: CustomEvent) => void }>
    'tc-debug-overlay': TcProps<{ 'draw-calls'?: string | number; 'fps'?: string | number; 'mem-mb'?: string | number; 'triangles'?: string | number }>
    'tc-dialogue-box': TcProps<{ 'speaker'?: string | number; 'text'?: string | number; 'typing-speed'?: string | number }>
    'tc-diff-viewer': TcProps<{ 'after'?: string | number; 'before'?: string | number; 'filename'?: string | number; 'language'?: string | number; 'mode'?: string | number; onTcRender?: (e: CustomEvent) => void }>
    'tc-difference-card': TcProps<{ 'loading'?: boolean; 'period'?: string | number; 'previous-value'?: string | number; 'title'?: string | number; 'value'?: string | number }>
    'tc-divider': TcProps<{ 'label'?: string | number; 'vertical'?: boolean }>
    'tc-download-stats': TcProps<{ 'monthly'?: string | number; 'package-name'?: string | number; 'registry'?: string | number; 'total'?: string | number; 'weekly'?: string | number }>
    'tc-drawer': TcProps<{ 'open'?: boolean; 'pinned'?: boolean; 'side'?: string | number; 'size'?: string | number; 'title'?: string | number; onTcClose?: (e: CustomEvent) => void }>
    'tc-dropdown': TcProps<{ 'auto-close'?: string | number; 'direction'?: string | number; 'label'?: string | number; 'split'?: boolean; 'variant'?: string | number; onTcHidden?: (e: CustomEvent) => void; onTcHide?: (e: CustomEvent) => void; onTcShow?: (e: CustomEvent) => void; onTcShown?: (e: CustomEvent) => void }>
    'tc-dropdown-item': TcProps<{ 'active'?: boolean; 'disabled'?: boolean; 'divider'?: boolean; 'href'?: string | number }>
    'tc-early-signup-form': TcProps<{ 'cta-label'?: string | number; 'eyebrow'?: string | number; 'field-label'?: string | number; 'helper-text'?: string | number; 'loading'?: boolean; 'placeholder'?: string | number; 'stat'?: string | number; 'subtitle'?: string | number; 'success-message'?: string | number; 'success-title'?: string | number; 'title'?: string | number; 'variant'?: string | number; onTcSubmit?: (e: CustomEvent) => void }>
    'tc-ecosystem-map': TcProps<{ 'size'?: string | number; 'title'?: string | number; onTcSelect?: (e: CustomEvent) => void }>
    'tc-editable-text': TcProps<{ 'aria-label'?: string | number; 'default-value'?: string | number; 'disabled'?: boolean; 'placeholder'?: string | number; onTcChange?: (e: CustomEvent) => void }>
    'tc-emission-badge': TcProps<{ 'co2-text'?: string | number; 'label'?: string | number; 'standard'?: string | number; 'tier'?: string | number }>
    'tc-empty-state': TcProps<{ 'description'?: string | number; 'heading'?: string | number; 'icon'?: string | number }>
    'tc-engine-spec': TcProps<{ 'code'?: string | number; 'compact'?: boolean; 'cylinders'?: string | number; 'displacement-cc'?: string | number; 'emission-control'?: string | number; 'fuel-injection'?: string | number; 'layout'?: string | number; 'manufacturer'?: string | number; 'position'?: string | number; 'power-at-rpm'?: string | number; 'supercharger'?: string | number; 'torque-at-rpm'?: string | number; 'torque-nm'?: string | number; 'valves'?: string | number }>
    'tc-entity-cell': TcProps<{ 'clickable'?: boolean; 'color'?: string | number; 'initial'?: string | number; 'name'?: string | number; 'size'?: string | number; 'sub-label'?: string | number; onTcClick?: (e: CustomEvent) => void }>
    'tc-entity-profile-card': TcProps<{ 'loading'?: boolean; 'title'?: string | number }>
    'tc-equipment-doll': TcProps<{ 'height'?: string | number; 'selected-id'?: string | number; 'silhouette'?: string | number; 'slot-size'?: string | number; 'width'?: string | number; onTcSelect?: (e: CustomEvent) => void }>
    'tc-equipment-matrix': TcProps<{ 'collapsible'?: boolean; 'columns'?: string | number }>
    'tc-equipment-tag': TcProps<{ 'flag'?: string | number; 'icon'?: string | number; 'label'?: string | number }>
    'tc-extended-select': TcProps<{ 'disabled'?: boolean; 'error'?: string | number; 'help'?: string | number; 'label'?: string | number; 'loading'?: boolean; 'max-height'?: string | number; 'multiple'?: boolean; 'name'?: string | number; 'no-results-text'?: string | number; 'placeholder'?: string | number; 'required'?: boolean; 'search-placeholder'?: string | number; 'state'?: string | number; 'value'?: string | number; onTcChange?: (e: CustomEvent) => void }>
    'tc-eyebrow': TcProps
    'tc-faq-list': TcProps<{ 'schema'?: boolean; 'title'?: string | number; onTcToggle?: (e: CustomEvent) => void }>
    'tc-feature-card': TcProps<{ 'description'?: string | number; 'eyebrow'?: string | number; 'icon'?: string | number; 'inline'?: boolean; 'size'?: string | number; 'title'?: string | number }>
    'tc-feature-matrix': TcProps<{ 'title'?: string | number }>
    'tc-file': TcProps<{ 'action-icon'?: string | number; 'action-label'?: string | number; 'category'?: string | number; 'category-placeholder'?: string | number; 'editable-tags'?: boolean; 'extension'?: string | number; 'format'?: string | number; 'icon'?: string | number; 'items'?: string | number; 'loading'?: boolean; 'name'?: string | number; 'readonly'?: boolean; 'size'?: string | number; onTcAction?: (e: CustomEvent) => void; onTcCategoryChange?: (e: CustomEvent) => void; onTcItemsClick?: (e: CustomEvent) => void; onTcMenuItemClick?: (e: CustomEvent) => void; onTcNameChange?: (e: CustomEvent) => void; onTcTagsChange?: (e: CustomEvent) => void }>
    'tc-file-dropzone': TcProps<{ onTcFiles?: (e: CustomEvent) => void }>
    'tc-file-tags': TcProps<{ 'readonly'?: boolean; onTcChange?: (e: CustomEvent) => void }>
    'tc-floating-label': TcProps<{ 'for'?: string | number; 'label'?: string | number }>
    'tc-form': TcProps<{ 'novalidate'?: boolean; 'validated'?: boolean }>
    'tc-form-input': TcProps<{ 'disabled'?: boolean; 'error'?: string | number; 'help'?: string | number; 'helper'?: string | number; 'id'?: string | number; 'label'?: string | number; 'loading'?: boolean; 'max'?: string | number; 'min'?: string | number; 'name'?: string | number; 'placeholder'?: string | number; 'required'?: boolean; 'required-message'?: string | number; 'rows'?: string | number; 'step'?: string | number; 'type'?: string | number; 'validate-on'?: string | number; onTcChange?: (e: CustomEvent) => void }>
    'tc-form-wizard': TcProps<{ 'complete-icon'?: string | number; 'complete-label'?: string | number; 'loading'?: boolean; onTcComplete?: (e: CustomEvent) => void; onTcStepChange?: (e: CustomEvent) => void }>
    'tc-fov-slider': TcProps<{ 'disabled'?: boolean; 'format'?: string | number; 'max'?: string | number; 'min'?: string | number; 'muted'?: boolean; 'step'?: string | number; 'unit'?: string | number; 'value'?: string | number; 'with-mute'?: boolean; onTcChange?: (e: CustomEvent) => void; onTcToggleMute?: (e: CustomEvent) => void }>
    'tc-fps-cap-select': TcProps<{ 'disabled'?: boolean; 'value'?: string | number; onTcChange?: (e: CustomEvent) => void }>
    'tc-fullscreen-toggle': TcProps<{ 'checked'?: boolean; 'disabled'?: boolean; onTcChange?: (e: CustomEvent) => void }>
    'tc-funnel-chart': TcProps<{ 'height'?: string | number; 'loading'?: boolean; 'show-labels'?: string | number; 'subtitle'?: string | number; 'title'?: string | number; onTcSelect?: (e: CustomEvent) => void }>
    'tc-game-over-screen': TcProps<{ 'eyebrow'?: string | number; 'subtitle'?: string | number; 'title-color'?: string | number; 'title-text'?: string | number; 'variant'?: string | number; onTcAction?: (e: CustomEvent) => void }>
    'tc-game-showcase-card': TcProps<{ 'pitch'?: string | number; 'title'?: string | number; onTcClick?: (e: CustomEvent) => void }>
    'tc-gamepad-button-prompt': TcProps<{ 'glyph'?: string | number; 'label'?: string | number; 'size'?: string | number }>
    'tc-gantt-chart': TcProps<{ 'end-date'?: string | number; 'loading'?: boolean; 'start-date'?: string | number; 'subtitle'?: string | number; 'title'?: string | number; onTcTaskClick?: (e: CustomEvent) => void }>
    'tc-gilded-frame': TcProps<{ 'padding'?: string | number; 'tone'?: string | number }>
    'tc-github-stars-card': TcProps<{ 'cta-label'?: string | number; 'fetch-live'?: boolean; 'owner'?: string | number; 'repo'?: string | number; onTcCtaClick?: (e: CustomEvent) => void; onTcStats?: (e: CustomEvent) => void }>
    'tc-good-first-issues': TcProps<{ 'title'?: string | number; onTcIssueClick?: (e: CustomEvent) => void }>
    'tc-graphics-preset-picker': TcProps<{ 'disabled'?: boolean; 'value'?: string | number; onTcChange?: (e: CustomEvent) => void }>
    'tc-grid': TcProps<{ 'cell-size'?: string | number; 'cell-size-lg'?: string | number; 'cell-size-md'?: string | number; 'cell-size-sm'?: string | number; 'cell-size-xl'?: string | number; 'cell-size-xxl'?: string | number; 'columns'?: string | number; 'columns-lg'?: string | number; 'columns-md'?: string | number; 'columns-sm'?: string | number; 'columns-xl'?: string | number; 'columns-xxl'?: string | number; 'gap'?: string | number; 'gap-lg'?: string | number; 'gap-md'?: string | number; 'gap-sm'?: string | number; 'gap-xl'?: string | number; 'gap-xxl'?: string | number; 'rows'?: string | number; 'rows-lg'?: string | number; 'rows-md'?: string | number; 'rows-sm'?: string | number; 'rows-xl'?: string | number; 'rows-xxl'?: string | number }>
    'tc-group': TcProps<{ 'action-icon'?: string | number; 'action-label'?: string | number; 'badge'?: string | number; 'default-collapsed'?: boolean; 'label'?: string | number; onTcActionClick?: (e: CustomEvent) => void; onTcToggle?: (e: CustomEvent) => void }>
    'tc-guild-panel': TcProps<{ 'guild-name'?: string | number; 'level'?: string | number; 'member-cap'?: string | number; 'motto'?: string | number; 'tag'?: string | number }>
    'tc-heading': TcProps<{ 'as'?: string | number; 'gradient'?: boolean }>
    'tc-health-bar': TcProps<{ 'ghost'?: string | number; 'label'?: string | number; 'max'?: string | number; 'segments'?: string | number; 'show-text'?: boolean; 'value'?: string | number; 'variant'?: string | number }>
    'tc-heatmap': TcProps<{ 'cell-size'?: string | number; 'loading'?: boolean; 'subtitle'?: string | number; 'title'?: string | number; onTcCellHover?: (e: CustomEvent) => void }>
    'tc-helper-text': TcProps<{ 'class-name'?: string | number; 'icon'?: string | number; 'id'?: string | number; 'text'?: string | number; 'variant'?: string | number }>
    'tc-hero': TcProps<{ 'backdrop'?: string | number; 'background-pattern-src'?: string | number; 'description'?: string | number; 'eyebrow'?: string | number; 'media-alt'?: string | number; 'media-caption'?: string | number; 'media-label'?: string | number; 'media-src'?: string | number; 'note'?: string | number; 'preview'?: boolean; 'title'?: string | number; 'title-as'?: string | number; onTcAction?: (e: CustomEvent) => void }>
    'tc-hero-stats-bar': TcProps<{ 'class-name'?: string | number }>
    'tc-hit-marker': TcProps<{ 'crit'?: boolean; 'duration'?: string | number; 'kill'?: boolean; 'show'?: boolean; 'size'?: string | number; onTcDone?: (e: CustomEvent) => void }>
    'tc-hotbar': TcProps<{ 'selected-id'?: string | number; 'slot-size'?: string | number; onTcSelect?: (e: CustomEvent) => void }>
    'tc-icon': TcProps<{ 'as'?: string | number; 'color'?: string | number; 'decorative'?: boolean; 'label'?: string | number; 'name'?: string | number; 'set'?: string | number; 'size'?: string | number }>
    'tc-icon-badge': TcProps<{ 'bg'?: string | number; 'color'?: string | number; 'glyph'?: string | number; 'size'?: string | number }>
    'tc-icon-button': TcProps<{ 'disabled'?: boolean; 'icon'?: string | number; 'label'?: string | number; 'outline'?: boolean; 'show-label'?: string | number; 'size'?: string | number; 'variant'?: string | number; onTcClick?: (e: CustomEvent) => void }>
    'tc-icon-picker': TcProps<{ 'columns'?: string | number; 'disabled'?: boolean; 'error'?: string | number; 'help'?: string | number; 'label'?: string | number; 'loading'?: boolean; 'max-height'?: string | number; 'name'?: string | number; 'required'?: boolean; 'state'?: string | number; 'value'?: string | number; onTcChange?: (e: CustomEvent) => void }>
    'tc-image': TcProps<{ 'alt'?: string | number; 'aspect-ratio'?: string | number; 'object-fit'?: string | number; 'src'?: string | number; onTcError?: (e: CustomEvent) => void; onTcLoad?: (e: CustomEvent) => void }>
    'tc-image-crop': TcProps<{ 'aspect-ratio'?: string | number; 'circular'?: boolean; 'src'?: string | number; onTcCrop?: (e: CustomEvent) => void; onTcError?: (e: CustomEvent) => void }>
    'tc-infinite-scroll': TcProps<{ 'has-more'?: boolean; 'loading'?: boolean; 'root-margin'?: string | number; 'threshold'?: string | number; onTcLoadMore?: (e: CustomEvent) => void }>
    'tc-input': TcProps<{ 'autocomplete'?: string | number; 'disabled'?: boolean; 'error'?: string | number; 'help'?: string | number; 'inputmode'?: string | number; 'label'?: string | number; 'max'?: string | number; 'maxlength'?: string | number; 'min'?: string | number; 'minlength'?: string | number; 'name'?: string | number; 'pattern'?: string | number; 'placeholder'?: string | number; 'readonly'?: boolean; 'required'?: boolean; 'size'?: string | number; 'state'?: string | number; 'step'?: string | number; 'type'?: string | number; 'value'?: string | number }>
    'tc-input-group': TcProps<{ 'size'?: string | number }>
    'tc-input-group-text': TcProps
    'tc-install-tabs': TcProps<{ 'default-manager'?: string | number; 'dev'?: boolean; 'global'?: boolean; 'package'?: string | number; onTcChange?: (e: CustomEvent) => void; onTcCopy?: (e: CustomEvent) => void }>
    'tc-interact-prompt': TcProps<{ 'hold-progress'?: string | number; 'key-label'?: string | number; 'show'?: boolean; 'text'?: string | number }>
    'tc-inventory-grid': TcProps<{ 'columns'?: string | number; 'selected-id'?: string | number; 'slot-size'?: string | number; onTcSelect?: (e: CustomEvent) => void }>
    'tc-invite-toast': TcProps<{ 'body'?: string | number; 'inviter'?: string | number; 'open'?: boolean; 'timeout-seconds'?: string | number; onTcAccept?: (e: CustomEvent) => void; onTcDecline?: (e: CustomEvent) => void }>
    'tc-item-compare': TcProps
    'tc-item-slot': TcProps<{ 'hotkey'?: string | number; 'selected'?: boolean; 'size'?: string | number; onTcClick?: (e: CustomEvent) => void }>
    'tc-item-tooltip': TcProps
    'tc-journal': TcProps<{ 'selected-id'?: string | number; onTcSelect?: (e: CustomEvent) => void }>
    'tc-json-editor': TcProps<{ 'disabled'?: boolean; 'loading'?: boolean; 'schema'?: string | number; onTcChange?: (e: CustomEvent) => void }>
    'tc-json-schema-def': TcProps<{ 'default-value'?: string | number; 'disabled'?: boolean; 'label'?: string | number; 'loading'?: boolean; 'value'?: string | number; onTcChange?: (e: CustomEvent) => void; onTcLabelChange?: (e: CustomEvent) => void }>
    'tc-kbd': TcProps<{ 'class-name'?: string | number; 'separator'?: string | number }>
    'tc-key': TcProps<{ 'size'?: string | number; 'variant'?: string | number }>
    'tc-key-binder': TcProps<{ 'disabled'?: boolean; 'placeholder'?: string | number; 'value'?: string | number; onTcCancel?: (e: CustomEvent) => void; onTcChange?: (e: CustomEvent) => void }>
    'tc-kill-feed': TcProps<{ 'max-visible'?: string | number }>
    'tc-label': TcProps<{ 'required'?: boolean; 'size'?: string | number; 'tooltip'?: string | number }>
    'tc-leaderboard': TcProps<{ onTcSelect?: (e: CustomEvent) => void }>
    'tc-leaderboard-trend': TcProps<{ 'direction'?: string | number; 'size'?: string | number; 'value'?: string | number }>
    'tc-legal-screen': TcProps<{ 'initial-section'?: string | number; 'screen-title'?: string | number; 'show-accept'?: boolean; onTcAccept?: (e: CustomEvent) => void; onTcClose?: (e: CustomEvent) => void }>
    'tc-letterbox-bars': TcProps<{ 'bar-color'?: string | number; 'bar-height'?: string | number; 'duration'?: string | number; 'show'?: boolean }>
    'tc-level-header': TcProps<{ 'level'?: string | number; 'next-label'?: string | number; 'title'?: string | number; 'xp'?: string | number; 'xp-max'?: string | number }>
    'tc-level-select': TcProps<{ 'height'?: string | number; 'selected-id'?: string | number; 'width'?: string | number; onTcConfirm?: (e: CustomEvent) => void; onTcSelect?: (e: CustomEvent) => void }>
    'tc-lightbox': TcProps<{ 'initial-index'?: string | number; 'open'?: boolean; onTcChange?: (e: CustomEvent) => void; onTcClose?: (e: CustomEvent) => void }>
    'tc-line-chart': TcProps<{ 'height'?: string | number; 'loading'?: boolean; 'show-grid'?: string | number; 'show-legend'?: string | number; 'subtitle'?: string | number; 'title'?: string | number; onTcPointHover?: (e: CustomEvent) => void }>
    'tc-link': TcProps<{ 'external'?: boolean; 'href'?: string | number; 'underline'?: string | number; 'variant'?: string | number }>
    'tc-linked-providers-card': TcProps<{ 'empty-label'?: string | number; 'title'?: string | number; onTcToggle?: (e: CustomEvent) => void }>
    'tc-list': TcProps<{ 'selected-id'?: string | number; onTcSelect?: (e: CustomEvent) => void }>
    'tc-list-card': TcProps<{ 'loading'?: boolean; 'loading-count'?: string | number; 'ordered'?: boolean; 'title'?: string | number }>
    'tc-list-group': TcProps<{ 'flush'?: boolean; 'horizontal'?: string | number; 'numbered'?: boolean }>
    'tc-list-group-item': TcProps<{ 'action'?: boolean; 'active'?: boolean; 'disabled'?: boolean; 'href'?: string | number; 'variant'?: string | number }>
    'tc-list-row': TcProps<{ 'accent'?: string | number; 'disabled'?: boolean; 'selected'?: boolean; onTcSelect?: (e: CustomEvent) => void }>
    'tc-live-feed': TcProps<{ 'auto-scroll'?: boolean; 'header'?: string | number; 'max-rows'?: string | number; 'recording'?: boolean; onTcRowClick?: (e: CustomEvent) => void }>
    'tc-loading-overlay': TcProps<{ 'label'?: string | number; 'open'?: boolean; 'progress'?: string | number; 'tip'?: string | number }>
    'tc-loading-screen': TcProps<{ 'eyebrow'?: string | number; 'label'?: string | number; 'progress'?: string | number; 'tip-interval'?: string | number; 'tip-title'?: string | number; 'title-text'?: string | number }>
    'tc-lobby': TcProps<{ 'can-start'?: boolean; 'capacity'?: string | number; 'is-ready'?: boolean; 'lobby-mode'?: string | number; 'map-name'?: string | number }>
    'tc-login': TcProps<{ 'background-pattern-src'?: string | number; 'description'?: string | number; 'loading'?: boolean; 'title'?: string | number; onTcConnect?: (e: CustomEvent) => void }>
    'tc-logo-cloud': TcProps<{ 'columns'?: string | number; 'grayscale'?: boolean; 'title'?: string | number }>
    'tc-loot-list': TcProps<{ 'list-title'?: string | number; onTcTake?: (e: CustomEvent) => void; onTcTakeAll?: (e: CustomEvent) => void }>
    'tc-loot-popup': TcProps<{ 'auto-fade-ms'?: string | number; 'discard-label'?: string | number; 'eyebrow'?: string | number; 'open'?: boolean; 'popup-title'?: string | number; onTcClose?: (e: CustomEvent) => void; onTcDiscard?: (e: CustomEvent) => void; onTcTake?: (e: CustomEvent) => void; onTcTakeAll?: (e: CustomEvent) => void }>
    'tc-lore-text': TcProps
    'tc-main-menu': TcProps<{ 'menu-title'?: string | number; 'selected-id'?: string | number; 'subtitle'?: string | number; onTcSelect?: (e: CustomEvent) => void }>
    'tc-maintainer-card': TcProps<{ 'avatar-url'?: string | number; 'bio'?: string | number; 'location'?: string | number; 'name'?: string | number; 'role'?: string | number; 'sponsor-href'?: string | number; 'sponsor-label'?: string | number }>
    'tc-mana-bar': TcProps<{ 'ghost'?: string | number; 'label'?: string | number; 'max'?: string | number; 'segments'?: string | number; 'show-text'?: boolean; 'value'?: string | number; 'variant'?: string | number }>
    'tc-manufacturer-tile': TcProps<{ 'active'?: boolean; 'count-text'?: string | number; 'eyebrow'?: string | number; 'href'?: string | number; 'logo-src'?: string | number; 'name'?: string | number }>
    'tc-markdown-editor': TcProps<{ 'disabled'?: boolean; 'height'?: string | number; 'label'?: string | number; 'placeholder'?: string | number; 'toolbar'?: string | number; 'value'?: string | number; onTcChange?: (e: CustomEvent) => void }>
    'tc-marquee': TcProps<{ 'direction'?: string | number; 'pause-on-hover'?: boolean; 'separator'?: string | number; 'speed'?: string | number }>
    'tc-matchmaking-screen': TcProps<{ 'elapsed'?: string | number; 'estimated'?: string | number; 'found-label'?: string | number; 'mode'?: string | number; 'region'?: string | number; 'state'?: string | number }>
    'tc-menu-item': TcProps<{ 'disabled'?: boolean; 'hotkey'?: string | number; 'icon'?: string | number; 'label'?: string | number; 'selected'?: boolean; onTcSelect?: (e: CustomEvent) => void }>
    'tc-metal-button': TcProps<{ 'disabled'?: boolean; 'error'?: string | number; 'field'?: boolean; 'help'?: string | number; 'href'?: string | number; 'loading'?: boolean; 'outline'?: boolean; 'size'?: string | number; 'skin'?: string | number; 'state'?: string | number; 'type'?: string | number; 'variant'?: string | number }>
    'tc-metric-card': TcProps<{ 'icon'?: string | number; 'loading'?: boolean; 'subtitle'?: string | number; 'title'?: string | number; 'trend-color'?: string | number; 'value'?: string | number }>
    'tc-metric-grid': TcProps<{ 'columns'?: string | number }>
    'tc-metric-tile': TcProps<{ 'hint'?: string | number; 'icon'?: string | number; 'label'?: string | number; 'unit'?: string | number; 'value'?: string | number }>
    'tc-migration-guide': TcProps<{ 'from'?: string | number; 'title'?: string | number; 'to'?: string | number }>
    'tc-minimap': TcProps<{ 'background-image'?: string | number; 'rotation'?: string | number; 'size'?: string | number; 'world-height'?: string | number; 'world-width'?: string | number; 'world-x'?: string | number; 'world-y'?: string | number }>
    'tc-modal': TcProps<{ 'centered'?: boolean; 'fullscreen'?: string | number; 'lazy'?: boolean; 'open'?: boolean; 'scrollable'?: boolean; 'size'?: string | number; 'static-backdrop'?: boolean; 'title'?: string | number; onTcHidden?: (e: CustomEvent) => void; onTcHide?: (e: CustomEvent) => void; onTcShow?: (e: CustomEvent) => void; onTcShown?: (e: CustomEvent) => void }>
    'tc-model-family-card': TcProps<{ 'body-type'?: string | number; 'generation'?: string | number; 'href'?: string | number; 'image-alt'?: string | number; 'image-src'?: string | number; 'manufacturer'?: string | number; 'range'?: string | number; 'series'?: string | number; 'variant-count-text'?: string | number; 'years-text'?: string | number }>
    'tc-module-access': TcProps<{ 'owner-role-id'?: string | number; onTcChange?: (e: CustomEvent) => void }>
    'tc-mouse-sensitivity': TcProps<{ 'ads'?: string | number; 'disabled'?: boolean; 'value'?: string | number; onTcChange?: (e: CustomEvent) => void }>
    'tc-multi-card-select': TcProps<{ 'columns'?: string | number; 'loading'?: boolean; 'loading-count'?: string | number; 'name'?: string | number; onTcChange?: (e: CustomEvent) => void }>
    'tc-nav': TcProps<{ 'fill'?: boolean; 'justified'?: boolean; 'variant'?: string | number; 'vertical'?: boolean }>
    'tc-nav-button': TcProps<{ 'disabled'?: boolean; 'kind'?: string | number; 'label'?: string | number; 'size'?: string | number }>
    'tc-nav-item': TcProps<{ 'active'?: boolean; 'disabled'?: boolean; 'href'?: string | number; 'target'?: string | number; onTcShow?: (e: CustomEvent) => void; onTcShown?: (e: CustomEvent) => void }>
    'tc-navbar': TcProps<{ 'bg'?: string | number; 'brand'?: string | number; 'expand'?: string | number; 'fixed'?: string | number; 'sticky'?: string | number; 'variant'?: string | number }>
    'tc-network-status-icon': TcProps<{ 'connected'?: boolean; 'loss'?: string | number; 'ping'?: string | number; 'show-label'?: boolean; 'size'?: string | number }>
    'tc-newsletter-signup': TcProps<{ 'cta-label'?: string | number; 'description'?: string | number; 'placeholder'?: string | number; 'privacy-href'?: string | number; 'success-message'?: string | number; 'title'?: string | number; onTcSubmit?: (e: CustomEvent) => void }>
    'tc-node-editor': TcProps<{ 'disabled'?: boolean; 'selected-id'?: string | number; onTcConnect?: (e: CustomEvent) => void; onTcMoveNode?: (e: CustomEvent) => void; onTcSelect?: (e: CustomEvent) => void }>
    'tc-normal-map-generator': TcProps<{ 'ambient'?: string | number; 'bevel-width'?: string | number; 'blur-radius'?: string | number; 'brush-falloff'?: string | number; 'brush-size'?: string | number; 'brush-strength'?: string | number; 'disabled'?: boolean; 'editable'?: boolean; 'emboss-height'?: string | number; 'invert-x'?: boolean; 'invert-y'?: boolean; 'light-tracking'?: string | number; 'light-x'?: string | number; 'light-y'?: string | number; 'light-z'?: string | number; 'mask-color'?: string | number; 'mask-opacity'?: string | number; 'max-dim'?: string | number; 'pan-x'?: string | number; 'pan-y'?: string | number; 'placeholder'?: string | number; 'preview-mode'?: string | number; 'source'?: string | number; 'strength'?: string | number; 'tool'?: string | number; 'zoom'?: string | number }>
    'tc-number-input': TcProps<{ 'disabled'?: boolean; 'error'?: string | number; 'help'?: string | number; 'label'?: string | number; 'max'?: string | number; 'min'?: string | number; 'name'?: string | number; 'placeholder'?: string | number; 'precision'?: string | number; 'prefix'?: string | number; 'required'?: boolean; 'state'?: string | number; 'step'?: string | number; 'suffix'?: string | number; 'value'?: string | number; onTcChange?: (e: CustomEvent) => void }>
    'tc-objective-marker': TcProps<{ 'color'?: string | number; 'distance'?: string | number; 'label'?: string | number; 'pulse'?: boolean; 'size'?: string | number; 'x'?: string | number; 'y'?: string | number }>
    'tc-offcanvas': TcProps<{ 'backdrop'?: string | number; 'open'?: boolean; 'placement'?: string | number; 'scroll'?: boolean; 'title'?: string | number; onTcHidden?: (e: CustomEvent) => void; onTcHide?: (e: CustomEvent) => void; onTcShow?: (e: CustomEvent) => void; onTcShown?: (e: CustomEvent) => void }>
    'tc-option': TcProps<{ 'disabled'?: boolean; 'selected'?: boolean; 'value'?: string | number }>
    'tc-otp-input': TcProps<{ 'disabled'?: boolean; 'error'?: string | number; 'help'?: string | number; 'label'?: string | number; 'length'?: string | number; 'masked'?: boolean; 'mode'?: string | number; 'name'?: string | number; 'placeholder'?: string | number; 'required'?: boolean; 'state'?: string | number; 'value'?: string | number; onTcChange?: (e: CustomEvent) => void; onTcComplete?: (e: CustomEvent) => void }>
    'tc-page-footer': TcProps<{ 'brand'?: string | number; 'description'?: string | number; 'legal-text'?: string | number; 'tagline'?: string | number }>
    'tc-page-indicator': TcProps<{ 'active-color'?: string | number; 'color'?: string | number; 'count'?: string | number; 'gap'?: string | number; 'index'?: string | number; 'size'?: string | number; onTcSelect?: (e: CustomEvent) => void }>
    'tc-pagination': TcProps<{ 'align'?: string | number; 'current'?: string | number; 'max-visible'?: string | number; 'size'?: string | number; 'total'?: string | number; onTcPageChange?: (e: CustomEvent) => void }>
    'tc-panel': TcProps<{ 'bordered'?: boolean }>
    'tc-panel-header': TcProps<{ 'heading'?: string | number; 'icon'?: string | number }>
    'tc-particle-emitter': TcProps<{ 'burst'?: string | number; 'count'?: string | number; 'gravity'?: string | number; 'height'?: string | number; 'lifetime'?: string | number; 'particle-size'?: string | number; 'speed'?: string | number; 'width'?: string | number; onTcBurst?: (e: CustomEvent) => void }>
    'tc-party-panel': TcProps<{ 'capacity'?: string | number }>
    'tc-pause-menu': TcProps<{ 'default-items'?: boolean; 'menu-title'?: string | number; 'open'?: boolean; 'resume-footer'?: boolean; 'screen-title'?: string | number; onTcClose?: (e: CustomEvent) => void; onTcQuit?: (e: CustomEvent) => void; onTcRestart?: (e: CustomEvent) => void; onTcResume?: (e: CustomEvent) => void; onTcSelect?: (e: CustomEvent) => void }>
    'tc-pause-screen': TcProps<{ 'default-items'?: boolean; 'menu-title'?: string | number; 'open'?: boolean; 'resume-footer'?: boolean; 'screen-title'?: string | number; onTcClose?: (e: CustomEvent) => void; onTcQuit?: (e: CustomEvent) => void; onTcRestart?: (e: CustomEvent) => void; onTcResume?: (e: CustomEvent) => void; onTcSelect?: (e: CustomEvent) => void }>
    'tc-perk-picker': TcProps<{ 'columns'?: string | number; onTcSelect?: (e: CustomEvent) => void }>
    'tc-phase-grid': TcProps<{ 'columns'?: string | number }>
    'tc-phone-input': TcProps<{ 'default-country'?: string | number; 'disabled'?: boolean; 'error'?: string | number; 'help'?: string | number; 'label'?: string | number; 'max-height'?: string | number; 'name'?: string | number; 'placeholder'?: string | number; 'required'?: boolean; 'state'?: string | number; 'value'?: string | number; onTcChange?: (e: CustomEvent) => void }>
    'tc-physics-editor': TcProps<{ 'alpha-threshold'?: string | number; 'auto-fit'?: boolean; 'disabled'?: boolean; 'handle-hit'?: string | number; 'handle-size'?: string | number; 'handles'?: string | number; 'history-limit'?: string | number; 'max-alpha-dim'?: string | number; 'min-size'?: string | number; 'readonly'?: boolean; 'shapes'?: string | number; 'shortcuts'?: string | number; 'simplify-tolerance'?: string | number; 'snap'?: string | number; 'source'?: string | number; 'tool'?: string | number; onTcChange?: (e: CustomEvent) => void }>
    'tc-pie-chart': TcProps<{ 'center-label'?: string | number; 'donut'?: boolean; 'height'?: string | number; 'loading'?: boolean; 'show-legend'?: string | number; 'subtitle'?: string | number; 'title'?: string | number; onTcSliceSelect?: (e: CustomEvent) => void }>
    'tc-ping-display': TcProps<{ 'ping'?: string | number }>
    'tc-pinned-feature-showcase': TcProps<{ 'description'?: string | number; 'eyebrow'?: string | number; 'image-alt'?: string | number; 'image-src'?: string | number; 'title'?: string | number }>
    'tc-pipeline': TcProps
    'tc-placeholder': TcProps<{ 'animation'?: string | number; 'size'?: string | number; 'variant'?: string | number; 'width'?: string | number }>
    'tc-platform-icon': TcProps<{ 'label'?: boolean; 'platform'?: string | number; 'size'?: string | number }>
    'tc-player-card': TcProps<{ 'card-title'?: string | number; 'level'?: string | number; 'online-status'?: string | number; 'player-name'?: string | number; 'rank'?: string | number; onTcAction?: (e: CustomEvent) => void }>
    'tc-player-frame': TcProps<{ 'class-name'?: string | number; 'glyph'?: string | number; 'hp'?: string | number; 'hp-max'?: string | number; 'level'?: string | number; 'mp'?: string | number; 'mp-max'?: string | number; 'name'?: string | number; 'show-mp'?: boolean; 'show-stamina'?: boolean; 'stamina'?: string | number; 'stamina-max'?: string | number }>
    'tc-plugin-grid': TcProps<{ 'columns'?: string | number; 'title-text'?: string | number; onTcCopy?: (e: CustomEvent) => void }>
    'tc-popover': TcProps<{ onTcHidden?: (e: CustomEvent) => void; onTcHide?: (e: CustomEvent) => void; onTcShow?: (e: CustomEvent) => void; onTcShown?: (e: CustomEvent) => void }>
    'tc-portrait': TcProps<{ 'circle'?: boolean; 'glyph'?: string | number; 'level'?: string | number; 'ring'?: string | number; 'size'?: string | number }>
    'tc-press-any-key': TcProps<{ 'disabled'?: boolean; 'text'?: string | number }>
    'tc-pricing-card': TcProps<{ 'badge-text'?: string | number; 'description'?: string | number; 'highlight'?: boolean; 'name'?: string | number; 'period'?: string | number; 'price'?: string | number; onTcAction?: (e: CustomEvent) => void }>
    'tc-progress': TcProps<{ 'animated'?: boolean; 'label'?: boolean; 'max'?: string | number; 'min'?: string | number; 'striped'?: boolean; 'value'?: string | number; 'variant'?: string | number }>
    'tc-progress-bar': TcProps<{ 'animated'?: boolean; 'label'?: boolean; 'striped'?: boolean; 'value'?: string | number; 'variant'?: string | number }>
    'tc-pulse-indicator': TcProps<{ 'color'?: string | number; 'label'?: string | number; 'paused'?: boolean }>
    'tc-quest-tracker': TcProps<{ 'tracker-title'?: string | number }>
    'tc-queued-file': TcProps<{ 'extension'?: string | number; 'format'?: string | number; 'name'?: string | number; 'size'?: string | number; onTcDismiss?: (e: CustomEvent) => void }>
    'tc-quick-start': TcProps<{ 'title-text'?: string | number; onTcCopy?: (e: CustomEvent) => void }>
    'tc-radial-wheel': TcProps<{ 'center-label'?: string | number; 'open'?: boolean; 'option-size'?: string | number; 'per-page'?: string | number; 'radius'?: string | number; onTcClose?: (e: CustomEvent) => void; onTcSelect?: (e: CustomEvent) => void }>
    'tc-radio': TcProps<{ 'checked'?: boolean; 'disabled'?: boolean; 'error'?: string | number; 'help'?: string | number; 'inline'?: boolean; 'label'?: string | number; 'name'?: string | number; 'required'?: boolean; 'reverse'?: boolean; 'state'?: string | number; 'value'?: string | number; onTcChange?: (e: CustomEvent) => void }>
    'tc-radio-group': TcProps<{ 'disabled'?: boolean; 'error'?: string | number; 'help'?: string | number; 'inline'?: boolean; 'label'?: string | number; 'name'?: string | number; 'required'?: boolean; 'state'?: string | number; 'value'?: string | number; onTcChange?: (e: CustomEvent) => void }>
    'tc-range': TcProps<{ 'disabled'?: boolean; 'error'?: string | number; 'help'?: string | number; 'label'?: string | number; 'max'?: string | number; 'min'?: string | number; 'name'?: string | number; 'required'?: boolean; 'state'?: string | number; 'step'?: string | number; 'value'?: string | number; onTcChange?: (e: CustomEvent) => void }>
    'tc-range-slider': TcProps<{ 'disabled'?: boolean; 'error'?: string | number; 'help'?: string | number; 'label'?: string | number; 'max'?: string | number; 'min'?: string | number; 'name'?: string | number; 'required'?: boolean; 'show-tooltip'?: boolean; 'state'?: string | number; 'step'?: string | number; 'ticks'?: boolean; onTcChange?: (e: CustomEvent) => void }>
    'tc-rank-cell': TcProps<{ 'pad'?: string | number; 'rank'?: string | number }>
    'tc-rarity-chip': TcProps<{ 'rarity'?: string | number }>
    'tc-rating': TcProps<{ 'allow-half'?: boolean; 'count'?: string | number; 'icon'?: string | number; 'read-only'?: boolean; 'size'?: string | number; 'value'?: string | number; onTcChange?: (e: CustomEvent) => void }>
    'tc-report-dialog': TcProps<{ 'open'?: boolean; 'player-name'?: string | number; onTcCancel?: (e: CustomEvent) => void; onTcSubmit?: (e: CustomEvent) => void }>
    'tc-reset-to-defaults': TcProps<{ 'disabled'?: boolean; onTcReset?: (e: CustomEvent) => void }>
    'tc-resizable-panel': TcProps<{ 'direction'?: string | number; 'min-size'?: string | number; 'storage-key'?: string | number; onTcResize?: (e: CustomEvent) => void }>
    'tc-resource-bar': TcProps<{ 'ghost'?: string | number; 'label'?: string | number; 'max'?: string | number; 'segments'?: string | number; 'show-text'?: boolean; 'value'?: string | number; 'variant'?: string | number }>
    'tc-result-screen': TcProps<{ 'eyebrow'?: string | number; 'subtitle'?: string | number; 'title-color'?: string | number; 'title-text'?: string | number; 'variant'?: string | number; onTcAction?: (e: CustomEvent) => void }>
    'tc-rich-page-header': TcProps<{ 'description'?: string | number; 'icon-color'?: string | number; 'icon-name'?: string | number; 'sub'?: string | number; 'title-text'?: string | number }>
    'tc-roadmap': TcProps<{ 'layout'?: string | number; 'title-text'?: string | number; onTcSelect?: (e: CustomEvent) => void }>
    'tc-row': TcProps<{ 'align'?: string | number; 'cols'?: string | number; 'cols-lg'?: string | number; 'cols-md'?: string | number; 'cols-sm'?: string | number; 'cols-xl'?: string | number; 'cols-xxl'?: string | number; 'g'?: string | number; 'gutter'?: string | number; 'justify'?: string | number }>
    'tc-rune-corner': TcProps<{ 'at'?: string | number; 'size'?: string | number }>
    'tc-safe-area': TcProps<{ 'extra'?: string | number }>
    'tc-score-display': TcProps<{ 'align'?: string | number; 'font-size'?: string | number; 'label'?: string | number; 'multiplier'?: string | number; 'score'?: string | number }>
    'tc-scoring-rules': TcProps
    'tc-screen-flash': TcProps<{ 'duration'?: string | number; 'flash-color'?: string | number; 'flash-opacity'?: string | number; 'trigger'?: string | number; onTcDone?: (e: CustomEvent) => void }>
    'tc-scroll-area': TcProps<{ 'axis'?: string | number; 'max-height'?: string | number; 'max-width'?: string | number }>
    'tc-scroll-text': TcProps<{ 'max-height'?: string | number; 'scroll-title'?: string | number }>
    'tc-scrollspy': TcProps<{ 'offset'?: string | number; 'smooth-scroll'?: boolean; 'target'?: string | number; onTcActivate?: (e: CustomEvent) => void }>
    'tc-section-card': TcProps<{ 'icon'?: string | number; 'title'?: string | number; 'variant'?: string | number }>
    'tc-section-flag': TcProps<{ 'align'?: string | number; 'subtitle'?: string | number; 'title'?: string | number }>
    'tc-select': TcProps<{ 'disabled'?: boolean; 'error'?: string | number; 'help'?: string | number; 'label'?: string | number; 'multiple'?: boolean; 'name'?: string | number; 'placeholder'?: string | number; 'required'?: boolean; 'size'?: string | number; 'state'?: string | number; 'value'?: string | number; onTcChange?: (e: CustomEvent) => void }>
    'tc-select-row': TcProps<{ 'disabled'?: boolean; 'value'?: string | number; onTcChange?: (e: CustomEvent) => void }>
    'tc-setting-slider': TcProps<{ 'disabled'?: boolean; 'format'?: string | number; 'max'?: string | number; 'min'?: string | number; 'muted'?: boolean; 'step'?: string | number; 'unit'?: string | number; 'value'?: string | number; 'with-mute'?: boolean; onTcChange?: (e: CustomEvent) => void; onTcToggleMute?: (e: CustomEvent) => void }>
    'tc-settings-category-list': TcProps<{ 'selected-id'?: string | number; onTcSelect?: (e: CustomEvent) => void }>
    'tc-shake-container': TcProps<{ 'duration'?: string | number; 'intensity'?: string | number; 'trigger'?: string | number }>
    'tc-shop-panel': TcProps<{ 'currency'?: string | number; 'currency-icon'?: string | number; 'sell-mode'?: boolean }>
    'tc-side-nav': TcProps<{ 'loading'?: boolean; 'loading-count'?: string | number; onTcItemClick?: (e: CustomEvent) => void }>
    'tc-simple-file': TcProps<{ 'extension'?: string | number; 'format'?: string | number; 'name'?: string | number }>
    'tc-single-card-select': TcProps<{ 'columns'?: string | number; 'loading'?: boolean; 'loading-count'?: string | number; 'name'?: string | number; 'value'?: string | number; onTcChange?: (e: CustomEvent) => void }>
    'tc-skeleton': TcProps<{ 'count'?: string | number; 'height'?: string | number; 'variant'?: string | number; 'width'?: string | number }>
    'tc-skill-bar': TcProps<{ 'gap'?: string | number; 'slot-size'?: string | number; onTcActivate?: (e: CustomEvent) => void }>
    'tc-skill-tree': TcProps<{ 'height'?: string | number; 'points'?: string | number; 'selected-id'?: string | number; 'width'?: string | number; onTcSelect?: (e: CustomEvent) => void; onTcUnlock?: (e: CustomEvent) => void }>
    'tc-slices-card': TcProps<{ 'loading'?: boolean; 'size'?: string | number; 'stroke-width'?: string | number; 'title'?: string | number }>
    'tc-slider': TcProps<{ 'disabled'?: boolean; 'error'?: string | number; 'help'?: string | number; 'label'?: string | number; 'max'?: string | number; 'min'?: string | number; 'name'?: string | number; 'required'?: boolean; 'show-tooltip'?: boolean; 'state'?: string | number; 'step'?: string | number; 'ticks'?: boolean; 'value'?: string | number; onTcChange?: (e: CustomEvent) => void }>
    'tc-social-links': TcProps<{ 'size'?: string | number; 'variant'?: string | number }>
    'tc-spacer': TcProps<{ 'axis'?: string | number; 'size'?: string | number }>
    'tc-sparkline': TcProps<{ 'color'?: string | number; 'data'?: string | number; 'height'?: string | number; 'type'?: string | number; 'width'?: string | number }>
    'tc-spinner': TcProps<{ 'label'?: string | number; 'size'?: string | number; 'type'?: string | number; 'variant'?: string | number }>
    'tc-sponsor-wall': TcProps<{ 'title'?: string | number }>
    'tc-sprint-chain': TcProps<{ 'columns'?: string | number; 'current-id'?: string | number }>
    'tc-stack': TcProps<{ 'align'?: string | number; 'direction'?: string | number; 'gap'?: string | number; 'inline'?: boolean; 'justify'?: string | number; 'wrap'?: boolean }>
    'tc-stamina-bar': TcProps<{ 'ghost'?: string | number; 'label'?: string | number; 'max'?: string | number; 'segments'?: string | number; 'show-text'?: boolean; 'value'?: string | number; 'variant'?: string | number }>
    'tc-stamp': TcProps<{ 'angle'?: string | number; 'color'?: string | number; 'label'?: string | number; 'position'?: string | number }>
    'tc-stat-card': TcProps<{ 'delta'?: string | number; 'delta-kind'?: string | number; 'footer'?: string | number; 'helper'?: string | number; 'icon'?: string | number; 'label'?: string | number; 'loading'?: boolean; 'unit'?: string | number; 'value'?: string | number }>
    'tc-stat-row': TcProps<{ 'accent'?: string | number; 'label'?: string | number; 'trend'?: string | number; 'value'?: string | number }>
    'tc-state-machine': TcProps<{ 'compact'?: boolean }>
    'tc-stats-screen': TcProps<{ 'screen-title'?: string | number; 'summary'?: string | number }>
    'tc-status-card': TcProps<{ 'loading'?: boolean; 'loading-count'?: string | number; 'title'?: string | number }>
    'tc-status-dot': TcProps<{ 'label'?: string | number; 'pulse'?: boolean; 'size'?: string | number; 'status'?: string | number }>
    'tc-stepper': TcProps<{ 'active-step'?: string | number; 'clickable'?: boolean; 'orientation'?: string | number; onTcStepClick?: (e: CustomEvent) => void }>
    'tc-subtitle': TcProps<{ 'align'?: string | number; 'boxed'?: boolean; 'font-size'?: string | number; 'max-width'?: string | number; 'speaker'?: string | number; 'text'?: string | number }>
    'tc-switch': TcProps<{ 'checked'?: boolean; 'disabled'?: boolean; 'error'?: string | number; 'help'?: string | number; 'label'?: string | number; 'name'?: string | number; 'required'?: boolean; 'reverse'?: boolean; 'state'?: string | number; 'value'?: string | number; onTcChange?: (e: CustomEvent) => void }>
    'tc-tab-bar': TcProps<{ 'active-id'?: string | number; 'size'?: string | number; onTcChange?: (e: CustomEvent) => void }>
    'tc-tab-sections': TcProps<{ 'active-key'?: boolean; 'default-active-key'?: string | number; 'loading'?: boolean; onTcChange?: (e: CustomEvent) => void }>
    'tc-table': TcProps<{ 'borderless'?: boolean; 'collapse'?: string | number; 'collapse-below'?: string | number; 'compact'?: boolean; 'empty-message'?: string | number; 'hoverable'?: boolean; 'loading'?: boolean; 'loading-rows'?: string | number; 'sticky-first-column'?: boolean; 'sticky-header'?: boolean; 'sticky-last-column'?: boolean; 'striped'?: boolean; onTcRowClick?: (e: CustomEvent) => void }>
    'tc-tag': TcProps<{ 'count'?: string | number; 'disabled'?: boolean; 'icon'?: string | number; 'removable'?: boolean; 'selected'?: boolean; 'static'?: boolean; 'variant'?: string | number; onTcClick?: (e: CustomEvent) => void; onTcRemove?: (e: CustomEvent) => void }>
    'tc-tag-input': TcProps<{ 'allow-create'?: boolean; 'disabled'?: boolean; 'error'?: string | number; 'help'?: string | number; 'label'?: string | number; 'loading'?: boolean; 'max-height'?: string | number; 'max-tags'?: string | number; 'name'?: string | number; 'placeholder'?: string | number; 'required'?: boolean; 'state'?: string | number; onTcChange?: (e: CustomEvent) => void }>
    'tc-team-list': TcProps
    'tc-terminal-window': TcProps<{ 'animate-typing'?: boolean; 'prompt'?: string | number; 'speed'?: string | number; 'title'?: string | number }>
    'tc-testimonial-carousel': TcProps<{ 'autoplay'?: boolean; 'interval'?: string | number; onTcChange?: (e: CustomEvent) => void }>
    'tc-text': TcProps<{ 'as'?: string | number; 'size'?: string | number; 'variant'?: string | number }>
    'tc-textarea': TcProps<{ 'autocomplete'?: string | number; 'disabled'?: boolean; 'error'?: string | number; 'help'?: string | number; 'inputmode'?: string | number; 'label'?: string | number; 'max'?: string | number; 'maxlength'?: string | number; 'min'?: string | number; 'minlength'?: string | number; 'name'?: string | number; 'pattern'?: string | number; 'placeholder'?: string | number; 'readonly'?: boolean; 'required'?: boolean; 'rows'?: string | number; 'size'?: string | number; 'state'?: string | number; 'step'?: string | number; 'value'?: string | number }>
    'tc-theme': TcProps<{ 'name'?: string | number; 'variant'?: string | number }>
    'tc-tier-ladder': TcProps<{ 'current-tier-id'?: string | number; 'summary'?: string | number; 'title'?: string | number }>
    'tc-time-picker': TcProps<{ 'clearable'?: boolean; 'disabled'?: boolean; 'error'?: string | number; 'format'?: string | number; 'help'?: string | number; 'label'?: string | number; 'minute-step'?: string | number; 'name'?: string | number; 'placeholder'?: string | number; 'required'?: boolean; 'show-seconds'?: boolean; 'state'?: string | number; 'value'?: string | number; onTcChange?: (e: CustomEvent) => void }>
    'tc-timeline': TcProps<{ 'connector'?: string | number; 'loading'?: boolean; 'loading-count'?: string | number; 'overlap'?: string | number; 'variant'?: string | number }>
    'tc-title': TcProps<{ 'align'?: string | number; 'size'?: string | number }>
    'tc-title-screen': TcProps<{ 'eyebrow'?: string | number; 'subtitle'?: string | number; 'title-text'?: string | number }>
    'tc-toast': TcProps<{ 'autohide'?: string | number; 'delay'?: string | number; 'open'?: boolean; 'title'?: string | number; 'variant'?: string | number; onTcHidden?: (e: CustomEvent) => void; onTcHide?: (e: CustomEvent) => void; onTcShow?: (e: CustomEvent) => void; onTcShown?: (e: CustomEvent) => void }>
    'tc-toggle': TcProps<{ 'disabled'?: boolean; 'label'?: string | number; 'on'?: boolean; onTcChange?: (e: CustomEvent) => void }>
    'tc-toggle-card': TcProps<{ 'badge'?: string | number; 'checked'?: boolean; 'disabled'?: boolean; 'hint'?: string | number; 'icon'?: string | number; 'label'?: string | number; 'loading'?: boolean; 'name'?: string | number; 'value'?: string | number; onTcChange?: (e: CustomEvent) => void }>
    'tc-toggle-row': TcProps<{ 'checked'?: boolean; 'disabled'?: boolean; onTcChange?: (e: CustomEvent) => void }>
    'tc-tooltip': TcProps<{ onTcHidden?: (e: CustomEvent) => void; onTcHide?: (e: CustomEvent) => void; onTcShow?: (e: CustomEvent) => void; onTcShown?: (e: CustomEvent) => void }>
    'tc-transition-wipe': TcProps<{ 'direction'?: string | number; 'duration'?: string | number; 'show'?: boolean; 'wipe-color'?: string | number; onTcComplete?: (e: CustomEvent) => void }>
    'tc-tree-view': TcProps<{ 'checkbox-mode'?: boolean; onTcExpandChange?: (e: CustomEvent) => void; onTcSelect?: (e: CustomEvent) => void }>
    'tc-trend-indicator': TcProps<{ 'direction'?: string | number; 'size'?: string | number; 'value'?: string | number }>
    'tc-tyre-spec': TcProps<{ 'front-spec'?: string | number; 'rear-spec'?: string | number; 'spec'?: string | number }>
    'tc-usage-summary-panel': TcProps<{ 'loading'?: boolean; 'loading-count'?: string | number; 'title'?: string | number }>
    'tc-user-panel': TcProps<{ 'avatar-src'?: string | number; 'icon'?: string | number; 'icon-highlighted'?: boolean; 'icon-label'?: string | number; 'initials'?: string | number; 'loading'?: boolean; 'plan'?: string | number; 'username'?: string | number; onTcIconClick?: (e: CustomEvent) => void; onTcMenuClick?: (e: CustomEvent) => void }>
    'tc-variant-spec-sheet': TcProps<{ 'dense'?: boolean; 'name'?: string | number; 'slug'?: string | number; 'version'?: string | number; 'years-text'?: string | number }>
    'tc-version-label': TcProps<{ 'branch'?: string | number; 'build'?: string | number; 'version'?: string | number }>
    'tc-version-picker': TcProps<{ 'name'?: string | number; 'value'?: string | number; 'variant'?: string | number; onTcChange?: (e: CustomEvent) => void }>
    'tc-vertical-item-list': TcProps<{ 'active-key'?: boolean; 'default-active-key'?: string | number; 'disabled'?: boolean; 'loading'?: boolean; 'loading-count'?: string | number; onTcSelect?: (e: CustomEvent) => void }>
    'tc-victory-screen': TcProps<{ 'eyebrow'?: string | number; 'subtitle'?: string | number; 'title-color'?: string | number; 'title-text'?: string | number; 'variant'?: string | number; onTcAction?: (e: CustomEvent) => void }>
    'tc-video-embed': TcProps<{ 'aspect-ratio'?: string | number; 'autoplay'?: boolean; 'controls'?: string | number; 'loop'?: boolean; 'muted'?: boolean; 'poster'?: string | number; 'src'?: string | number; 'title'?: string | number }>
    'tc-vignette-overlay': TcProps<{ 'intensity'?: string | number; 'vignette-color'?: string | number }>
    'tc-virtual-list': TcProps<{ 'end-reached-threshold'?: string | number; 'height'?: string | number; 'overscan'?: string | number; onTcEndReached?: (e: CustomEvent) => void }>
    'tc-visually-hidden': TcProps<{ 'as'?: string | number }>
    'tc-volume-slider': TcProps<{ 'disabled'?: boolean; 'format'?: string | number; 'max'?: string | number; 'min'?: string | number; 'muted'?: boolean; 'step'?: string | number; 'unit'?: string | number; 'value'?: string | number; 'with-mute'?: boolean; onTcChange?: (e: CustomEvent) => void; onTcToggleMute?: (e: CustomEvent) => void }>
    'tc-waypoint-marker': TcProps<{ 'color'?: string | number; 'distance'?: string | number; 'icon'?: string | number; 'label'?: string | number; 'size'?: string | number; 'x'?: string | number; 'y'?: string | number }>
    'tc-welcome-guide': TcProps<{ 'background-pattern-alt'?: string | number; 'background-pattern-src'?: string | number; 'loading'?: boolean; 'title'?: string | number }>
}

// React 17+ automatic runtime / React 19 — IntrinsicElements lives on React.JSX.
declare module 'react' {
    namespace JSX {
        interface IntrinsicElements extends ToolcaseIntrinsicElements {}
    }
}

// Classic global JSX namespace — React 18 and the legacy runtime.
declare global {
    namespace JSX {
        interface IntrinsicElements extends ToolcaseIntrinsicElements {}
    }
}

export {}
