// AUTO-GENERATED by scripts/gen-react-types.mjs — do not edit by hand.
// Opt-in React JSX typings for @toolcase/web-components custom elements.
//
// Import via the package's ./react entry point (src/react.ts), which also
// exports the useTc / useTcEvents runtime hooks.
//
// Regenerate after adding/removing a component or attribute:
//     npm -w @toolcase/web-components run gen:react-types

import type * as React from 'react'

/**
 * Props for a toolcase custom element: standard HTML attributes (className,
 * style, ref, event handlers, …) plus the element's own kebab-case attributes
 * in `T` for autocomplete. Typos in attribute names are now a TypeScript error.
 * Use useTc() to wire the on* event handler props at runtime.
 */
export type TcProps<T = {}> = React.DetailedHTMLProps<
    React.HTMLAttributes<HTMLElement> & T,
    HTMLElement
>

export interface ToolcaseIntrinsicElements {
    'tc-ability-card': TcProps<{ 'ability-name'?: string | number | boolean; 'cooldown'?: string | number | boolean; 'cost'?: string | number | boolean; 'description'?: string | number | boolean; 'icon'?: string | number | boolean; 'keybind'?: string | number | boolean; 'range'?: string | number | boolean; 'rarity'?: string | number | boolean }>
    'tc-accordion': TcProps<{ 'always-open'?: string | number | boolean; 'flush'?: string | number | boolean }>
    'tc-accordion-item': TcProps<{ 'header'?: string | number | boolean; 'open'?: string | number | boolean; onTcShow?: (e: CustomEvent) => void; onTcShown?: (e: CustomEvent) => void; onTcHide?: (e: CustomEvent) => void; onTcHidden?: (e: CustomEvent) => void }>
    'tc-action-header': TcProps<{ 'disabled'?: string | number | boolean; onTcExec?: (e: CustomEvent) => void }>
    'tc-action-items': TcProps<{ 'label'?: string | number | boolean; onTcActionClick?: (e: CustomEvent) => void }>
    'tc-action-row-list': TcProps<{ 'outline'?: string | number | boolean; 'trailing-icon'?: string | number | boolean; onTcActionClick?: (e: CustomEvent) => void }>
    'tc-activity-card': TcProps<{ 'loading'?: string | number | boolean; 'loading-count'?: string | number | boolean; 'title'?: string | number | boolean }>
    'tc-advanced-table': TcProps<{ 'limit'?: string | number | boolean; 'loading'?: string | number | boolean; 'offset'?: string | number | boolean; 'total'?: string | number | boolean; onTcFilterChange?: (e: CustomEvent) => void; onTcSortChange?: (e: CustomEvent) => void; onTcPageChange?: (e: CustomEvent) => void }>
    'tc-alert': TcProps<{ 'dismissible'?: string | number | boolean; 'variant'?: string | number | boolean; onTcClosed?: (e: CustomEvent) => void }>
    'tc-ammo-counter': TcProps<{ 'mag'?: string | number | boolean; 'mag-max'?: string | number | boolean; 'reloading'?: string | number | boolean; 'reserve'?: string | number | boolean; 'weapon-name'?: string | number | boolean }>
    'tc-anchor': TcProps<{ 'inset'?: string | number | boolean; 'position'?: string | number | boolean }>
    'tc-announcement-bar': TcProps<{ 'cta-href'?: string | number | boolean; 'cta-label'?: string | number | boolean; 'dismissible'?: string | number | boolean; 'icon'?: string | number | boolean; 'icon-name'?: string | number | boolean; 'persist-dismiss-key'?: string | number | boolean; 'storage-key'?: string | number | boolean; 'variant'?: string | number | boolean }>
    'tc-api-reference-table': TcProps<{ 'title'?: string | number | boolean }>
    'tc-area-chart': TcProps<{ onTcPointHover?: (e: CustomEvent) => void }>
    'tc-artboard-backdrop': TcProps<{ 'kind'?: string | number | boolean; 'padding'?: string | number | boolean }>
    'tc-aspect-ratio-box': TcProps<{ 'ratio'?: string | number | boolean }>
    'tc-asset-bundle': TcProps<{ 'build-tag'?: string | number | boolean; 'category'?: string | number | boolean; 'default-build-tag'?: string | number | boolean; 'latest-build-ref'?: string | number | boolean; 'loading'?: string | number | boolean; 'name'?: string | number | boolean; 'target'?: string | number | boolean; 'target-icon'?: string | number | boolean; onTcAdvancedToggle?: (e: CustomEvent) => void; onTcBuildTagChange?: (e: CustomEvent) => void; onTcMenuClick?: (e: CustomEvent) => void }>
    'tc-asset-row': TcProps<{ 'icon'?: string | number | boolean; 'name'?: string | number | boolean; 'size'?: string | number | boolean }>
    'tc-asset-row-list': TcProps
    'tc-audio-mixer': TcProps<{ 'current-ms'?: string | number | boolean; 'disabled'?: string | number | boolean; 'loading'?: string | number | boolean }>
    'tc-avatar': TcProps<{ 'alt'?: string | number | boolean; 'name'?: string | number | boolean; 'size'?: string | number | boolean; 'src'?: string | number | boolean; 'status'?: string | number | boolean; 'variant'?: string | number | boolean }>
    'tc-badge': TcProps<{ 'pill'?: string | number | boolean; 'text'?: string | number | boolean; 'variant'?: string | number | boolean }>
    'tc-badge-row': TcProps<{ 'size'?: string | number | boolean }>
    'tc-banner': TcProps<{ 'cta-href'?: string | number | boolean; 'cta-label'?: string | number | boolean; 'dismissible'?: string | number | boolean; 'icon'?: string | number | boolean; 'icon-name'?: string | number | boolean; 'persist-dismiss-key'?: string | number | boolean; 'storage-key'?: string | number | boolean; 'variant'?: string | number | boolean; onTcDismiss?: (e: CustomEvent) => void }>
    'tc-bar-chart': TcProps<{ onTcBarClick?: (e: CustomEvent) => void }>
    'tc-basic-card': TcProps
    'tc-basic-layout': TcProps<{ 'brand'?: string | number | boolean }>
    'tc-battle-pass': TcProps<{ 'current-level'?: string | number | boolean; 'current-xp'?: string | number | boolean; 'has-premium'?: string | number | boolean; 'season-end'?: string | number | boolean; 'season-name'?: string | number | boolean; onTcClaim?: (e: CustomEvent) => void }>
    'tc-benchmark-chart': TcProps<{ onTcBarClick?: (e: CustomEvent) => void }>
    'tc-bitmap-font-generator': TcProps<{ 'background'?: string | number | boolean; 'disabled'?: string | number | boolean; 'export-format'?: string | number | boolean; 'font-family'?: string | number | boolean; 'font-size'?: string | number | boolean; 'glyphs'?: string | number | boolean; 'glyphs-per-row'?: string | number | boolean; 'letter-spacing'?: string | number | boolean; 'line-height'?: string | number | boolean; 'padding'?: string | number | boolean; 'power-of-two'?: string | number | boolean; 'scale'?: string | number | boolean; 'text'?: string | number | boolean }>
    'tc-blur-overlay': TcProps<{ 'background'?: string | number | boolean; 'blur-amount'?: string | number | boolean }>
    'tc-boss-bar': TcProps<{ 'epithet'?: string | number | boolean; 'hp'?: string | number | boolean; 'hp-max'?: string | number | boolean; 'name'?: string | number | boolean; 'phase'?: string | number | boolean }>
    'tc-brand': TcProps<{ 'color'?: string | number | boolean; 'label'?: string | number | boolean; 'primary-text'?: string | number | boolean; 'secondary-text'?: string | number | boolean; 'xlarge'?: string | number | boolean }>
    'tc-breadcrumb': TcProps<{ 'divider'?: string | number | boolean }>
    'tc-breadcrumb-item': TcProps<{ 'active'?: string | number | boolean; 'href'?: string | number | boolean }>
    'tc-brief-card': TcProps<{ 'body'?: string | number | boolean; 'brief-id'?: string | number | boolean; 'clickable'?: string | number | boolean; 'difficulty'?: string | number | boolean; 'icon'?: string | number | boolean; 'meta-left'?: string | number | boolean; 'meta-right'?: string | number | boolean; 'title'?: string | number | boolean; onTcClick?: (e: CustomEvent) => void }>
    'tc-brightness-calibration': TcProps<{ 'value'?: string | number | boolean; onTcChange?: (e: CustomEvent) => void }>
    'tc-buff-bar': TcProps<{ 'gap'?: string | number | boolean; 'icon-size'?: string | number | boolean }>
    'tc-buff-icon': TcProps<{ 'color'?: string | number | boolean; 'glyph'?: string | number | boolean; 'kind'?: string | number | boolean; 'size'?: string | number | boolean; 'time'?: string | number | boolean }>
    'tc-build': TcProps<{ 'badge'?: string | number | boolean; 'badge-variant'?: string | number | boolean; 'date'?: string | number | boolean; 'duration'?: string | number | boolean; 'loading'?: string | number | boolean; 'name'?: string | number | boolean; 'size'?: string | number | boolean; 'status'?: string | number | boolean; onTcClick?: (e: CustomEvent) => void; onTcMenuSelect?: (e: CustomEvent) => void }>
    'tc-bundle-bar': TcProps<{ 'filled-segments'?: string | number | boolean; 'meta'?: string | number | boolean; 'name'?: string | number | boolean; 'segments'?: string | number | boolean }>
    'tc-button': TcProps<{ 'disabled'?: string | number | boolean; 'href'?: string | number | boolean; 'loading'?: string | number | boolean; 'outline'?: string | number | boolean; 'size'?: string | number | boolean; 'skin'?: string | number | boolean; 'type'?: string | number | boolean; 'variant'?: string | number | boolean }>
    'tc-button-group': TcProps<{ 'aria-label'?: string | number | boolean; 'size'?: string | number | boolean; 'vertical'?: string | number | boolean }>
    'tc-callout-quote': TcProps<{ 'attribution'?: string | number | boolean; 'quote'?: string | number | boolean; 'source'?: string | number | boolean; 'source-href'?: string | number | boolean }>
    'tc-card': TcProps<{ 'img'?: string | number | boolean; 'img-position'?: string | number | boolean; 'subtitle'?: string | number | boolean; 'title'?: string | number | boolean; 'variant'?: string | number | boolean }>
    'tc-card-options': TcProps<{ 'columns'?: string | number | boolean; 'value'?: string | number | boolean; onTcChange?: (e: CustomEvent) => void }>
    'tc-carousel': TcProps<{ 'controls'?: string | number | boolean; 'fade'?: string | number | boolean; 'indicators'?: string | number | boolean; 'interval'?: string | number | boolean; 'pause'?: string | number | boolean; 'ride'?: string | number | boolean; onTcSlide?: (e: CustomEvent) => void; onTcSlid?: (e: CustomEvent) => void }>
    'tc-cdn-map': TcProps<{ 'height'?: string | number | boolean }>
    'tc-changelog': TcProps<{ 'loading'?: string | number | boolean; 'max-visible'?: string | number | boolean; 'read-more-href'?: string | number | boolean; 'read-more-label'?: string | number | boolean }>
    'tc-character-create': TcProps<{ 'confirm-label'?: string | number | boolean; 'heading'?: string | number | boolean; 'name'?: string | number | boolean; 'name-placeholder'?: string | number | boolean; onTcName?: (e: CustomEvent) => void; onTcChange?: (e: CustomEvent) => void; onTcConfirm?: (e: CustomEvent) => void }>
    'tc-character-select': TcProps<{ 'selected-id'?: string | number | boolean; onTcSelect?: (e: CustomEvent) => void; onTcConfirm?: (e: CustomEvent) => void }>
    'tc-chart-container': TcProps<{ 'empty'?: string | number | boolean; 'loading'?: string | number | boolean; 'subtitle'?: string | number | boolean; 'title'?: string | number | boolean }>
    'tc-chat-window': TcProps<{ 'active-channel'?: string | number | boolean; 'height'?: string | number | boolean; 'placeholder'?: string | number | boolean; 'width'?: string | number | boolean; onTcChannelChange?: (e: CustomEvent) => void; onTcSend?: (e: CustomEvent) => void }>
    'tc-check': TcProps<{ 'checked'?: string | number | boolean; 'disabled'?: string | number | boolean; 'indeterminate'?: string | number | boolean; 'inline'?: string | number | boolean; 'label'?: string | number | boolean; 'reverse'?: string | number | boolean; 'state'?: string | number | boolean; 'value'?: string | number | boolean }>
    'tc-checkbox-group': TcProps<{ 'inline'?: string | number | boolean; 'label'?: string | number | boolean; 'name'?: string | number | boolean; 'required'?: string | number | boolean; onTcChange?: (e: CustomEvent) => void }>
    'tc-chip': TcProps<{ 'count'?: string | number | boolean; 'disabled'?: string | number | boolean; 'icon'?: string | number | boolean; 'removable'?: string | number | boolean; 'selected'?: string | number | boolean; 'static'?: string | number | boolean; 'variant'?: string | number | boolean; onTcClick?: (e: CustomEvent) => void; onTcRemove?: (e: CustomEvent) => void }>
    'tc-chip-group': TcProps<{ 'border'?: string | number | boolean; 'subtitle'?: string | number | boolean; 'title'?: string | number | boolean; onTcToggle?: (e: CustomEvent) => void }>
    'tc-circular-progress': TcProps<{ 'background'?: string | number | boolean; 'color'?: string | number | boolean; 'max'?: string | number | boolean; 'reverse'?: string | number | boolean; 'show-text'?: string | number | boolean; 'size'?: string | number | boolean; 'thickness'?: string | number | boolean; 'value'?: string | number | boolean }>
    'tc-close-button': TcProps<{ 'aria-label'?: string | number | boolean; 'disabled'?: string | number | boolean }>
    'tc-code-label-cell': TcProps<{ 'code'?: string | number | boolean; 'name'?: string | number | boolean }>
    'tc-code-snippet': TcProps<{ 'code'?: string | number | boolean; 'language'?: string | number | boolean; 'loading'?: string | number | boolean; 'show-copy-button'?: string | number | boolean; 'title'?: string | number | boolean; onTcCopy?: (e: CustomEvent) => void }>
    'tc-code-with-output': TcProps<{ 'code'?: string | number | boolean; 'language'?: string | number | boolean; 'layout'?: string | number | boolean; 'title'?: string | number | boolean }>
    'tc-codex': TcProps<{ 'selected-id'?: string | number | boolean; onTcSelect?: (e: CustomEvent) => void }>
    'tc-col': TcProps<{ 'order'?: string | number | boolean; 'span'?: string | number | boolean }>
    'tc-collapse': TcProps<{ 'horizontal'?: string | number | boolean; 'open'?: string | number | boolean; onTcShow?: (e: CustomEvent) => void; onTcShown?: (e: CustomEvent) => void; onTcHide?: (e: CustomEvent) => void; onTcHidden?: (e: CustomEvent) => void }>
    'tc-color-picker': TcProps<{ 'columns'?: string | number | boolean; 'disabled'?: string | number | boolean; 'label'?: string | number | boolean; 'loading'?: string | number | boolean; 'value'?: string | number | boolean; onTcChange?: (e: CustomEvent) => void }>
    'tc-colored-card': TcProps
    'tc-combo-box': TcProps<{ 'disabled'?: string | number | boolean; 'placeholder'?: string | number | boolean; 'value'?: string | number | boolean; onTcChange?: (e: CustomEvent) => void }>
    'tc-combo-counter': TcProps<{ 'combo'?: string | number | boolean; 'font-size'?: string | number | boolean; 'label'?: string | number | boolean; 'timer'?: string | number | boolean }>
    'tc-command-palette': TcProps<{ 'loading'?: string | number | boolean; 'open'?: string | number | boolean; 'placeholder'?: string | number | boolean; onTcClose?: (e: CustomEvent) => void; onTcSelect?: (e: CustomEvent) => void }>
    'tc-command-reference': TcProps<{ 'search-placeholder'?: string | number | boolean; 'searchable'?: string | number | boolean; 'title'?: string | number | boolean; onTcSearch?: (e: CustomEvent) => void }>
    'tc-community-links': TcProps<{ 'title'?: string | number | boolean }>
    'tc-comparator': TcProps<{ 'description'?: string | number | boolean; 'loading'?: string | number | boolean; 'loading-count'?: string | number | boolean; 'show-summary'?: string | number | boolean; 'title'?: string | number | boolean }>
    'tc-compass-bar': TcProps<{ 'fov'?: string | number | boolean; 'heading'?: string | number | boolean; 'height'?: string | number | boolean; 'show-cardinals'?: string | number | boolean; 'width'?: string | number | boolean }>
    'tc-compass-rose': TcProps<{ 'heading'?: string | number | boolean; 'size'?: string | number | boolean }>
    'tc-compatibility-matrix': TcProps<{ 'title'?: string | number | boolean }>
    'tc-config-preview': TcProps<{ 'live-label'?: string | number | boolean }>
    'tc-confirm-dialog': TcProps<{ 'cancel-label'?: string | number | boolean; 'confirm-label'?: string | number | boolean; 'danger'?: string | number | boolean; 'dialog-title'?: string | number | boolean; 'eyebrow'?: string | number | boolean; 'message'?: string | number | boolean; 'open'?: string | number | boolean; onTcConfirm?: (e: CustomEvent) => void; onTcCancel?: (e: CustomEvent) => void }>
    'tc-container': TcProps<{ 'breakpoint'?: string | number | boolean; 'fluid'?: string | number | boolean }>
    'tc-context-menu': TcProps<{ onTcSelect?: (e: CustomEvent) => void }>
    'tc-contributor-wall': TcProps<{ 'max-visible'?: string | number | boolean; 'title'?: string | number | boolean }>
    'tc-controller-layout-preview': TcProps<{ 'layout'?: string | number | boolean }>
    'tc-controls-rebind-list': TcProps<{ onTcRebind?: (e: CustomEvent) => void }>
    'tc-cookbook-grid': TcProps<{ 'columns'?: string | number | boolean; 'title'?: string | number | boolean }>
    'tc-cool-button': TcProps<{ 'addon'?: string | number | boolean; 'addon-position'?: string | number | boolean; 'disabled'?: string | number | boolean; 'label'?: string | number | boolean; 'loading'?: string | number | boolean; 'outline'?: string | number | boolean; 'size'?: string | number | boolean; 'variant'?: string | number | boolean; onTcClick?: (e: CustomEvent) => void }>
    'tc-cool-nav': TcProps<{ 'brand'?: string | number | boolean; 'expand-breakpoint'?: string | number | boolean; 'login-href'?: string | number | boolean; 'login-label'?: string | number | boolean; 'login-variant'?: string | number | boolean; 'scroll-offset'?: string | number | boolean; 'sticky'?: string | number | boolean; 'theme'?: string | number | boolean; onTcLogin?: (e: CustomEvent) => void; onTcNavToggle?: (e: CustomEvent) => void }>
    'tc-cooldown-badge': TcProps<{ 'label'?: string | number | boolean; 'max'?: string | number | boolean; 'show-label'?: string | number | boolean; 'size'?: string | number | boolean; 'value'?: string | number | boolean }>
    'tc-countdown-timer': TcProps<{ 'compact'?: string | number | boolean; 'label'?: string | number | boolean; 'sub-label'?: string | number | boolean; 'target'?: string | number | boolean; 'units'?: string | number | boolean; onTcExpire?: (e: CustomEvent) => void }>
    'tc-crafting-panel': TcProps<{ 'crafting'?: string | number | boolean; 'selected-id'?: string | number | boolean; onTcSelect?: (e: CustomEvent) => void; onTcCraft?: (e: CustomEvent) => void }>
    'tc-credits-scroll': TcProps<{ 'scroll-title'?: string | number | boolean; 'speed'?: string | number | boolean; onTcComplete?: (e: CustomEvent) => void }>
    'tc-crosshair': TcProps<{ 'color'?: string | number | boolean; 'gap'?: string | number | boolean; 'size'?: string | number | boolean; 'spread'?: string | number | boolean; 'thickness'?: string | number | boolean; 'variant'?: string | number | boolean }>
    'tc-currency-chip': TcProps<{ 'amount'?: string | number | boolean; 'color'?: string | number | boolean; 'glyph'?: string | number | boolean }>
    'tc-currency-display': TcProps<{ 'amount'?: string | number | boolean; 'color'?: string | number | boolean; 'currency-icon'?: string | number | boolean; 'font-size'?: string | number | boolean; 'label'?: string | number | boolean }>
    'tc-cycle-wheel': TcProps<{ 'center-label'?: string | number | boolean; 'center-pill'?: string | number | boolean; 'center-sub'?: string | number | boolean; 'center-value'?: string | number | boolean; 'current-index'?: string | number | boolean; 'paused'?: string | number | boolean; 'spin-seconds'?: string | number | boolean }>
    'tc-damage-number': TcProps<{ 'crit'?: string | number | boolean; 'duration'?: string | number | boolean; 'heal'?: string | number | boolean; 'miss'?: string | number | boolean; 'value'?: string | number | boolean; onTcDone?: (e: CustomEvent) => void }>
    'tc-danger-zone-actions': TcProps<{ 'class-name'?: string | number | boolean; onTcActionClick?: (e: CustomEvent) => void }>
    'tc-dashboard-content': TcProps
    'tc-dashboard-layout': TcProps<{ 'sidebar-open'?: string | number | boolean; onTcToggleSidebar?: (e: CustomEvent) => void }>
    'tc-dashboard-sidebar': TcProps
    'tc-data-list': TcProps<{ 'empty-text'?: string | number | boolean; 'list-title'?: string | number | boolean; 'selectable'?: string | number | boolean; 'selected-id'?: string | number | boolean; onTcSelect?: (e: CustomEvent) => void; onTcAction?: (e: CustomEvent) => void }>
    'tc-date-picker': TcProps<{ 'disabled'?: string | number | boolean; 'label'?: string | number | boolean; 'max'?: string | number | boolean; 'min'?: string | number | boolean; 'value'?: string | number | boolean; onTcChange?: (e: CustomEvent) => void }>
    'tc-deadzone-slider': TcProps<{ 'disabled'?: string | number | boolean; 'format'?: string | number | boolean; 'max'?: string | number | boolean; 'min'?: string | number | boolean; 'muted'?: string | number | boolean; 'step'?: string | number | boolean; 'unit'?: string | number | boolean; 'value'?: string | number | boolean; 'with-mute'?: string | number | boolean }>
    'tc-debug-overlay': TcProps<{ 'draw-calls'?: string | number | boolean; 'fps'?: string | number | boolean; 'mem-mb'?: string | number | boolean; 'triangles'?: string | number | boolean }>
    'tc-dialogue-box': TcProps<{ 'speaker'?: string | number | boolean; 'text'?: string | number | boolean; 'typing-speed'?: string | number | boolean }>
    'tc-diff-viewer': TcProps<{ 'after'?: string | number | boolean; 'before'?: string | number | boolean; 'filename'?: string | number | boolean; 'language'?: string | number | boolean; 'mode'?: string | number | boolean; onTcRender?: (e: CustomEvent) => void }>
    'tc-difference-card': TcProps<{ 'loading'?: string | number | boolean; 'period'?: string | number | boolean; 'previous-value'?: string | number | boolean; 'title'?: string | number | boolean; 'value'?: string | number | boolean }>
    'tc-divider': TcProps<{ 'label'?: string | number | boolean; 'vertical'?: string | number | boolean }>
    'tc-download-stats': TcProps<{ 'monthly'?: string | number | boolean; 'package-name'?: string | number | boolean; 'registry'?: string | number | boolean; 'total'?: string | number | boolean; 'weekly'?: string | number | boolean }>
    'tc-drawer': TcProps<{ 'open'?: string | number | boolean; 'pinned'?: string | number | boolean; 'side'?: string | number | boolean; 'size'?: string | number | boolean; 'title'?: string | number | boolean; onTcClose?: (e: CustomEvent) => void }>
    'tc-dropdown': TcProps<{ 'auto-close'?: string | number | boolean; 'direction'?: string | number | boolean; 'label'?: string | number | boolean; 'split'?: string | number | boolean; 'variant'?: string | number | boolean; onTcShow?: (e: CustomEvent) => void; onTcShown?: (e: CustomEvent) => void; onTcHide?: (e: CustomEvent) => void; onTcHidden?: (e: CustomEvent) => void }>
    'tc-dropdown-item': TcProps<{ 'active'?: string | number | boolean; 'disabled'?: string | number | boolean; 'divider'?: string | number | boolean; 'href'?: string | number | boolean }>
    'tc-early-signup-form': TcProps<{ 'cta-label'?: string | number | boolean; 'eyebrow'?: string | number | boolean; 'field-label'?: string | number | boolean; 'helper-text'?: string | number | boolean; 'loading'?: string | number | boolean; 'placeholder'?: string | number | boolean; 'stat'?: string | number | boolean; 'subtitle'?: string | number | boolean; 'success-message'?: string | number | boolean; 'success-title'?: string | number | boolean; 'title'?: string | number | boolean; 'variant'?: string | number | boolean; onTcSubmit?: (e: CustomEvent) => void }>
    'tc-ecosystem-map': TcProps<{ 'size'?: string | number | boolean; 'title'?: string | number | boolean; onTcSelect?: (e: CustomEvent) => void }>
    'tc-editable-text': TcProps<{ 'aria-label'?: string | number | boolean; 'default-value'?: string | number | boolean; 'disabled'?: string | number | boolean; 'placeholder'?: string | number | boolean; onTcChange?: (e: CustomEvent) => void }>
    'tc-empty-state': TcProps<{ 'icon'?: string | number | boolean }>
    'tc-entity-cell': TcProps<{ 'clickable'?: string | number | boolean; 'color'?: string | number | boolean; 'initial'?: string | number | boolean; 'name'?: string | number | boolean; 'size'?: string | number | boolean; 'sub-label'?: string | number | boolean; onTcClick?: (e: CustomEvent) => void }>
    'tc-entity-profile-card': TcProps
    'tc-equipment-doll': TcProps<{ 'height'?: string | number | boolean; 'selected-id'?: string | number | boolean; 'silhouette'?: string | number | boolean; 'slot-size'?: string | number | boolean; 'width'?: string | number | boolean; onTcSelect?: (e: CustomEvent) => void }>
    'tc-extended-select': TcProps<{ 'loading'?: string | number | boolean; 'name'?: string | number | boolean; 'no-results-text'?: string | number | boolean; 'placeholder'?: string | number | boolean; 'search-placeholder'?: string | number | boolean; 'value'?: string | number | boolean; onTcChange?: (e: CustomEvent) => void }>
    'tc-eyebrow': TcProps
    'tc-faq-list': TcProps<{ onTcToggle?: (e: CustomEvent) => void }>
    'tc-feature-card': TcProps<{ 'description'?: string | number | boolean; 'eyebrow'?: string | number | boolean; 'icon'?: string | number | boolean; 'inline'?: string | number | boolean; 'size'?: string | number | boolean; 'title'?: string | number | boolean }>
    'tc-feature-matrix': TcProps<{ 'title'?: string | number | boolean }>
    'tc-file': TcProps<{ onTcMenuItemClick?: (e: CustomEvent) => void; onTcNameChange?: (e: CustomEvent) => void }>
    'tc-file-dropzone': TcProps<{ onTcFiles?: (e: CustomEvent) => void }>
    'tc-file-tags': TcProps<{ 'readonly'?: string | number | boolean; onTcChange?: (e: CustomEvent) => void }>
    'tc-floating-label': TcProps<{ 'for'?: string | number | boolean; 'label'?: string | number | boolean }>
    'tc-form': TcProps<{ 'novalidate'?: string | number | boolean; 'validated'?: string | number | boolean }>
    'tc-form-input': TcProps<{ 'disabled'?: string | number | boolean; 'error'?: string | number | boolean; 'help'?: string | number | boolean; 'helper'?: string | number | boolean; 'id'?: string | number | boolean; 'label'?: string | number | boolean; 'loading'?: string | number | boolean; 'max'?: string | number | boolean; 'min'?: string | number | boolean; 'name'?: string | number | boolean; 'placeholder'?: string | number | boolean; 'required'?: string | number | boolean; 'rows'?: string | number | boolean; 'step'?: string | number | boolean; 'type'?: string | number | boolean; onTcChange?: (e: CustomEvent) => void }>
    'tc-form-wizard': TcProps<{ 'complete-icon'?: string | number | boolean; 'complete-label'?: string | number | boolean; 'loading'?: string | number | boolean; onTcStepChange?: (e: CustomEvent) => void; onTcComplete?: (e: CustomEvent) => void }>
    'tc-fov-slider': TcProps<{ 'disabled'?: string | number | boolean; 'format'?: string | number | boolean; 'max'?: string | number | boolean; 'min'?: string | number | boolean; 'muted'?: string | number | boolean; 'step'?: string | number | boolean; 'unit'?: string | number | boolean; 'value'?: string | number | boolean; 'with-mute'?: string | number | boolean }>
    'tc-fps-cap-select': TcProps<{ 'disabled'?: string | number | boolean; 'value'?: string | number | boolean; onTcChange?: (e: CustomEvent) => void }>
    'tc-fullscreen-toggle': TcProps<{ 'checked'?: string | number | boolean; 'disabled'?: string | number | boolean; onTcChange?: (e: CustomEvent) => void }>
    'tc-funnel-chart': TcProps<{ onTcSelect?: (e: CustomEvent) => void }>
    'tc-game-over-screen': TcProps<{ 'eyebrow'?: string | number | boolean; 'subtitle'?: string | number | boolean; 'title-color'?: string | number | boolean; 'title-text'?: string | number | boolean; 'variant'?: string | number | boolean }>
    'tc-game-showcase-card': TcProps<{ onTcClick?: (e: CustomEvent) => void }>
    'tc-gamepad-button-prompt': TcProps<{ 'glyph'?: string | number | boolean; 'label'?: string | number | boolean; 'size'?: string | number | boolean }>
    'tc-gantt-chart': TcProps<{ onTcTaskClick?: (e: CustomEvent) => void }>
    'tc-gilded-frame': TcProps<{ 'padding'?: string | number | boolean; 'tone'?: string | number | boolean }>
    'tc-github-stars-card': TcProps<{ 'cta-label'?: string | number | boolean; 'fetch-live'?: string | number | boolean; 'owner'?: string | number | boolean; 'repo'?: string | number | boolean; onTcStats?: (e: CustomEvent) => void; onTcCtaClick?: (e: CustomEvent) => void }>
    'tc-good-first-issues': TcProps<{ 'title'?: string | number | boolean; onTcIssueClick?: (e: CustomEvent) => void }>
    'tc-graphics-preset-picker': TcProps<{ 'disabled'?: string | number | boolean; 'value'?: string | number | boolean; onTcChange?: (e: CustomEvent) => void }>
    'tc-grid': TcProps<{ 'cell-size'?: string | number | boolean; 'columns'?: string | number | boolean; 'gap'?: string | number | boolean; 'rows'?: string | number | boolean }>
    'tc-group': TcProps<{ 'action-icon'?: string | number | boolean; 'action-label'?: string | number | boolean; 'badge'?: string | number | boolean; 'default-collapsed'?: string | number | boolean; 'label'?: string | number | boolean; onTcToggle?: (e: CustomEvent) => void; onTcActionClick?: (e: CustomEvent) => void }>
    'tc-guild-panel': TcProps<{ 'guild-name'?: string | number | boolean; 'level'?: string | number | boolean; 'member-cap'?: string | number | boolean; 'motto'?: string | number | boolean; 'tag'?: string | number | boolean }>
    'tc-heading': TcProps<{ 'as'?: string | number | boolean; 'gradient'?: string | number | boolean }>
    'tc-health-bar': TcProps<{ 'ghost'?: string | number | boolean; 'label'?: string | number | boolean; 'max'?: string | number | boolean; 'segments'?: string | number | boolean; 'show-text'?: string | number | boolean; 'value'?: string | number | boolean; 'variant'?: string | number | boolean }>
    'tc-heatmap': TcProps<{ 'cell-size'?: string | number | boolean; 'loading'?: string | number | boolean; 'subtitle'?: string | number | boolean; 'title'?: string | number | boolean; onTcCellHover?: (e: CustomEvent) => void }>
    'tc-helper-text': TcProps<{ 'class-name'?: string | number | boolean; 'icon'?: string | number | boolean; 'id'?: string | number | boolean; 'text'?: string | number | boolean; 'variant'?: string | number | boolean }>
    'tc-hero': TcProps<{ 'background-pattern-src'?: string | number | boolean; 'description'?: string | number | boolean; 'eyebrow'?: string | number | boolean; 'title'?: string | number | boolean; 'title-as'?: string | number | boolean; onTcAction?: (e: CustomEvent) => void }>
    'tc-hero-stats-bar': TcProps<{ 'class-name'?: string | number | boolean }>
    'tc-hit-marker': TcProps<{ 'crit'?: string | number | boolean; 'duration'?: string | number | boolean; 'kill'?: string | number | boolean; 'show'?: string | number | boolean; 'size'?: string | number | boolean; onTcDone?: (e: CustomEvent) => void }>
    'tc-hotbar': TcProps<{ 'selected-id'?: string | number | boolean; 'slot-size'?: string | number | boolean; onTcSelect?: (e: CustomEvent) => void }>
    'tc-icon': TcProps<{ 'as'?: string | number | boolean; 'color'?: string | number | boolean; 'decorative'?: string | number | boolean; 'label'?: string | number | boolean; 'name'?: string | number | boolean; 'set'?: string | number | boolean; 'size'?: string | number | boolean }>
    'tc-icon-badge': TcProps<{ 'bg'?: string | number | boolean; 'color'?: string | number | boolean; 'glyph'?: string | number | boolean; 'size'?: string | number | boolean }>
    'tc-icon-button': TcProps<{ 'disabled'?: string | number | boolean; 'icon'?: string | number | boolean; 'label'?: string | number | boolean; 'outline'?: string | number | boolean; 'size'?: string | number | boolean; 'variant'?: string | number | boolean; onTcClick?: (e: CustomEvent) => void }>
    'tc-icon-picker': TcProps<{ 'columns'?: string | number | boolean; 'label'?: string | number | boolean; 'loading'?: string | number | boolean; 'value'?: string | number | boolean; onTcChange?: (e: CustomEvent) => void }>
    'tc-image': TcProps<{ onTcLoad?: (e: CustomEvent) => void; onTcError?: (e: CustomEvent) => void }>
    'tc-image-crop': TcProps<{ 'aspect-ratio'?: string | number | boolean; 'circular'?: string | number | boolean; 'src'?: string | number | boolean; onTcCrop?: (e: CustomEvent) => void; onTcError?: (e: CustomEvent) => void }>
    'tc-infinite-scroll': TcProps<{ 'has-more'?: string | number | boolean; 'loading'?: string | number | boolean; 'root-margin'?: string | number | boolean; 'threshold'?: string | number | boolean; onTcLoadMore?: (e: CustomEvent) => void }>
    'tc-input': TcProps<{ 'type'?: string | number | boolean }>
    'tc-input-group': TcProps<{ 'size'?: string | number | boolean }>
    'tc-input-group-text': TcProps
    'tc-install-tabs': TcProps<{ 'default-manager'?: string | number | boolean; 'dev'?: string | number | boolean; 'global'?: string | number | boolean; 'package'?: string | number | boolean; onTcChange?: (e: CustomEvent) => void; onTcCopy?: (e: CustomEvent) => void }>
    'tc-interact-prompt': TcProps<{ 'hold-progress'?: string | number | boolean; 'key-label'?: string | number | boolean; 'show'?: string | number | boolean; 'text'?: string | number | boolean }>
    'tc-inventory-grid': TcProps<{ 'columns'?: string | number | boolean; 'selected-id'?: string | number | boolean; 'slot-size'?: string | number | boolean; onTcSelect?: (e: CustomEvent) => void }>
    'tc-invite-toast': TcProps<{ 'body'?: string | number | boolean; 'inviter'?: string | number | boolean; 'open'?: string | number | boolean; 'timeout-seconds'?: string | number | boolean; onTcAccept?: (e: CustomEvent) => void; onTcDecline?: (e: CustomEvent) => void }>
    'tc-item-compare': TcProps
    'tc-item-slot': TcProps<{ 'hotkey'?: string | number | boolean; 'selected'?: string | number | boolean; 'size'?: string | number | boolean; onTcClick?: (e: CustomEvent) => void }>
    'tc-item-tooltip': TcProps
    'tc-journal': TcProps<{ 'selected-id'?: string | number | boolean; onTcSelect?: (e: CustomEvent) => void }>
    'tc-json-editor': TcProps<{ 'disabled'?: string | number | boolean; 'loading'?: string | number | boolean; 'schema'?: string | number | boolean; onTcChange?: (e: CustomEvent) => void }>
    'tc-json-schema-def': TcProps<{ 'default-value'?: string | number | boolean; 'disabled'?: string | number | boolean; 'label'?: string | number | boolean; 'loading'?: string | number | boolean; 'value'?: string | number | boolean; onTcChange?: (e: CustomEvent) => void; onTcLabelChange?: (e: CustomEvent) => void }>
    'tc-kbd': TcProps<{ 'class-name'?: string | number | boolean; 'separator'?: string | number | boolean }>
    'tc-key': TcProps<{ 'size'?: string | number | boolean; 'variant'?: string | number | boolean }>
    'tc-key-binder': TcProps<{ 'disabled'?: string | number | boolean; 'placeholder'?: string | number | boolean; 'value'?: string | number | boolean; onTcCancel?: (e: CustomEvent) => void; onTcChange?: (e: CustomEvent) => void }>
    'tc-kill-feed': TcProps<{ 'max-visible'?: string | number | boolean }>
    'tc-label': TcProps<{ 'required'?: string | number | boolean; 'size'?: string | number | boolean; 'tooltip'?: string | number | boolean }>
    'tc-leaderboard': TcProps<{ onTcSelect?: (e: CustomEvent) => void }>
    'tc-leaderboard-trend': TcProps<{ 'direction'?: string | number | boolean; 'size'?: string | number | boolean; 'value'?: string | number | boolean }>
    'tc-legal-screen': TcProps<{ 'initial-section'?: string | number | boolean; 'screen-title'?: string | number | boolean; 'show-accept'?: string | number | boolean; onTcClose?: (e: CustomEvent) => void; onTcAccept?: (e: CustomEvent) => void }>
    'tc-letterbox-bars': TcProps<{ 'bar-color'?: string | number | boolean; 'bar-height'?: string | number | boolean; 'duration'?: string | number | boolean; 'show'?: string | number | boolean }>
    'tc-level-header': TcProps<{ 'level'?: string | number | boolean; 'next-label'?: string | number | boolean; 'title'?: string | number | boolean; 'xp'?: string | number | boolean; 'xp-max'?: string | number | boolean }>
    'tc-level-select': TcProps<{ 'height'?: string | number | boolean; 'selected-id'?: string | number | boolean; 'width'?: string | number | boolean; onTcSelect?: (e: CustomEvent) => void; onTcConfirm?: (e: CustomEvent) => void }>
    'tc-lightbox': TcProps<{ 'initial-index'?: string | number | boolean; 'open'?: string | number | boolean; onTcChange?: (e: CustomEvent) => void; onTcClose?: (e: CustomEvent) => void }>
    'tc-line-chart': TcProps<{ onTcPointHover?: (e: CustomEvent) => void }>
    'tc-link': TcProps<{ 'external'?: string | number | boolean; 'href'?: string | number | boolean; 'underline'?: string | number | boolean; 'variant'?: string | number | boolean }>
    'tc-linked-providers-card': TcProps<{ 'empty-label'?: string | number | boolean; 'title'?: string | number | boolean; onTcToggle?: (e: CustomEvent) => void }>
    'tc-list': TcProps<{ 'selected-id'?: string | number | boolean; onTcSelect?: (e: CustomEvent) => void }>
    'tc-list-card': TcProps<{ 'loading'?: string | number | boolean; 'loading-count'?: string | number | boolean; 'ordered'?: string | number | boolean; 'title'?: string | number | boolean }>
    'tc-list-group': TcProps<{ 'flush'?: string | number | boolean; 'horizontal'?: string | number | boolean; 'numbered'?: string | number | boolean }>
    'tc-list-group-item': TcProps<{ 'action'?: string | number | boolean; 'active'?: string | number | boolean; 'disabled'?: string | number | boolean; 'href'?: string | number | boolean; 'variant'?: string | number | boolean }>
    'tc-list-row': TcProps<{ 'accent'?: string | number | boolean; 'disabled'?: string | number | boolean; 'selected'?: string | number | boolean; onTcSelect?: (e: CustomEvent) => void }>
    'tc-live-feed': TcProps<{ 'auto-scroll'?: string | number | boolean; 'header'?: string | number | boolean; 'max-rows'?: string | number | boolean; 'recording'?: string | number | boolean; onTcRowClick?: (e: CustomEvent) => void }>
    'tc-loading-overlay': TcProps<{ 'label'?: string | number | boolean; 'open'?: string | number | boolean; 'progress'?: string | number | boolean; 'tip'?: string | number | boolean }>
    'tc-loading-screen': TcProps<{ 'eyebrow'?: string | number | boolean; 'label'?: string | number | boolean; 'progress'?: string | number | boolean; 'tip-interval'?: string | number | boolean; 'tip-title'?: string | number | boolean; 'title-text'?: string | number | boolean }>
    'tc-lobby': TcProps<{ 'can-start'?: string | number | boolean; 'capacity'?: string | number | boolean; 'is-ready'?: string | number | boolean; 'lobby-mode'?: string | number | boolean; 'map-name'?: string | number | boolean }>
    'tc-login': TcProps<{ 'background-pattern-src'?: string | number | boolean; 'description'?: string | number | boolean; 'loading'?: string | number | boolean; 'title'?: string | number | boolean; onTcConnect?: (e: CustomEvent) => void }>
    'tc-logo-cloud': TcProps<{ 'columns'?: string | number | boolean; 'grayscale'?: string | number | boolean; 'title'?: string | number | boolean }>
    'tc-loot-list': TcProps<{ 'list-title'?: string | number | boolean; onTcTake?: (e: CustomEvent) => void; onTcTakeAll?: (e: CustomEvent) => void }>
    'tc-loot-popup': TcProps<{ 'auto-fade-ms'?: string | number | boolean; 'discard-label'?: string | number | boolean; 'eyebrow'?: string | number | boolean; 'open'?: string | number | boolean; 'popup-title'?: string | number | boolean; onTcClose?: (e: CustomEvent) => void; onTcTake?: (e: CustomEvent) => void; onTcTakeAll?: (e: CustomEvent) => void; onTcDiscard?: (e: CustomEvent) => void }>
    'tc-lore-text': TcProps
    'tc-main-menu': TcProps<{ 'menu-title'?: string | number | boolean; 'selected-id'?: string | number | boolean; 'subtitle'?: string | number | boolean; onTcSelect?: (e: CustomEvent) => void }>
    'tc-maintainer-card': TcProps<{ 'avatar-url'?: string | number | boolean; 'bio'?: string | number | boolean; 'location'?: string | number | boolean; 'name'?: string | number | boolean; 'role'?: string | number | boolean; 'sponsor-href'?: string | number | boolean; 'sponsor-label'?: string | number | boolean }>
    'tc-mana-bar': TcProps<{ 'ghost'?: string | number | boolean; 'label'?: string | number | boolean; 'max'?: string | number | boolean; 'segments'?: string | number | boolean; 'show-text'?: string | number | boolean; 'value'?: string | number | boolean; 'variant'?: string | number | boolean }>
    'tc-markdown-editor': TcProps<{ 'disabled'?: string | number | boolean; 'height'?: string | number | boolean; 'label'?: string | number | boolean; 'placeholder'?: string | number | boolean; 'toolbar'?: string | number | boolean; 'value'?: string | number | boolean }>
    'tc-marquee': TcProps<{ 'direction'?: string | number | boolean; 'pause-on-hover'?: string | number | boolean; 'separator'?: string | number | boolean; 'speed'?: string | number | boolean }>
    'tc-matchmaking-screen': TcProps<{ 'elapsed'?: string | number | boolean; 'estimated'?: string | number | boolean; 'found-label'?: string | number | boolean; 'mode'?: string | number | boolean; 'region'?: string | number | boolean; 'state'?: string | number | boolean }>
    'tc-menu-item': TcProps<{ 'disabled'?: string | number | boolean; 'hotkey'?: string | number | boolean; 'icon'?: string | number | boolean; 'label'?: string | number | boolean; 'selected'?: string | number | boolean; onTcSelect?: (e: CustomEvent) => void }>
    'tc-metal-button': TcProps<{ 'disabled'?: string | number | boolean; 'href'?: string | number | boolean; 'loading'?: string | number | boolean; 'outline'?: string | number | boolean; 'size'?: string | number | boolean; 'skin'?: string | number | boolean; 'type'?: string | number | boolean; 'variant'?: string | number | boolean }>
    'tc-metric-card': TcProps
    'tc-metric-grid': TcProps<{ 'columns'?: string | number | boolean }>
    'tc-metric-tile': TcProps<{ 'hint'?: string | number | boolean; 'icon'?: string | number | boolean; 'label'?: string | number | boolean; 'unit'?: string | number | boolean; 'value'?: string | number | boolean }>
    'tc-migration-guide': TcProps<{ 'from'?: string | number | boolean; 'title'?: string | number | boolean; 'to'?: string | number | boolean }>
    'tc-minimap': TcProps<{ 'background-image'?: string | number | boolean; 'rotation'?: string | number | boolean; 'size'?: string | number | boolean; 'world-height'?: string | number | boolean; 'world-width'?: string | number | boolean; 'world-x'?: string | number | boolean; 'world-y'?: string | number | boolean }>
    'tc-modal': TcProps<{ 'centered'?: string | number | boolean; 'fullscreen'?: string | number | boolean; 'open'?: string | number | boolean; 'scrollable'?: string | number | boolean; 'size'?: string | number | boolean; 'static-backdrop'?: string | number | boolean; 'title'?: string | number | boolean; onTcShow?: (e: CustomEvent) => void; onTcShown?: (e: CustomEvent) => void; onTcHide?: (e: CustomEvent) => void; onTcHidden?: (e: CustomEvent) => void }>
    'tc-mouse-sensitivity': TcProps<{ 'ads'?: string | number | boolean; 'disabled'?: string | number | boolean; 'value'?: string | number | boolean; onTcChange?: (e: CustomEvent) => void }>
    'tc-multi-card-select': TcProps<{ 'columns'?: string | number | boolean; 'loading'?: string | number | boolean; 'loading-count'?: string | number | boolean; 'name'?: string | number | boolean; onTcChange?: (e: CustomEvent) => void }>
    'tc-nav': TcProps<{ 'fill'?: string | number | boolean; 'justified'?: string | number | boolean; 'variant'?: string | number | boolean; 'vertical'?: string | number | boolean }>
    'tc-nav-button': TcProps<{ 'disabled'?: string | number | boolean; 'kind'?: string | number | boolean; 'label'?: string | number | boolean; 'size'?: string | number | boolean }>
    'tc-nav-item': TcProps<{ 'active'?: string | number | boolean; 'disabled'?: string | number | boolean; 'href'?: string | number | boolean; 'target'?: string | number | boolean; onTcShow?: (e: CustomEvent) => void; onTcShown?: (e: CustomEvent) => void }>
    'tc-navbar': TcProps<{ 'bg'?: string | number | boolean; 'brand'?: string | number | boolean; 'expand'?: string | number | boolean; 'fixed'?: string | number | boolean; 'sticky'?: string | number | boolean; 'variant'?: string | number | boolean }>
    'tc-network-status-icon': TcProps<{ 'connected'?: string | number | boolean; 'loss'?: string | number | boolean; 'ping'?: string | number | boolean; 'show-label'?: string | number | boolean; 'size'?: string | number | boolean }>
    'tc-newsletter-signup': TcProps<{ 'cta-label'?: string | number | boolean; 'description'?: string | number | boolean; 'placeholder'?: string | number | boolean; 'privacy-href'?: string | number | boolean; 'success-message'?: string | number | boolean; 'title'?: string | number | boolean; onTcSubmit?: (e: CustomEvent) => void }>
    'tc-node-editor': TcProps<{ 'disabled'?: string | number | boolean; 'selected-id'?: string | number | boolean; onTcSelect?: (e: CustomEvent) => void; onTcMoveNode?: (e: CustomEvent) => void; onTcConnect?: (e: CustomEvent) => void }>
    'tc-normal-map-generator': TcProps<{ 'bevel-width'?: string | number | boolean; 'disabled'?: string | number | boolean; 'editable'?: string | number | boolean; 'emboss-height'?: string | number | boolean; 'preview-mode'?: string | number | boolean; 'source'?: string | number | boolean; 'strength'?: string | number | boolean; 'tool'?: string | number | boolean }>
    'tc-number-input': TcProps<{ 'error'?: string | number | boolean; 'label'?: string | number | boolean; 'max'?: string | number | boolean; 'min'?: string | number | boolean; 'precision'?: string | number | boolean; 'prefix'?: string | number | boolean; 'step'?: string | number | boolean; 'suffix'?: string | number | boolean; 'value'?: string | number | boolean; onTcChange?: (e: CustomEvent) => void }>
    'tc-objective-marker': TcProps<{ 'color'?: string | number | boolean; 'distance'?: string | number | boolean; 'label'?: string | number | boolean; 'pulse'?: string | number | boolean; 'size'?: string | number | boolean; 'x'?: string | number | boolean; 'y'?: string | number | boolean }>
    'tc-offcanvas': TcProps<{ 'backdrop'?: string | number | boolean; 'open'?: string | number | boolean; 'placement'?: string | number | boolean; 'scroll'?: string | number | boolean; 'title'?: string | number | boolean; onTcShow?: (e: CustomEvent) => void; onTcShown?: (e: CustomEvent) => void; onTcHide?: (e: CustomEvent) => void; onTcHidden?: (e: CustomEvent) => void }>
    'tc-option': TcProps<{ 'disabled'?: string | number | boolean; 'selected'?: string | number | boolean; 'value'?: string | number | boolean }>
    'tc-otp-input': TcProps<{ 'error'?: string | number | boolean; 'label'?: string | number | boolean; 'length'?: string | number | boolean; 'masked'?: string | number | boolean; 'mode'?: string | number | boolean; 'name'?: string | number | boolean; 'value'?: string | number | boolean; onTcChange?: (e: CustomEvent) => void; onTcComplete?: (e: CustomEvent) => void }>
    'tc-page-footer': TcProps<{ 'brand'?: string | number | boolean; 'description'?: string | number | boolean; 'legal-text'?: string | number | boolean; 'tagline'?: string | number | boolean }>
    'tc-page-indicator': TcProps<{ 'active-color'?: string | number | boolean; 'color'?: string | number | boolean; 'count'?: string | number | boolean; 'gap'?: string | number | boolean; 'index'?: string | number | boolean; 'size'?: string | number | boolean; onTcSelect?: (e: CustomEvent) => void }>
    'tc-pagination': TcProps<{ 'align'?: string | number | boolean; 'current'?: string | number | boolean; 'max-visible'?: string | number | boolean; 'size'?: string | number | boolean; 'total'?: string | number | boolean; onTcPageChange?: (e: CustomEvent) => void }>
    'tc-panel': TcProps<{ 'bordered'?: string | number | boolean }>
    'tc-panel-header': TcProps<{ 'heading'?: string | number | boolean; 'icon'?: string | number | boolean }>
    'tc-particle-emitter': TcProps<{ 'burst'?: string | number | boolean; 'count'?: string | number | boolean; 'gravity'?: string | number | boolean; 'height'?: string | number | boolean; 'lifetime'?: string | number | boolean; 'particle-size'?: string | number | boolean; 'speed'?: string | number | boolean; 'width'?: string | number | boolean; onTcBurst?: (e: CustomEvent) => void }>
    'tc-party-panel': TcProps<{ 'capacity'?: string | number | boolean }>
    'tc-pause-menu': TcProps<{ 'default-items'?: string | number | boolean; 'menu-title'?: string | number | boolean; 'open'?: string | number | boolean; 'resume-footer'?: string | number | boolean; 'screen-title'?: string | number | boolean; onTcResume?: (e: CustomEvent) => void; onTcSelect?: (e: CustomEvent) => void; onTcRestart?: (e: CustomEvent) => void; onTcQuit?: (e: CustomEvent) => void; onTcClose?: (e: CustomEvent) => void }>
    'tc-pause-screen': TcProps<{ 'default-items'?: string | number | boolean; 'menu-title'?: string | number | boolean; 'open'?: string | number | boolean; 'resume-footer'?: string | number | boolean; 'screen-title'?: string | number | boolean }>
    'tc-perk-picker': TcProps<{ 'columns'?: string | number | boolean; onTcSelect?: (e: CustomEvent) => void }>
    'tc-phase-grid': TcProps<{ 'columns'?: string | number | boolean }>
    'tc-phone-input': TcProps<{ 'default-country'?: string | number | boolean; 'error'?: string | number | boolean; 'label'?: string | number | boolean; 'name'?: string | number | boolean; 'placeholder'?: string | number | boolean; 'value'?: string | number | boolean; onTcChange?: (e: CustomEvent) => void }>
    'tc-physics-editor': TcProps<{ 'alpha-threshold'?: string | number | boolean; 'disabled'?: string | number | boolean; 'source'?: string | number | boolean; 'tool'?: string | number | boolean; onTcChange?: (e: CustomEvent) => void }>
    'tc-pie-chart': TcProps<{ onTcSliceSelect?: (e: CustomEvent) => void }>
    'tc-ping-display': TcProps<{ 'ping'?: string | number | boolean }>
    'tc-pinned-feature-showcase': TcProps<{ 'description'?: string | number | boolean; 'eyebrow'?: string | number | boolean; 'image-alt'?: string | number | boolean; 'image-src'?: string | number | boolean; 'title'?: string | number | boolean }>
    'tc-pipeline': TcProps
    'tc-placeholder': TcProps<{ 'animation'?: string | number | boolean; 'size'?: string | number | boolean; 'variant'?: string | number | boolean; 'width'?: string | number | boolean }>
    'tc-platform-icon': TcProps<{ 'label'?: string | number | boolean; 'platform'?: string | number | boolean; 'size'?: string | number | boolean }>
    'tc-player-card': TcProps<{ 'card-title'?: string | number | boolean; 'level'?: string | number | boolean; 'online-status'?: string | number | boolean; 'player-name'?: string | number | boolean; 'rank'?: string | number | boolean; onTcAction?: (e: CustomEvent) => void }>
    'tc-player-frame': TcProps<{ 'class-name'?: string | number | boolean; 'glyph'?: string | number | boolean; 'hp'?: string | number | boolean; 'hp-max'?: string | number | boolean; 'level'?: string | number | boolean; 'mp'?: string | number | boolean; 'mp-max'?: string | number | boolean; 'name'?: string | number | boolean; 'show-mp'?: string | number | boolean; 'show-stamina'?: string | number | boolean; 'stamina'?: string | number | boolean; 'stamina-max'?: string | number | boolean }>
    'tc-plugin-grid': TcProps<{ 'columns'?: string | number | boolean; 'title-text'?: string | number | boolean; onTcCopy?: (e: CustomEvent) => void }>
    'tc-popover': TcProps<{ onTcShow?: (e: CustomEvent) => void; onTcShown?: (e: CustomEvent) => void; onTcHide?: (e: CustomEvent) => void; onTcHidden?: (e: CustomEvent) => void }>
    'tc-portrait': TcProps<{ 'circle'?: string | number | boolean; 'glyph'?: string | number | boolean; 'level'?: string | number | boolean; 'ring'?: string | number | boolean; 'size'?: string | number | boolean }>
    'tc-press-any-key': TcProps<{ 'disabled'?: string | number | boolean; 'text'?: string | number | boolean }>
    'tc-pricing-card': TcProps<{ 'badge-text'?: string | number | boolean; 'description'?: string | number | boolean; 'highlight'?: string | number | boolean; 'name'?: string | number | boolean; 'period'?: string | number | boolean; 'price'?: string | number | boolean; onTcAction?: (e: CustomEvent) => void }>
    'tc-progress': TcProps<{ 'animated'?: string | number | boolean; 'label'?: string | number | boolean; 'max'?: string | number | boolean; 'min'?: string | number | boolean; 'striped'?: string | number | boolean; 'value'?: string | number | boolean; 'variant'?: string | number | boolean }>
    'tc-progress-bar': TcProps<{ 'animated'?: string | number | boolean; 'label'?: string | number | boolean; 'striped'?: string | number | boolean; 'value'?: string | number | boolean; 'variant'?: string | number | boolean }>
    'tc-pulse-indicator': TcProps<{ 'color'?: string | number | boolean; 'label'?: string | number | boolean; 'paused'?: string | number | boolean }>
    'tc-quest-tracker': TcProps<{ 'tracker-title'?: string | number | boolean }>
    'tc-queued-file': TcProps<{ 'extension'?: string | number | boolean; 'format'?: string | number | boolean; 'name'?: string | number | boolean; 'size'?: string | number | boolean; onTcDismiss?: (e: CustomEvent) => void }>
    'tc-quick-start': TcProps<{ 'title-text'?: string | number | boolean; onTcCopy?: (e: CustomEvent) => void }>
    'tc-radial-wheel': TcProps<{ 'center-label'?: string | number | boolean; 'open'?: string | number | boolean; 'option-size'?: string | number | boolean; 'per-page'?: string | number | boolean; 'radius'?: string | number | boolean; onTcClose?: (e: CustomEvent) => void; onTcSelect?: (e: CustomEvent) => void }>
    'tc-radio': TcProps<{ 'checked'?: string | number | boolean; 'disabled'?: string | number | boolean; 'inline'?: string | number | boolean; 'label'?: string | number | boolean; 'name'?: string | number | boolean; 'reverse'?: string | number | boolean; 'value'?: string | number | boolean }>
    'tc-radio-group': TcProps<{ 'inline'?: string | number | boolean; 'label'?: string | number | boolean; 'name'?: string | number | boolean; 'value'?: string | number | boolean; onTcChange?: (e: CustomEvent) => void }>
    'tc-range': TcProps<{ 'disabled'?: string | number | boolean; 'label'?: string | number | boolean; 'max'?: string | number | boolean; 'min'?: string | number | boolean; 'step'?: string | number | boolean; 'value'?: string | number | boolean }>
    'tc-range-slider': TcProps<{ 'disabled'?: string | number | boolean; 'label'?: string | number | boolean; 'max'?: string | number | boolean; 'min'?: string | number | boolean; 'show-tooltip'?: string | number | boolean; 'step'?: string | number | boolean; 'ticks'?: string | number | boolean; onTcChange?: (e: CustomEvent) => void }>
    'tc-rank-cell': TcProps<{ 'pad'?: string | number | boolean; 'rank'?: string | number | boolean }>
    'tc-rarity-chip': TcProps<{ 'rarity'?: string | number | boolean }>
    'tc-rating': TcProps<{ 'allow-half'?: string | number | boolean; 'count'?: string | number | boolean; 'icon'?: string | number | boolean; 'read-only'?: string | number | boolean; 'size'?: string | number | boolean; 'value'?: string | number | boolean; onTcChange?: (e: CustomEvent) => void }>
    'tc-report-dialog': TcProps<{ 'open'?: string | number | boolean; 'player-name'?: string | number | boolean; onTcCancel?: (e: CustomEvent) => void; onTcSubmit?: (e: CustomEvent) => void }>
    'tc-reset-to-defaults': TcProps<{ 'disabled'?: string | number | boolean; onTcReset?: (e: CustomEvent) => void }>
    'tc-resizable-panel': TcProps<{ 'direction'?: string | number | boolean; 'min-size'?: string | number | boolean; 'storage-key'?: string | number | boolean; onTcResize?: (e: CustomEvent) => void }>
    'tc-resource-bar': TcProps<{ 'ghost'?: string | number | boolean; 'label'?: string | number | boolean; 'max'?: string | number | boolean; 'segments'?: string | number | boolean; 'show-text'?: string | number | boolean; 'value'?: string | number | boolean; 'variant'?: string | number | boolean }>
    'tc-result-screen': TcProps<{ 'eyebrow'?: string | number | boolean; 'subtitle'?: string | number | boolean; 'title-color'?: string | number | boolean; 'title-text'?: string | number | boolean; 'variant'?: string | number | boolean; onTcAction?: (e: CustomEvent) => void }>
    'tc-rich-page-header': TcProps<{ 'description'?: string | number | boolean; 'icon-color'?: string | number | boolean; 'icon-name'?: string | number | boolean; 'sub'?: string | number | boolean; 'title-text'?: string | number | boolean }>
    'tc-roadmap': TcProps<{ 'layout'?: string | number | boolean; 'title-text'?: string | number | boolean; onTcSelect?: (e: CustomEvent) => void }>
    'tc-row': TcProps<{ 'align'?: string | number | boolean; 'cols'?: string | number | boolean; 'cols-lg'?: string | number | boolean; 'cols-md'?: string | number | boolean; 'cols-sm'?: string | number | boolean; 'cols-xl'?: string | number | boolean; 'cols-xxl'?: string | number | boolean; 'g'?: string | number | boolean; 'gutter'?: string | number | boolean; 'justify'?: string | number | boolean }>
    'tc-rune-corner': TcProps<{ 'at'?: string | number | boolean; 'size'?: string | number | boolean }>
    'tc-safe-area': TcProps<{ 'extra'?: string | number | boolean }>
    'tc-score-display': TcProps<{ 'align'?: string | number | boolean; 'font-size'?: string | number | boolean; 'label'?: string | number | boolean; 'multiplier'?: string | number | boolean; 'score'?: string | number | boolean }>
    'tc-scoring-rules': TcProps
    'tc-screen-flash': TcProps<{ 'duration'?: string | number | boolean; 'flash-color'?: string | number | boolean; 'flash-opacity'?: string | number | boolean; 'trigger'?: string | number | boolean; onTcDone?: (e: CustomEvent) => void }>
    'tc-scroll-area': TcProps<{ 'axis'?: string | number | boolean; 'max-height'?: string | number | boolean; 'max-width'?: string | number | boolean }>
    'tc-scroll-text': TcProps<{ 'max-height'?: string | number | boolean; 'scroll-title'?: string | number | boolean }>
    'tc-scrollspy': TcProps<{ 'offset'?: string | number | boolean; 'smooth-scroll'?: string | number | boolean; 'target'?: string | number | boolean; onTcActivate?: (e: CustomEvent) => void }>
    'tc-section-card': TcProps<{ 'icon'?: string | number | boolean; 'title'?: string | number | boolean; 'variant'?: string | number | boolean }>
    'tc-section-flag': TcProps<{ 'align'?: string | number | boolean; 'subtitle'?: string | number | boolean; 'title'?: string | number | boolean }>
    'tc-select': TcProps<{ 'disabled'?: string | number | boolean; 'label'?: string | number | boolean; 'multiple'?: string | number | boolean; 'size'?: string | number | boolean; 'state'?: string | number | boolean; 'value'?: string | number | boolean }>
    'tc-select-row': TcProps<{ 'disabled'?: string | number | boolean; 'value'?: string | number | boolean; onTcChange?: (e: CustomEvent) => void }>
    'tc-setting-slider': TcProps<{ 'disabled'?: string | number | boolean; 'format'?: string | number | boolean; 'max'?: string | number | boolean; 'min'?: string | number | boolean; 'muted'?: string | number | boolean; 'step'?: string | number | boolean; 'unit'?: string | number | boolean; 'value'?: string | number | boolean; 'with-mute'?: string | number | boolean; onTcChange?: (e: CustomEvent) => void; onTcToggleMute?: (e: CustomEvent) => void }>
    'tc-settings-category-list': TcProps<{ 'selected-id'?: string | number | boolean; onTcSelect?: (e: CustomEvent) => void }>
    'tc-shake-container': TcProps<{ 'duration'?: string | number | boolean; 'intensity'?: string | number | boolean; 'trigger'?: string | number | boolean }>
    'tc-shop-panel': TcProps<{ 'currency'?: string | number | boolean; 'currency-icon'?: string | number | boolean; 'sell-mode'?: string | number | boolean }>
    'tc-side-nav': TcProps<{ 'loading'?: string | number | boolean; 'loading-count'?: string | number | boolean; onTcItemClick?: (e: CustomEvent) => void }>
    'tc-simple-file': TcProps<{ 'extension'?: string | number | boolean; 'format'?: string | number | boolean; 'name'?: string | number | boolean }>
    'tc-single-card-select': TcProps<{ 'columns'?: string | number | boolean; 'loading'?: string | number | boolean; 'loading-count'?: string | number | boolean; 'name'?: string | number | boolean; 'value'?: string | number | boolean; onTcChange?: (e: CustomEvent) => void }>
    'tc-skeleton': TcProps<{ 'count'?: string | number | boolean; 'height'?: string | number | boolean; 'variant'?: string | number | boolean; 'width'?: string | number | boolean }>
    'tc-skill-bar': TcProps<{ 'gap'?: string | number | boolean; 'slot-size'?: string | number | boolean; onTcActivate?: (e: CustomEvent) => void }>
    'tc-skill-tree': TcProps<{ 'height'?: string | number | boolean; 'points'?: string | number | boolean; 'selected-id'?: string | number | boolean; 'width'?: string | number | boolean; onTcSelect?: (e: CustomEvent) => void; onTcUnlock?: (e: CustomEvent) => void }>
    'tc-slices-card': TcProps
    'tc-slider': TcProps<{ 'disabled'?: string | number | boolean; 'error'?: string | number | boolean; 'label'?: string | number | boolean; 'max'?: string | number | boolean; 'min'?: string | number | boolean; 'show-tooltip'?: string | number | boolean; 'step'?: string | number | boolean; 'ticks'?: string | number | boolean; 'value'?: string | number | boolean; onTcChange?: (e: CustomEvent) => void }>
    'tc-social-links': TcProps<{ 'size'?: string | number | boolean; 'variant'?: string | number | boolean }>
    'tc-spacer': TcProps<{ 'axis'?: string | number | boolean; 'size'?: string | number | boolean }>
    'tc-sparkline': TcProps<{ 'color'?: string | number | boolean; 'data'?: string | number | boolean; 'height'?: string | number | boolean; 'type'?: string | number | boolean; 'width'?: string | number | boolean }>
    'tc-spinner': TcProps<{ 'label'?: string | number | boolean; 'size'?: string | number | boolean; 'type'?: string | number | boolean; 'variant'?: string | number | boolean }>
    'tc-sponsor-wall': TcProps<{ 'title'?: string | number | boolean }>
    'tc-sprint-chain': TcProps<{ 'columns'?: string | number | boolean; 'current-id'?: string | number | boolean }>
    'tc-stack': TcProps<{ 'align'?: string | number | boolean; 'direction'?: string | number | boolean; 'gap'?: string | number | boolean; 'inline'?: string | number | boolean; 'justify'?: string | number | boolean; 'wrap'?: string | number | boolean }>
    'tc-stamina-bar': TcProps<{ 'ghost'?: string | number | boolean; 'label'?: string | number | boolean; 'max'?: string | number | boolean; 'segments'?: string | number | boolean; 'show-text'?: string | number | boolean; 'value'?: string | number | boolean; 'variant'?: string | number | boolean }>
    'tc-stamp': TcProps<{ 'angle'?: string | number | boolean; 'color'?: string | number | boolean; 'label'?: string | number | boolean; 'position'?: string | number | boolean }>
    'tc-stat-card': TcProps<{ 'delta'?: string | number | boolean; 'delta-kind'?: string | number | boolean; 'footer'?: string | number | boolean; 'helper'?: string | number | boolean; 'icon'?: string | number | boolean; 'label'?: string | number | boolean; 'loading'?: string | number | boolean; 'unit'?: string | number | boolean; 'value'?: string | number | boolean }>
    'tc-stat-row': TcProps<{ 'accent'?: string | number | boolean; 'label'?: string | number | boolean; 'trend'?: string | number | boolean; 'value'?: string | number | boolean }>
    'tc-state-machine': TcProps<{ 'compact'?: string | number | boolean }>
    'tc-stats-screen': TcProps<{ 'screen-title'?: string | number | boolean; 'summary'?: string | number | boolean }>
    'tc-status-card': TcProps<{ 'loading'?: string | number | boolean; 'loading-count'?: string | number | boolean; 'title'?: string | number | boolean }>
    'tc-status-dot': TcProps<{ 'label'?: string | number | boolean; 'pulse'?: string | number | boolean; 'size'?: string | number | boolean; 'status'?: string | number | boolean }>
    'tc-stepper': TcProps<{ 'active-step'?: string | number | boolean; 'clickable'?: string | number | boolean; 'orientation'?: string | number | boolean; onTcStepClick?: (e: CustomEvent) => void }>
    'tc-subtitle': TcProps<{ 'align'?: string | number | boolean; 'boxed'?: string | number | boolean; 'font-size'?: string | number | boolean; 'max-width'?: string | number | boolean; 'speaker'?: string | number | boolean; 'text'?: string | number | boolean }>
    'tc-switch': TcProps<{ 'checked'?: string | number | boolean; 'disabled'?: string | number | boolean; 'label'?: string | number | boolean; 'reverse'?: string | number | boolean; 'value'?: string | number | boolean; onTcChange?: (e: CustomEvent) => void }>
    'tc-tab-bar': TcProps<{ 'active-id'?: string | number | boolean; 'size'?: string | number | boolean; onTcChange?: (e: CustomEvent) => void }>
    'tc-tab-sections': TcProps<{ 'active-key'?: string | number | boolean; 'default-active-key'?: string | number | boolean; 'loading'?: string | number | boolean; onTcChange?: (e: CustomEvent) => void }>
    'tc-table': TcProps<{ 'borderless'?: string | number | boolean; 'compact'?: string | number | boolean; 'empty-message'?: string | number | boolean; 'hoverable'?: string | number | boolean; 'loading'?: string | number | boolean; 'loading-rows'?: string | number | boolean; 'sticky-header'?: string | number | boolean; 'striped'?: string | number | boolean; onTcRowClick?: (e: CustomEvent) => void }>
    'tc-tag': TcProps<{ 'count'?: string | number | boolean; 'disabled'?: string | number | boolean; 'icon'?: string | number | boolean; 'removable'?: string | number | boolean; 'selected'?: string | number | boolean; 'static'?: string | number | boolean; 'variant'?: string | number | boolean }>
    'tc-tag-input': TcProps<{ 'allow-create'?: string | number | boolean; 'disabled'?: string | number | boolean; 'label'?: string | number | boolean; 'loading'?: string | number | boolean; 'max-tags'?: string | number | boolean; 'placeholder'?: string | number | boolean; onTcChange?: (e: CustomEvent) => void }>
    'tc-terminal-window': TcProps<{ 'animate-typing'?: string | number | boolean; 'prompt'?: string | number | boolean; 'speed'?: string | number | boolean; 'title'?: string | number | boolean }>
    'tc-testimonial-carousel': TcProps<{ 'autoplay'?: string | number | boolean; 'interval'?: string | number | boolean; onTcChange?: (e: CustomEvent) => void }>
    'tc-text': TcProps<{ 'as'?: string | number | boolean; 'size'?: string | number | boolean; 'variant'?: string | number | boolean }>
    'tc-textarea': TcProps<{ 'rows'?: string | number | boolean }>
    'tc-theme': TcProps<{ 'name'?: string | number | boolean }>
    'tc-tier-ladder': TcProps<{ 'current-tier-id'?: string | number | boolean; 'summary'?: string | number | boolean; 'title'?: string | number | boolean }>
    'tc-time-picker': TcProps<{ 'clearable'?: string | number | boolean; 'disabled'?: string | number | boolean; 'error'?: string | number | boolean; 'format'?: string | number | boolean; 'label'?: string | number | boolean; 'minute-step'?: string | number | boolean; 'placeholder'?: string | number | boolean; 'show-seconds'?: string | number | boolean; 'value'?: string | number | boolean; onTcChange?: (e: CustomEvent) => void }>
    'tc-timeline': TcProps<{ 'connector'?: string | number | boolean; 'loading'?: string | number | boolean; 'loading-count'?: string | number | boolean; 'overlap'?: string | number | boolean; 'variant'?: string | number | boolean }>
    'tc-title': TcProps<{ 'align'?: string | number | boolean; 'size'?: string | number | boolean }>
    'tc-title-screen': TcProps<{ 'eyebrow'?: string | number | boolean; 'subtitle'?: string | number | boolean; 'title-text'?: string | number | boolean }>
    'tc-toast': TcProps<{ 'autohide'?: string | number | boolean; 'delay'?: string | number | boolean; 'open'?: string | number | boolean; 'title'?: string | number | boolean; 'variant'?: string | number | boolean; onTcShow?: (e: CustomEvent) => void; onTcShown?: (e: CustomEvent) => void; onTcHide?: (e: CustomEvent) => void; onTcHidden?: (e: CustomEvent) => void }>
    'tc-toggle': TcProps<{ 'disabled'?: string | number | boolean; 'label'?: string | number | boolean; 'on'?: string | number | boolean; onTcChange?: (e: CustomEvent) => void }>
    'tc-toggle-card': TcProps<{ 'badge'?: string | number | boolean; 'checked'?: string | number | boolean; 'disabled'?: string | number | boolean; 'hint'?: string | number | boolean; 'icon'?: string | number | boolean; 'label'?: string | number | boolean; 'loading'?: string | number | boolean; 'name'?: string | number | boolean; 'value'?: string | number | boolean; onTcChange?: (e: CustomEvent) => void }>
    'tc-toggle-row': TcProps<{ 'checked'?: string | number | boolean; 'disabled'?: string | number | boolean; onTcChange?: (e: CustomEvent) => void }>
    'tc-tooltip': TcProps<{ onTcShow?: (e: CustomEvent) => void; onTcShown?: (e: CustomEvent) => void; onTcHide?: (e: CustomEvent) => void; onTcHidden?: (e: CustomEvent) => void }>
    'tc-transition-wipe': TcProps<{ 'direction'?: string | number | boolean; 'duration'?: string | number | boolean; 'show'?: string | number | boolean; 'wipe-color'?: string | number | boolean; onTcComplete?: (e: CustomEvent) => void }>
    'tc-tree-view': TcProps<{ 'checkbox-mode'?: string | number | boolean; onTcExpandChange?: (e: CustomEvent) => void; onTcSelect?: (e: CustomEvent) => void }>
    'tc-trend-indicator': TcProps<{ 'direction'?: string | number | boolean; 'size'?: string | number | boolean; 'value'?: string | number | boolean }>
    'tc-usage-summary-panel': TcProps<{ 'loading'?: string | number | boolean; 'loading-count'?: string | number | boolean; 'title'?: string | number | boolean }>
    'tc-user-panel': TcProps<{ 'avatar-src'?: string | number | boolean; 'icon'?: string | number | boolean; 'icon-highlighted'?: string | number | boolean; 'initials'?: string | number | boolean; 'loading'?: string | number | boolean; 'plan'?: string | number | boolean; 'username'?: string | number | boolean; onTcMenuClick?: (e: CustomEvent) => void; onTcIconClick?: (e: CustomEvent) => void }>
    'tc-version-label': TcProps<{ 'branch'?: string | number | boolean; 'build'?: string | number | boolean; 'version'?: string | number | boolean }>
    'tc-version-picker': TcProps<{ 'name'?: string | number | boolean; 'value'?: string | number | boolean; 'variant'?: string | number | boolean; onTcChange?: (e: CustomEvent) => void }>
    'tc-vertical-item-list': TcProps<{ 'active-key'?: string | number | boolean; 'default-active-key'?: string | number | boolean; 'disabled'?: string | number | boolean; 'loading'?: string | number | boolean; 'loading-count'?: string | number | boolean; onTcSelect?: (e: CustomEvent) => void }>
    'tc-victory-screen': TcProps<{ 'eyebrow'?: string | number | boolean; 'subtitle'?: string | number | boolean; 'title-color'?: string | number | boolean; 'title-text'?: string | number | boolean; 'variant'?: string | number | boolean }>
    'tc-video-embed': TcProps
    'tc-vignette-overlay': TcProps<{ 'intensity'?: string | number | boolean; 'vignette-color'?: string | number | boolean }>
    'tc-virtual-list': TcProps<{ 'end-reached-threshold'?: string | number | boolean; 'height'?: string | number | boolean; 'overscan'?: string | number | boolean; onTcEndReached?: (e: CustomEvent) => void }>
    'tc-visually-hidden': TcProps<{ 'as'?: string | number | boolean }>
    'tc-volume-slider': TcProps<{ 'disabled'?: string | number | boolean; 'format'?: string | number | boolean; 'max'?: string | number | boolean; 'min'?: string | number | boolean; 'muted'?: string | number | boolean; 'step'?: string | number | boolean; 'unit'?: string | number | boolean; 'value'?: string | number | boolean; 'with-mute'?: string | number | boolean }>
    'tc-waypoint-marker': TcProps<{ 'color'?: string | number | boolean; 'distance'?: string | number | boolean; 'icon'?: string | number | boolean; 'label'?: string | number | boolean; 'size'?: string | number | boolean; 'x'?: string | number | boolean; 'y'?: string | number | boolean }>
    'tc-welcome-guide': TcProps<{ 'background-pattern-alt'?: string | number | boolean; 'background-pattern-src'?: string | number | boolean; 'loading'?: string | number | boolean; 'title'?: string | number | boolean }>
}

// React 17+ automatic runtime / React 19 — IntrinsicElements lives on React.JSX.
declare module 'react' {
    namespace JSX {
        interface IntrinsicElements extends ToolcaseIntrinsicElements {}
    }
}

// Classic global JSX namespace — React 18 and the legacy runtime.
declare global {
    namespace JSX {
        interface IntrinsicElements extends ToolcaseIntrinsicElements {}
    }
}

export {}
