package nginxconf

import (
	"errors"
	"fmt"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"

	"github.com/kalevski/toolcase/nginxpilot/internal/config"
)

// ErrPoolMissing is returned when an app's php-fpm pool socket is not
// configured. It is deliberately an error rather than a fallback: letting the
// request reach the static handler would serve index.php as text/plain and
// publish the application's own database credentials. The apply engine treats
// it exactly like ErrCertRequired — the resource is disabled and reported.
var ErrPoolMissing = errors.New("php-fpm pool is not available for this app")

// PoolSocket returns the unix socket path for an app's pool.
func PoolSocket(cfg *config.Config, domain string) string {
	dir := cfg.PHP.SocketDir
	if dir == "" {
		dir = "/run/php"
	}
	return filepath.Join(dir, domain+".sock")
}

// AppVhost renders the server block for an app. It reuses every helper the
// static renderer uses, so TLS, listeners, logging and the per-host toggles
// behave identically; only the body differs.
func AppVhost(cfg *config.Config, app *config.App, opts Options) (string, error) {
	if app.RuntimeMode() != config.RuntimePHP {
		return "", fmt.Errorf("app %q: unsupported runtime %q", app.Domain, app.Runtime)
	}
	if !cfg.PHP.Enabled {
		return "", ErrPoolMissing
	}

	tls, err := resolveTLS(app.TLSMode(), app.Domain, opts)
	if err != nil {
		return "", err
	}

	root := filepath.Join(cfg.DataDir, "apps", app.Domain, "current")
	socket := PoolSocket(cfg, app.Domain)
	index := app.PHP.IndexFile()
	php := app.PHP

	var b strings.Builder
	fmt.Fprintf(&b, "# nginx vhost for php app %s — generated by nginxpilot\n", app.Domain)
	if !opts.Managed {
		fmt.Fprintf(&b, "# Paste into /etc/nginx/conf.d/%s.conf, adapt, then: nginx -t && nginx -s reload\n", app.Domain)
		fmt.Fprintf(&b, "# Run `nginxpilot sync %s` once first so `current` exists.\n", app.Domain)
	}
	b.WriteByte('\n')

	writeRedirectIfForceSSL(&b, app.Domain, 80, tls, app.WebOptions)

	b.WriteString("server {\n")
	writeListeners(&b, 80, tls, app.WebOptions)
	fmt.Fprintf(&b, "    server_name %s;\n", app.Domain)
	writeSSL(&b, tls)
	writeAccessLog(&b, cfg, opts, app.Domain, LogResourceApp)
	writeServerToggles(&b, app.WebOptions, opts, tls)

	fmt.Fprintf(&b, "\n    root %s;\n", root)
	fmt.Fprintf(&b, "    index %s index.html;\n", index)
	fmt.Fprintf(&b, "    client_max_body_size %s;\n", nginxSize(php.MaxBodySizeOrDefault()))

	// Deny rules come BEFORE the executable location so a longer regex match
	// cannot be shadowed. Dotfiles first: .env, .git leftovers, editor files.
	b.WriteString("\n    location ~ /\\. { deny all; }\n")
	b.WriteString("    location ~ ^/(vendor|node_modules)/ { deny all; }\n")

	// The request router.
	b.WriteString("\n    location / {\n")
	switch php.RoutingMode() {
	case config.PHPRoutingStaticFirst:
		b.WriteString("        try_files $uri $uri/ =404;\n")
	default:
		fmt.Fprintf(&b, "        try_files $uri $uri/ /%s?$query_string;\n", index)
	}
	b.WriteString("    }\n")

	// Exactly the front controller executes, plus anything explicitly exposed.
	// Everything else that ends in .php is a 404 — never a fastcgi_pass. This
	// is what stops /uploads/evil.jpg/x.php from executing an uploaded file,
	// which matters more here than in a normal PHP install because the app has
	// a writable persistent directory inside its own document root.
	for _, script := range append([]string{index}, php.Expose...) {
		writePHPLocation(&b, script, socket, php, script == index)
	}

	b.WriteString("\n    location ~ \\.php$ { return 404; }\n")
	b.WriteString("    autoindex off;\n")
	b.WriteString("}\n")

	writeTLSHint(&b, app.Domain, app.WebOptions, opts, tls)
	return b.String(), nil
}

// writePHPLocation emits one executable location. internalOnly marks the front
// controller `internal;` so it is reachable through the try_files fallback but
// never as a direct /index.php request.
func writePHPLocation(b *strings.Builder, script, socket string, php config.AppPHP, internalOnly bool) {
	fmt.Fprintf(b, "\n    location ~ ^/%s(/|$) {\n", regexpEscape(script))
	// Absolute, not the bare `include fastcgi_params;`. nginx resolves a
	// relative include against its PREFIX, and the managed-mode apply validates
	// in a staging directory with a temporary prefix — where the relative name
	// does not resolve and every app would be quarantined by `nginx -t`.
	fmt.Fprintf(b, "        include %s;\n", fastcgiParamsPath)
	fmt.Fprintf(b, "        fastcgi_pass unix:%s;\n", socket)
	b.WriteString("        fastcgi_split_path_info ^(.+\\.php)(/.*)$;\n")
	// $realpath_root, not $document_root: the root is the `current` symlink, and
	// opcache keys compiled scripts by the path it is given. With
	// $document_root every release shares one cache key and php keeps executing
	// the PREVIOUS release after a swap — the atomic-deploy guarantee silently
	// stops applying to PHP. $realpath_root resolves through the symlink, so
	// each release is its own key.
	b.WriteString("        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;\n")
	b.WriteString("        fastcgi_param DOCUMENT_ROOT   $realpath_root;\n")
	b.WriteString("        fastcgi_param PATH_INFO       $fastcgi_path_info;\n")
	// Sorted so a map with the same contents renders byte-identically: the
	// applier diffs generated files to decide whether nginx needs a reload.
	for _, k := range sortedKeys(php.Env) {
		fmt.Fprintf(b, "        fastcgi_param %s %s;\n", k, nginxQuote(php.Env[k]))
	}
	fmt.Fprintf(b, "        fastcgi_read_timeout %s;\n", durationSeconds(php.TimeoutOrDefault()))
	if internalOnly {
		b.WriteString("        internal;\n")
	}
	b.WriteString("    }\n")
}

// fastcgiParamsPath is nginx's stock parameter file. Absolute on purpose — see
// writePHPLocation.
const fastcgiParamsPath = "/etc/nginx/fastcgi_params"

var regexpMeta = regexp.MustCompile(`[.\\+*?()|\[\]{}^$]`)

// regexpEscape quotes a config-supplied script path for use inside an nginx
// location regex. Script paths are already validated to be clean relative paths,
// but they legitimately contain dots, and an unescaped dot is a wildcard.
func regexpEscape(s string) string {
	return regexpMeta.ReplaceAllString(s, `\$0`)
}

// durationSeconds renders a duration in nginx's own `60s` spelling.
func durationSeconds(d time.Duration) string {
	return fmt.Sprintf("%ds", int64(d/time.Second))
}

// nginxSize renders a byte count in nginx's own size spelling.
func nginxSize(n int64) string {
	switch {
	case n%(1<<30) == 0:
		return fmt.Sprintf("%dg", n/(1<<30))
	case n%(1<<20) == 0:
		return fmt.Sprintf("%dm", n/(1<<20))
	case n%(1<<10) == 0:
		return fmt.Sprintf("%dk", n/(1<<10))
	default:
		return fmt.Sprintf("%d", n)
	}
}

// sortedKeys returns a map's keys in a stable order.
func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// nginxQuote wraps a value in double quotes and escapes what nginx treats as
// special inside them. A bare value would end at the first space and a $ would
// be read as a variable, so an app's env would silently become something else.
func nginxQuote(v string) string {
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`, `$`, `\$`)
	return `"` + r.Replace(v) + `"`
}
