package nginxconf

import (
	"fmt"
	"net/netip"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/kalevski/toolcase/nginxpilot/internal/config"
)

// StaticVhost renders the content-serving server block(s) for a static site,
// honoring its TLS + toggle WebOptions.
func StaticVhost(cfg *config.Config, site *config.Site, opts Options) (string, error) {
	tls, err := resolveTLS(site.TLSMode(), site.Domain, opts)
	if err != nil {
		return "", err
	}
	root := filepath.Join(cfg.DataDir, "sites", site.Domain, "current")

	var b strings.Builder
	fmt.Fprintf(&b, "# nginx vhost for %s — generated by nginxpilot\n", site.Domain)
	if !opts.Managed {
		fmt.Fprintf(&b, "# Paste into /etc/nginx/conf.d/%s.conf, adapt, then: nginx -t && nginx -s reload\n", site.Domain)
		fmt.Fprintf(&b, "# Run `nginxpilot sync %s` once first so `current` exists.\n", site.Domain)
	}
	b.WriteByte('\n')

	acmeRoot := acmeWebroot(cfg)
	writeRedirectIfForceSSL(&b, site.Domain, 80, tls, site.WebOptions, acmeRoot)

	b.WriteString("server {\n")
	writeListeners(&b, 80, tls, site.WebOptions)
	fmt.Fprintf(&b, "    server_name %s;\n", site.Domain)
	writeSSL(&b, tls)
	writeAccessLog(&b, cfg, opts, site.Domain, LogResourceSite)
	writeServerToggles(&b, site.WebOptions, opts, tls)
	if acmeRoot != "" {
		writeACMEChallengeLocation(&b, acmeRoot, "    ")
	}

	fmt.Fprintf(&b, "\n    root %s;\n    index index.html;\n", root)
	if site.NotFound != "" {
		fmt.Fprintf(&b, "    error_page 404 %s;\n", site.NotFound)
	}
	if site.CacheAssets {
		b.WriteString("\n    location ~* \\.(?:css|js|mjs|map|woff2?|ttf|otf|eot|ico|gif|jpe?g|png|webp|avif|svg|mp4|webm)$ {\n")
		b.WriteString("        add_header Cache-Control \"public, max-age=31536000, immutable\";\n")
		b.WriteString("        try_files $uri =404;\n    }\n")
	}
	b.WriteString("\n    location / {\n")
	switch site.RoutingMode() {
	case config.RoutingSPA:
		b.WriteString("        try_files $uri $uri/ /index.html;\n")
	case config.RoutingCleanURLs:
		b.WriteString("        try_files $uri $uri.html $uri/ =404;\n")
	default:
		b.WriteString("        try_files $uri $uri/ =404;\n")
	}
	b.WriteString("    }\n")
	b.WriteString("    autoindex off;\n")
	b.WriteString("}\n")

	writeTLSHint(&b, site.Domain, site.WebOptions, opts, tls)
	return b.String(), nil
}

// ProxyVhost renders a reverse-proxy snippet. In generate-only mode (opts.
// Managed false) it prepends the referenced upstream blocks so the output is
// self-contained; in managed mode the upstreams live in their own files, so
// only the server block(s) are emitted.
func ProxyVhost(cfg *config.Config, p *config.Proxy, opts Options) (string, error) {
	tls, err := resolveTLS(p.TLSMode(), p.Domain, opts)
	if err != nil {
		return "", err
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# nginx reverse proxy for %s — generated by nginxpilot\n", p.Domain)
	if !opts.Managed {
		fmt.Fprintf(&b, "# Paste into /etc/nginx/conf.d/%s.conf, adapt, then: nginx -t && nginx -s reload\n", p.Domain)
	}
	b.WriteByte('\n')

	if !opts.Managed {
		byName := map[string]*config.Upstream{}
		for i := range cfg.Upstreams {
			byName[cfg.Upstreams[i].Name] = &cfg.Upstreams[i]
		}
		for _, name := range referencedUpstreams(p) {
			if u := byName[name]; u != nil {
				b.WriteString(UpstreamBlock(u))
				b.WriteByte('\n')
			}
		}
		// proxy_cache_path must live in http{} context, not server{} — emit it as
		// a note above the block for the operator to place.
		if p.Cache.Enabled {
			b.WriteString("# Add this proxy_cache_path to your http{} context (outside server{}):\n")
			b.WriteString("# " + cachePathDirective(p) + "\n\n")
		}
	}

	acmeRoot := acmeWebroot(cfg)
	writeRedirectIfForceSSL(&b, p.Domain, p.ListenPort(), tls, p.WebOptions, acmeRoot)

	httpPort := p.ListenPort()
	b.WriteString("server {\n")
	writeListeners(&b, httpPort, tls, p.WebOptions)
	fmt.Fprintf(&b, "    server_name %s;\n", p.Domain)
	writeSSL(&b, tls)
	writeAccessLog(&b, cfg, opts, p.Domain, LogResourceProxy)
	if p.ClientMaxBodySize > 0 {
		fmt.Fprintf(&b, "    client_max_body_size %s;\n", p.ClientMaxBodySize)
	}
	if p.UsesResolver() {
		writeResolver(&b, cfg.Nginx.Resolver)
	}
	writeServerToggles(&b, p.WebOptions, opts, tls)
	writeAccessControl(&b, cfg, p.AccessList)
	if acmeRoot != "" {
		writeACMEChallengeLocation(&b, acmeRoot, "    ")
	}

	consumeAuth := consumesAuthHeader(cfg, p.AccessList)
	for i, loc := range effectiveLocations(p) {
		writeLocation(&b, p, i, loc, consumeAuth)
	}

	b.WriteString("}\n")
	writeTLSHint(&b, p.Domain, p.WebOptions, opts, tls)
	return b.String(), nil
}

// renderSimpleVhost emits the shared server-block frame every "simple" http
// vhost uses: resolveTLS → generation-comment header → writeRedirectIfForceSSL
// → "server {" → writeListeners → server_name → writeSSL → writeServerToggles
// → access list → body(b, indent) → "}" → writeTLSHint. Redirect and dead-host
// renderers differ ONLY in their body callback; ProxyVhost keeps its own frame
// (it interleaves upstream inlining, client_max_body_size and cache concerns).
// Their bodies are a bare `return`, which at server level would answer before
// any location — so with an ACME webroot the body goes inside `location /`,
// next to the challenge location, and with an access list it goes behind the
// access check (see below); indent says how deep it is.
func renderSimpleVhost(cfg *config.Config, kind, domain string, listen int, w config.WebOptions,
	accessList string, opts Options, body func(b *strings.Builder, indent string)) (string, error) {
	tls, err := resolveTLS(w.TLSMode(), domain, opts)
	if err != nil {
		return "", err
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# nginx %s for %s — generated by nginxpilot\n", kind, domain)
	if !opts.Managed {
		fmt.Fprintf(&b, "# Paste into /etc/nginx/conf.d/%s.conf, adapt, then: nginx -t && nginx -s reload\n", config.FileStem(domain))
	}
	b.WriteByte('\n')

	acmeRoot := acmeWebroot(cfg)
	writeRedirectIfForceSSL(&b, domain, listen, tls, w, acmeRoot)

	b.WriteString("server {\n")
	writeListeners(&b, listen, tls, w)
	fmt.Fprintf(&b, "    server_name %s;\n", domain)
	writeSSL(&b, tls)
	writeAccessLog(&b, cfg, opts, domain, simpleVhostResourceType(kind))
	writeServerToggles(&b, w, opts, tls)
	writeAccessControl(&b, cfg, accessList)
	guarded := accessList != "" && findAccessList(cfg, accessList) != nil
	switch {
	case guarded:
		// A return runs in the rewrite phase, BEFORE allow/deny and auth_basic
		// (access phase), so a bare return would answer every client and the
		// access list would guard nothing. try_files runs in the content phase,
		// after the access check: a file that cannot exist falls through to the
		// named location holding the return.
		if acmeRoot != "" {
			writeACMEChallengeLocation(&b, acmeRoot, "    ")
		}
		b.WriteString("\n    location / {\n        try_files /.nginxpilot-no-such-file @nginxpilot_answer;\n    }\n")
		b.WriteString("\n    location @nginxpilot_answer {")
		body(&b, "        ")
		b.WriteString("    }\n")
	case acmeRoot != "":
		writeACMEChallengeLocation(&b, acmeRoot, "    ")
		b.WriteString("\n    location / {")
		body(&b, "        ")
		b.WriteString("    }\n")
	default:
		body(&b, "    ")
	}
	b.WriteString("}\n")

	writeTLSHint(&b, domain, w, opts, tls)
	return b.String(), nil
}

// UpstreamBlock renders one nginx http upstream{} block.
func UpstreamBlock(u *config.Upstream) string {
	var b strings.Builder
	fmt.Fprintf(&b, "upstream %s {\n", u.Name)
	switch u.Balancer {
	case config.BalancerLeastConn:
		b.WriteString("    least_conn;\n")
	case config.BalancerIPHash:
		b.WriteString("    ip_hash;\n")
	}
	for _, s := range u.Servers {
		b.WriteString("    server " + s.Address)
		if s.Weight > 0 {
			b.WriteString(" weight=" + strconv.Itoa(s.Weight))
		}
		if s.MaxFails != nil {
			b.WriteString(" max_fails=" + strconv.Itoa(*s.MaxFails))
		}
		if s.FailTimeout > 0 {
			b.WriteString(" fail_timeout=" + s.FailTimeout.String())
		}
		if s.Backup {
			b.WriteString(" backup")
		}
		if s.Down {
			b.WriteString(" down")
		}
		b.WriteString(";\n")
	}
	if u.Keepalive > 0 {
		fmt.Fprintf(&b, "    keepalive %d;\n", u.Keepalive)
	}
	b.WriteString("}\n")
	return b.String()
}

// writeListeners writes the listen directives for the main server block. When
// TLS is enabled but force_ssl is off, the block serves both plain HTTP and
// HTTPS; with force_ssl the plain listener moves to the redirect block.
func writeListeners(b *strings.Builder, httpPort int, tls tlsState, w config.WebOptions) {
	if !tls.enabled {
		fmt.Fprintf(b, "    listen %d;\n    listen [::]:%d;\n", httpPort, httpPort)
		return
	}
	if !w.ForceSSL {
		fmt.Fprintf(b, "    listen %d;\n    listen [::]:%d;\n", httpPort, httpPort)
	}
	b.WriteString("    listen 443 ssl;\n    listen [::]:443 ssl;\n")
	if w.HTTP2 {
		b.WriteString("    http2 on;\n")
	}
}

// writeRedirectIfForceSSL emits the 80 → 301 https server when force_ssl is set
// (validation guarantees force_ssl implies TLS). With an ACME webroot the
// redirect moves into `location /`: a server-level return runs before any
// location is matched, so it would redirect the HTTP-01 challenge too.
func writeRedirectIfForceSSL(b *strings.Builder, domain string, httpPort int, tls tlsState, w config.WebOptions, acmeRoot string) {
	if !w.ForceSSL || !tls.enabled {
		return
	}
	b.WriteString("server {\n")
	fmt.Fprintf(b, "    listen %d;\n    listen [::]:%d;\n", httpPort, httpPort)
	fmt.Fprintf(b, "    server_name %s;\n", domain)
	if acmeRoot == "" {
		b.WriteString("    return 301 https://$host$request_uri;\n}\n\n")
		return
	}
	writeACMEChallengeLocation(b, acmeRoot, "    ")
	b.WriteString("\n    location / {\n        return 301 https://$host$request_uri;\n    }\n}\n\n")
}

// writeSSL writes ssl_certificate/key plus nginxpilot's modern TLS defaults.
func writeSSL(b *strings.Builder, tls tlsState) {
	if !tls.enabled {
		return
	}
	fmt.Fprintf(b, "    ssl_certificate     %s;\n", tls.cert)
	fmt.Fprintf(b, "    ssl_certificate_key %s;\n", tls.key)
	b.WriteString("    ssl_protocols TLSv1.2 TLSv1.3;\n")
	b.WriteString("    ssl_session_cache shared:SSL:10m;\n")
}

// writeServerToggles writes the server-level toggles common to sites and
// proxies: hsts, block_exploits, gzip, advanced.
func writeServerToggles(b *strings.Builder, w config.WebOptions, opts Options, tls tlsState) {
	if w.HSTS.Enabled && tls.enabled {
		fmt.Fprintf(b, "    add_header Strict-Transport-Security \"%s\" always;\n", hstsValue(w.HSTS))
	}
	if w.BlockExploits {
		writeBlockExploits(b, opts)
	}
	if w.Gzip {
		b.WriteString("    gzip on;\n")
		b.WriteString("    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml;\n")
	}
	writeAdvanced(b, w.Advanced, "    ")
}

// writeAdvanced emits a raw-passthrough snippet at the given indent, shared by
// the server-level (WebOptions.Advanced) and location-level
// (ProxyLocation.Advanced) escape hatches.
func writeAdvanced(b *strings.Builder, text, indent string) {
	if strings.TrimSpace(text) == "" {
		return
	}
	b.WriteString("\n" + indent + "# advanced (raw passthrough)\n")
	for _, line := range strings.Split(strings.TrimRight(text, "\n"), "\n") {
		b.WriteString(indent + line + "\n")
	}
}

// writeBlockExploits references the managed include in managed mode, or inlines
// the snippet for a self-contained print-vhost output.
func writeBlockExploits(b *strings.Builder, opts Options) {
	if opts.Managed {
		dir := opts.IncludeDir
		if dir == "" {
			dir = config.DefaultManagedIncludeDir
		}
		fmt.Fprintf(b, "    include %s;\n", filepath.Join(dir, BlockExploitsFilename))
		return
	}
	b.WriteString("\n    # block-exploits (inline)\n")
	for _, line := range strings.Split(strings.TrimRight(blockExploitsRules(), "\n"), "\n") {
		if line == "" {
			b.WriteString("\n")
			continue
		}
		b.WriteString("    " + line + "\n")
	}
}

// writeTLSHint adds a trailing certbot hint only when TLS is off and the
// snippet is for a human (print-vhost) — managed output stays terse.
func writeTLSHint(b *strings.Builder, domain string, w config.WebOptions, opts Options, tls tlsState) {
	if opts.Managed {
		return
	}
	if !tls.enabled {
		fmt.Fprintf(b, "\n# TLS: set `tls: auto` (with a cert dir) or terminate with certbot:\n#   certbot --nginx -d %s\n", domain)
		return
	}
	if !tls.found {
		fmt.Fprintf(b, "\n# TLS cert paths above are the conventional certbot layout — issue one with:\n#   certbot --nginx -d %s\n", domain)
	}
}

// hstsValue builds the Strict-Transport-Security header value.
func hstsValue(h config.HSTS) string {
	v := fmt.Sprintf("max-age=%d", h.MaxAgeOrDefault())
	if h.IncludesSubdomains() {
		v += "; includeSubDomains"
	}
	if h.Preload {
		v += "; preload"
	}
	return v
}

// writeLocation renders one location{} block with proxy_pass + forwarding
// headers, WebSocket upgrade headers (per-location or proxy-level), cache, and
// the per-server proxy timeouts. consumeAuth blanks the client's Authorization
// header before proxy_pass — set when the proxy's access list authenticates at
// the edge with pass_auth off.
//
// A location that resolves per request (config.Proxy.ResolvesPerRequest)
// stages its pass in a variable, $np_pass_<index>: nginx resolves a proxy_pass
// hostname once at load, but a proxy_pass holding a variable is resolved at
// request time through the server's resolver, cached for resolver valid=.
func writeLocation(b *strings.Builder, p *config.Proxy, index int, loc config.ProxyLocation, consumeAuth bool) {
	target := proxyPassTarget(p, loc)
	fmt.Fprintf(b, "\n    location %s {\n", loc.Path)
	if p.ResolvesPerRequest(loc) {
		fmt.Fprintf(b, "        set $np_pass_%d %s;\n", index, target)
		fmt.Fprintf(b, "        proxy_pass $np_pass_%d;\n", index)
	} else {
		fmt.Fprintf(b, "        proxy_pass %s;\n", target)
	}
	b.WriteString("        proxy_http_version 1.1;\n")
	b.WriteString("        proxy_set_header Host $host;\n")
	b.WriteString("        proxy_set_header X-Real-IP $remote_addr;\n")
	b.WriteString("        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n")
	b.WriteString("        proxy_set_header X-Forwarded-Proto $scheme;\n")
	if consumeAuth {
		b.WriteString("        proxy_set_header Authorization \"\";\n")
	}
	if loc.Websocket || p.Websocket {
		b.WriteString("        proxy_set_header Upgrade $http_upgrade;\n")
		b.WriteString("        proxy_set_header Connection \"upgrade\";\n")
	}
	if p.ConnectTimeout > 0 {
		fmt.Fprintf(b, "        proxy_connect_timeout %s;\n", p.ConnectTimeout)
	}
	if p.ReadTimeout > 0 {
		fmt.Fprintf(b, "        proxy_read_timeout %s;\n", p.ReadTimeout)
	}
	if p.SendTimeout > 0 {
		fmt.Fprintf(b, "        proxy_send_timeout %s;\n", p.SendTimeout)
	}
	if p.Cache.Enabled {
		fmt.Fprintf(b, "        proxy_cache %s;\n", cacheZoneName(p.Domain))
		for _, v := range p.Cache.Valid {
			fmt.Fprintf(b, "        proxy_cache_valid %s;\n", v)
		}
		b.WriteString("        add_header X-Cache-Status $upstream_cache_status;\n")
	}
	writeAdvanced(b, loc.Advanced, "        ")
	b.WriteString("    }\n")
}

// proxyPassTarget resolves the proxy_pass argument for a location: a named
// upstream becomes http://<name>, an inline pass is used verbatim. Location
// settings override the proxy default.
func proxyPassTarget(p *config.Proxy, loc config.ProxyLocation) string {
	up, pass := p.LocationTarget(loc)
	if up != "" {
		return "http://" + up
	}
	return pass
}

// effectiveLocations returns the proxy's locations, defaulting to a single "/"
// location using the proxy default when none are declared.
func effectiveLocations(p *config.Proxy) []config.ProxyLocation {
	return p.EffectiveLocations()
}

// writeResolver emits the request-time DNS directives for a proxy with at least
// one per-request location. They are server-level so every such location shares
// one resolver; IPv6 addresses are bracketed, as nginx requires.
func writeResolver(b *strings.Builder, r config.Resolver) {
	addrs := make([]string, 0, len(r.AddressesOrDefault()))
	for _, a := range r.AddressesOrDefault() {
		if ip, err := netip.ParseAddr(a); err == nil && ip.Is6() {
			a = "[" + a + "]"
		}
		addrs = append(addrs, a)
	}
	ipv6 := "off"
	if r.IPv6Enabled() {
		ipv6 = "on"
	}
	fmt.Fprintf(b, "    resolver %s valid=%s ipv6=%s;\n", strings.Join(addrs, " "), nginxTime(r.ValidOrDefault()), ipv6)
	fmt.Fprintf(b, "    resolver_timeout %s;\n", nginxTime(r.TimeoutOrDefault()))
}

// nginxTime renders a duration in nginx's time syntax: whole seconds as "10s",
// anything finer as milliseconds ("1500ms") — never Go's "1m0s" or "1.5s".
func nginxTime(d time.Duration) string {
	if d%time.Second == 0 {
		return strconv.FormatInt(int64(d/time.Second), 10) + "s"
	}
	return strconv.FormatInt(int64(d/time.Millisecond), 10) + "ms"
}

// referencedUpstreams returns the distinct named upstreams a proxy uses, in
// first-seen order (proxy default first, then per-location overrides).
func referencedUpstreams(p *config.Proxy) []string {
	var out []string
	seen := map[string]bool{}
	add := func(name string) {
		if name != "" && !seen[name] {
			seen[name] = true
			out = append(out, name)
		}
	}
	add(p.Upstream)
	for _, loc := range p.Locations {
		add(loc.Upstream)
	}
	return out
}
