// Package nginxconf generates nginx server-block / upstream snippets from
// the daemon's config entities. It is a pure text generator: the daemon never
// writes nginx config nor reloads nginx (zero request-path coupling). Both the
// `print-vhost` CLI and the admin GET /vhost/<domain> endpoint render through
// here so the two surfaces never drift.
package nginxconf

import (
	"errors"
	"fmt"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/kalevski/toolcase/nginxpilot/internal/config"
)

// ErrUnknownDomain is returned by Vhost when no site or proxy owns the domain.
var ErrUnknownDomain = errors.New("domain is not configured")

// Vhost renders the nginx snippet for one domain. A static site yields a
// content-serving server{} block; a reverse proxy yields the upstream{}
// block(s) it references plus a proxy_pass server{} block.
func Vhost(cfg *config.Config, domain string) (string, error) {
	for i := range cfg.Sites {
		if cfg.Sites[i].Domain == domain {
			return StaticVhost(cfg.DataDir, domain), nil
		}
	}
	for i := range cfg.Proxies {
		if cfg.Proxies[i].Domain == domain {
			return ProxyVhost(cfg, &cfg.Proxies[i]), nil
		}
	}
	return "", fmt.Errorf("%q: %w", domain, ErrUnknownDomain)
}

// StaticVhost renders the content-serving server block for a static site.
func StaticVhost(dataDir, domain string) string {
	root := filepath.Join(dataDir, "sites", domain, "current")
	return fmt.Sprintf(`# nginx vhost for %[1]s — generated by nginxpilot print-vhost
# Paste into /etc/nginx/sites-available/%[1]s.conf (or conf.d/), adapt, then:
#   nginx -t && nginx -s reload
#
# Onboarding tip: run `+"`nginxpilot sync %[1]s`"+` once BEFORE
# enabling this vhost so `+"`current`"+` exists and nginx doesn't 404.

server {
    listen 80;
    listen [::]:80;
    server_name %[1]s;

    # Content is deployed atomically by nginxpilot; the `+"`current`"+`
    # symlink is swapped via rename(2) — no nginx reload needed on updates.
    root %[2]s;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
        # For single-page apps use instead:
        # try_files $uri $uri/ /index.html;
    }

    # If your CI pre-compresses assets (.gz next to each file):
    # gzip_static on;

    # Keep directory listings off — deployed content is source-controlled,
    # anything unexpected should 404, not enumerate.
    autoindex off;
}

# TLS: terminate with certbot/acme.sh (nginxpilot does not manage
# certificates), e.g.:
#   certbot --nginx -d %[1]s
`, domain, root)
}

// ProxyVhost renders the upstream{} block(s) a proxy references followed by
// its server{} block. The snippet is self-contained (paste-and-go); when an
// upstream is shared across proxies, emit it once and drop the duplicate.
func ProxyVhost(cfg *config.Config, p *config.Proxy) string {
	var b strings.Builder
	port := p.ListenPort()

	fmt.Fprintf(&b, "# nginx reverse proxy for %[1]s — generated by nginxpilot print-vhost\n", p.Domain)
	fmt.Fprintf(&b, "# Paste into /etc/nginx/sites-available/%[1]s.conf (or conf.d/), adapt, then:\n", p.Domain)
	b.WriteString("#   nginx -t && nginx -s reload\n\n")

	// Referenced named upstreams, in first-seen order, emitted self-contained.
	byName := map[string]*config.Upstream{}
	for i := range cfg.Upstreams {
		byName[cfg.Upstreams[i].Name] = &cfg.Upstreams[i]
	}
	for _, name := range referencedUpstreams(p) {
		if u := byName[name]; u != nil {
			b.WriteString(UpstreamBlock(u))
			b.WriteByte('\n')
		}
	}

	fmt.Fprintf(&b, "server {\n    listen %d;\n    listen [::]:%d;\n    server_name %s;\n", port, port, p.Domain)
	if p.ClientMaxBodySize > 0 {
		fmt.Fprintf(&b, "    client_max_body_size %s;\n", p.ClientMaxBodySize)
	}

	for _, loc := range effectiveLocations(p) {
		writeLocation(&b, p, loc)
	}

	b.WriteString("}\n\n")
	fmt.Fprintf(&b, "# TLS: terminate with certbot/acme.sh (nginxpilot does not manage\n# certificates), e.g.:\n#   certbot --nginx -d %s\n", p.Domain)
	return b.String()
}

// UpstreamBlock renders one nginx upstream{} block.
func UpstreamBlock(u *config.Upstream) string {
	var b strings.Builder
	fmt.Fprintf(&b, "upstream %s {\n", u.Name)
	switch u.Balancer {
	case config.BalancerLeastConn:
		b.WriteString("    least_conn;\n")
	case config.BalancerIPHash:
		b.WriteString("    ip_hash;\n")
	}
	for _, s := range u.Servers {
		b.WriteString("    server " + s.Address)
		if s.Weight > 0 {
			b.WriteString(" weight=" + strconv.Itoa(s.Weight))
		}
		if s.MaxFails != nil {
			b.WriteString(" max_fails=" + strconv.Itoa(*s.MaxFails))
		}
		if s.FailTimeout > 0 {
			b.WriteString(" fail_timeout=" + s.FailTimeout.String())
		}
		if s.Backup {
			b.WriteString(" backup")
		}
		if s.Down {
			b.WriteString(" down")
		}
		b.WriteString(";\n")
	}
	if u.Keepalive > 0 {
		fmt.Fprintf(&b, "    keepalive %d;\n", u.Keepalive)
	}
	b.WriteString("}\n")
	return b.String()
}

// writeLocation renders one location{} block with proxy_pass + the standard
// forwarding headers (and WebSocket upgrade headers when requested).
func writeLocation(b *strings.Builder, p *config.Proxy, loc config.ProxyLocation) {
	target := proxyPassTarget(p, loc)
	fmt.Fprintf(b, "\n    location %s {\n", loc.Path)
	fmt.Fprintf(b, "        proxy_pass %s;\n", target)
	b.WriteString("        proxy_http_version 1.1;\n")
	b.WriteString("        proxy_set_header Host $host;\n")
	b.WriteString("        proxy_set_header X-Real-IP $remote_addr;\n")
	b.WriteString("        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n")
	b.WriteString("        proxy_set_header X-Forwarded-Proto $scheme;\n")
	if loc.Websocket {
		b.WriteString("        proxy_set_header Upgrade $http_upgrade;\n")
		b.WriteString("        proxy_set_header Connection \"upgrade\";\n")
	}
	if p.ConnectTimeout > 0 {
		fmt.Fprintf(b, "        proxy_connect_timeout %s;\n", p.ConnectTimeout)
	}
	if p.ReadTimeout > 0 {
		fmt.Fprintf(b, "        proxy_read_timeout %s;\n", p.ReadTimeout)
	}
	if p.SendTimeout > 0 {
		fmt.Fprintf(b, "        proxy_send_timeout %s;\n", p.SendTimeout)
	}
	b.WriteString("    }\n")
}

// proxyPassTarget resolves the proxy_pass argument for a location: a named
// upstream becomes http://<name>, an inline pass is used verbatim. Location
// settings override the proxy default.
func proxyPassTarget(p *config.Proxy, loc config.ProxyLocation) string {
	up, pass := loc.Upstream, loc.Pass
	if up == "" && pass == "" {
		up, pass = p.Upstream, p.Pass
	}
	if up != "" {
		return "http://" + up
	}
	return pass
}

// effectiveLocations returns the proxy's locations, defaulting to a single
// "/" location using the proxy default when none are declared.
func effectiveLocations(p *config.Proxy) []config.ProxyLocation {
	if len(p.Locations) == 0 {
		return []config.ProxyLocation{{Path: "/"}}
	}
	return p.Locations
}

// referencedUpstreams returns the distinct named upstreams a proxy uses,
// in first-seen order (proxy default first, then per-location overrides).
func referencedUpstreams(p *config.Proxy) []string {
	var out []string
	seen := map[string]bool{}
	add := func(name string) {
		if name != "" && !seen[name] {
			seen[name] = true
			out = append(out, name)
		}
	}
	add(p.Upstream)
	for _, loc := range p.Locations {
		add(loc.Upstream)
	}
	return out
}
