package nginxconf

import (
	"fmt"
	"strings"

	"github.com/kalevski/toolcase/nginxpilot/internal/config"
)

// BlockExploitsFilename is the managed shared snippet referenced by `include`
// from a resource with block_exploits: true. The .inc extension (not .conf)
// keeps it out of the operator's `include nginxpilot.d/*.conf` wildcard — it
// holds server-scoped `if` rules that are invalid if auto-loaded at http
// context, so it must only ever be pulled in by an explicit `include`.
const BlockExploitsFilename = "block-exploits.inc"

// CacheIncludeFilename is the managed shared include declaring the http-context
// proxy_cache_path zones for every proxy with cache: enabled.
const CacheIncludeFilename = "00-nginxpilot-cache.conf"

// RealIPIncludeFilename is the managed http-context include restoring the real
// client IP behind a CDN/trusted proxy (better.md §8): set_real_ip_from for
// every trusted range plus real_ip_header / real_ip_recursive.
const RealIPIncludeFilename = "00-nginxpilot-realip.conf"

// RealIPInclude renders the real-ip include from the config's static CIDRs plus
// the (cache-loaded, pre-validated) provider ranges. Returns "" when disabled.
func RealIPInclude(cfg *config.Config, providerRanges []string) string {
	r := cfg.Nginx.RealIP
	if !r.Enabled {
		return ""
	}
	var b strings.Builder
	b.WriteString("# nginxpilot managed real-ip trust list — do not edit.\n")
	b.WriteString("# Restores the client IP from " + r.HeaderOrDefault() + " for requests arriving via trusted ranges.\n")
	for _, c := range r.StaticCidrs {
		b.WriteString("set_real_ip_from " + c + ";\n")
	}
	for _, c := range providerRanges {
		b.WriteString("set_real_ip_from " + c + ";\n")
	}
	b.WriteString("real_ip_header " + r.HeaderOrDefault() + ";\n")
	if r.IsRecursive() {
		b.WriteString("real_ip_recursive on;\n")
	} else {
		b.WriteString("real_ip_recursive off;\n")
	}
	return b.String()
}

// blockExploitsRules returns the deny rules (server-block scoped) mirroring
// Nginx Proxy Manager's block-exploits: common SQLi / file-injection query
// patterns and known scanner user-agents. The regexes are intentionally left
// unquoted so nginx's string-escaping never mangles a backslash — keeping the
// shared managed include reliably `nginx -t`-clean (a broken include would take
// down every resource that references it).
func blockExploitsRules() string {
	return `# Deny common exploit patterns (generated by nginxpilot).
if ($request_uri ~* (\.\./|\.\.%2f)) { return 403; }
if ($request_uri ~* (boot\.ini|etc/passwd|self/environ)) { return 403; }
if ($query_string ~* (union.+select|insert.+into|drop.+table|information_schema)) { return 403; }
if ($http_user_agent ~* (nmap|nikto|sqlmap|fimap|nessus|whatweb|openvas|wpscan|masscan)) { return 403; }
`
}

// BlockExploitsSnippet is the full content of the managed block-exploits.conf
// file (a comment header + the rules). The engine writes it into the managed
// include dir; resources reference it via `include`.
func BlockExploitsSnippet() string {
	return "# nginxpilot managed exploit-blocking rules — included by resources with block_exploits: true.\n" +
		"# Do not edit; nginxpilot rewrites this file.\n" +
		blockExploitsRules()
}

// cacheZoneName derives a keys_zone-safe identifier from a domain (dots and any
// other non-identifier chars become underscores).
func cacheZoneName(domain string) string {
	return strings.Map(func(r rune) rune {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9', r == '_':
			return r
		default:
			return '_'
		}
	}, domain)
}

// cachePathDirective renders the http-context proxy_cache_path directive for a
// proxy's cache zone.
func cachePathDirective(p *config.Proxy) string {
	zone := cacheZoneName(p.Domain)
	return fmt.Sprintf("proxy_cache_path /var/cache/nginx/nginxpilot/%s levels=1:2 keys_zone=%s:%s max_size=1g inactive=60m use_temp_path=off;",
		zone, zone, p.Cache.ZoneSizeOrDefault())
}

// CachePathInclude renders the managed shared cache include: one
// proxy_cache_path per proxy with cache enabled. Returns "" when no proxy uses
// caching (the engine then omits the file).
func CachePathInclude(cfg *config.Config) string {
	var b strings.Builder
	any := false
	for i := range cfg.Proxies {
		p := &cfg.Proxies[i]
		if !p.Cache.Enabled || !p.IsEnabled() {
			continue
		}
		if !any {
			b.WriteString("# nginxpilot managed proxy cache zones — do not edit.\n")
			any = true
		}
		b.WriteString(cachePathDirective(p) + "\n")
	}
	if !any {
		return ""
	}
	return b.String()
}
