package nginxconf

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/kalevski/toolcase/nginxpilot/internal/config"
)

// StreamUpstreamBlock renders one stream-context upstream{} block.
func StreamUpstreamBlock(u *config.StreamUpstream) string {
	var b strings.Builder
	fmt.Fprintf(&b, "upstream %s {\n", u.Name)
	switch u.Balancer {
	case config.StreamBalancerLeastConn:
		b.WriteString("    least_conn;\n")
	case config.StreamBalancerHash:
		b.WriteString("    hash $remote_addr;\n")
	}
	for _, s := range u.Servers {
		b.WriteString("    server " + s.Address)
		if s.Weight > 0 {
			b.WriteString(" weight=" + strconv.Itoa(s.Weight))
		}
		if s.MaxFails != nil {
			b.WriteString(" max_fails=" + strconv.Itoa(*s.MaxFails))
		}
		if s.FailTimeout > 0 {
			b.WriteString(" fail_timeout=" + s.FailTimeout.String())
		}
		if s.Backup {
			b.WriteString(" backup")
		}
		if s.Down {
			b.WriteString(" down")
		}
		b.WriteString(";\n")
	}
	b.WriteString("}\n")
	return b.String()
}

// StreamBlock renders one stream-context server{} block for an L4 (TCP/UDP)
// proxy. These directives must be included from nginx's top-level stream{}
// context (see `nginxpilot print-include`), not conf.d/ (which is in http{}).
func StreamBlock(s *config.Stream, opts Options) (string, error) {
	tls, err := resolveTLS(s.TLSMode(), s.TLSDomain, opts)
	if err != nil {
		return "", err
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# nginx stream %s (%s/%d) — generated by nginxpilot\n", s.Name, s.ProtocolOrTCP(), s.Listen)
	b.WriteString("server {\n")

	listen := fmt.Sprintf("    listen %d", s.Listen)
	if s.ProtocolOrTCP() == config.ProtocolUDP {
		listen += " udp"
	}
	if tls.enabled {
		listen += " ssl"
	}
	if s.ProxyProtocol {
		listen += " proxy_protocol"
	}
	b.WriteString(listen + ";\n")

	if tls.enabled {
		fmt.Fprintf(&b, "    ssl_certificate     %s;\n", tls.cert)
		fmt.Fprintf(&b, "    ssl_certificate_key %s;\n", tls.key)
		b.WriteString("    ssl_protocols TLSv1.2 TLSv1.3;\n")
	}

	if s.Upstream != "" {
		fmt.Fprintf(&b, "    proxy_pass %s;\n", s.Upstream)
	} else {
		fmt.Fprintf(&b, "    proxy_pass %s;\n", s.Pass)
	}
	if s.ConnectTimeout > 0 {
		fmt.Fprintf(&b, "    proxy_connect_timeout %s;\n", s.ConnectTimeout)
	}
	if s.Timeout > 0 {
		fmt.Fprintf(&b, "    proxy_timeout %s;\n", s.Timeout)
	}
	b.WriteString("}\n")
	return b.String(), nil
}
