package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"

	"github.com/kalevski/toolcase/nginxpilot/internal/config"
)

// cmdPrintVhost prints a correct, commented nginx server-block starting
// snippet for one domain (Model A helper, spec §5). The daemon never
// touches nginx config — paste and adapt this.
func cmdPrintVhost(args []string) int {
	fs := flag.NewFlagSet("print-vhost", flag.ExitOnError)
	configPath := fs.String("config", config.DefaultPath, "config file path")
	domain, ok := parseWithPositional(fs, args, "usage: nginxpilot print-vhost <domain> [flags]")
	if !ok {
		return 2
	}

	res, err := config.Load(*configPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "config error: %v\n", err)
		return 1
	}
	found := false
	for _, site := range res.Config.Sites {
		if site.Domain == domain {
			found = true
			break
		}
	}
	if !found {
		fmt.Fprintf(os.Stderr, "domain %q is not configured\n", domain)
		return 1
	}

	root := filepath.Join(res.Config.DataDir, "sites", domain, "current")
	fmt.Printf(`# nginx vhost for %[1]s — generated by nginxpilot print-vhost
# Paste into /etc/nginx/sites-available/%[1]s.conf (or conf.d/), adapt, then:
#   nginx -t && nginx -s reload
#
# Onboarding tip: run `+"`nginxpilot sync %[1]s`"+` once BEFORE
# enabling this vhost so `+"`current`"+` exists and nginx doesn't 404.

server {
    listen 80;
    listen [::]:80;
    server_name %[1]s;

    # Content is deployed atomically by nginxpilot; the `+"`current`"+`
    # symlink is swapped via rename(2) — no nginx reload needed on updates.
    root %[2]s;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
        # For single-page apps use instead:
        # try_files $uri $uri/ /index.html;
    }

    # If your CI pre-compresses assets (.gz next to each file):
    # gzip_static on;

    # Keep directory listings off — deployed content is source-controlled,
    # anything unexpected should 404, not enumerate.
    autoindex off;
}

# TLS: terminate with certbot/acme.sh (nginxpilot does not manage
# certificates), e.g.:
#   certbot --nginx -d %[1]s
`, domain, root)
	return 0
}
