import type React from 'react'

type GCAttrs = React.HTMLAttributes<HTMLElement> & Record<string, unknown>

declare module 'react' {
    namespace JSX {
        interface IntrinsicElements {
            'gc-panel': GCAttrs
            'gc-stack': GCAttrs
            'gc-grid': GCAttrs
            'gc-anchor': GCAttrs
            'gc-safe-area': GCAttrs
            'gc-aspect-ratio-box': GCAttrs
            'gc-list': GCAttrs
            'gc-combo-box': GCAttrs
            'gc-key-binder': GCAttrs
            'gc-gamepad-button-prompt': GCAttrs
            'gc-main-menu': GCAttrs
            'gc-pause-menu': GCAttrs
            'gc-page-indicator': GCAttrs
            'gc-nav-button': GCAttrs
            'gc-confirm-dialog': GCAttrs
            'gc-loading-overlay': GCAttrs
            'gc-health-bar': GCAttrs
            'gc-mana-bar': GCAttrs
            'gc-stamina-bar': GCAttrs
            'gc-circular-progress': GCAttrs
            'gc-compass-bar': GCAttrs
            'gc-compass-rose': GCAttrs
            'gc-crosshair': GCAttrs
            'gc-hit-marker': GCAttrs
            'gc-ammo-counter': GCAttrs
            'gc-damage-number': GCAttrs
            'gc-waypoint-marker': GCAttrs
            'gc-interact-prompt': GCAttrs
            'gc-score-display': GCAttrs
            'gc-combo-counter': GCAttrs
            'gc-speedometer': GCAttrs
            'gc-subtitle': GCAttrs
            'gc-dialogue-box': GCAttrs
            'gc-minimap': GCAttrs
            'gc-skill-bar': GCAttrs
            'gc-buff-bar': GCAttrs
            'gc-quest-tracker': GCAttrs
            'gc-objective-marker': GCAttrs
            'gc-kill-feed': GCAttrs
            'gc-chat-window': GCAttrs
            'gc-radial-wheel': GCAttrs
            'gc-title-screen': GCAttrs
            'gc-press-any-key': GCAttrs
            'gc-loading-screen': GCAttrs
            'gc-matchmaking-screen': GCAttrs
            'gc-result-screen': GCAttrs
            'gc-game-over-screen': GCAttrs
            'gc-victory-screen': GCAttrs
            'gc-pause-screen': GCAttrs
            'gc-save-slot-list': GCAttrs
            'gc-credits-scroll': GCAttrs
            'gc-credits-list': GCAttrs
            'gc-legal-screen': GCAttrs
            'gc-character-select': GCAttrs
            'gc-character-create': GCAttrs
            'gc-lobby': GCAttrs
            'gc-level-select': GCAttrs
            'gc-settings-category-list': GCAttrs
            'gc-volume-slider': GCAttrs
            'gc-select-row': GCAttrs
            'gc-toggle-row': GCAttrs
            'gc-fullscreen-toggle': GCAttrs
            'gc-vsync-toggle': GCAttrs
            'gc-invert-axis-toggle': GCAttrs
            'gc-graphics-preset-picker': GCAttrs
            'gc-fov-slider': GCAttrs
            'gc-fps-cap-select': GCAttrs
            'gc-controls-rebind-list': GCAttrs
            'gc-reset-to-defaults': GCAttrs
            'gc-brightness-calibration': GCAttrs
            'gc-mouse-sensitivity': GCAttrs
            'gc-deadzone-slider': GCAttrs
            'gc-controller-layout-preview': GCAttrs
            'gc-item-slot': GCAttrs
            'gc-inventory-grid': GCAttrs
            'gc-item-tooltip': GCAttrs
            'gc-item-compare': GCAttrs
            'gc-equipment-doll': GCAttrs
            'gc-crafting-panel': GCAttrs
            'gc-loot-list': GCAttrs
            'gc-shop-panel': GCAttrs
            'gc-currency-display': GCAttrs
            'gc-skill-tree': GCAttrs
            'gc-ability-card': GCAttrs
            'gc-perk-picker': GCAttrs
            'gc-achievement-list': GCAttrs
            'gc-stats-screen': GCAttrs
            'gc-codex': GCAttrs
            'gc-journal': GCAttrs
            'gc-battle-pass': GCAttrs
            'gc-friends-list': GCAttrs
            'gc-party-panel': GCAttrs
            'gc-guild-panel': GCAttrs
            'gc-player-card': GCAttrs
            'gc-report-player-dialog': GCAttrs
            'gc-mute-list': GCAttrs
            'gc-invite-toast': GCAttrs
            'gc-screen-flash': GCAttrs
            'gc-vignette-overlay': GCAttrs
            'gc-blur-overlay': GCAttrs
            'gc-letterbox-bars': GCAttrs
            'gc-shake-container': GCAttrs
            'gc-particle-emitter': GCAttrs
            'gc-transition-wipe': GCAttrs
            'gc-network-status-icon': GCAttrs
            'gc-ping-display': GCAttrs
            'gc-platform-icon': GCAttrs
            'gc-version-label': GCAttrs
            'gc-debug-overlay': GCAttrs
        }
    }
}
