#!/usr/bin/env python3
"""Create the buckets and tokens one suite needs through the admin API.

usage: bootstrap.py --suite NAME --admin-url URL --admin-token TOKEN --endpoint URL
                    --tool-endpoint URL --domain DOMAIN --out DIR

Every suite gets its own set of five buckets (so suites cannot disturb each other), named
bvt-<suite>-<kind>:

    plain      default settings
    versioned  versioning enabled + SSE-S3 default encryption
    public     anonymous_read "objects" + CORS rules
    quota      quota_bytes = QUOTA_BYTES
    ctype      allowed_content_types = CTYPE_PATTERNS

each with one full-access token. Writes DIR/env.json (for Python/Go/JS) and DIR/env.sh (for bash).
Stdlib only.
"""
import argparse
import json
import os
import sys
import urllib.error
import urllib.request

QUOTA_BYTES = 8 * 1024 * 1024
CTYPE_PATTERNS = ["image/png", "image/jpeg", "text/plain"]
FULL = ["read", "write", "list", "delete", "purge", "tag"]
CORS = [
    {
        "allowed_origins": ["https://app.example.com", "https://*.example.org"],
        "allowed_methods": ["GET", "PUT", "POST", "HEAD", "DELETE"],
        "allowed_headers": ["*"],
        "expose_headers": ["ETag", "x-amz-version-id", "x-amz-checksum-crc32"],
        "max_age_seconds": 3000,
    }
]

KINDS = {
    "plain": {},
    "versioned": {"versioning": "enabled", "encryption": "sse-s3"},
    "public": {"anonymous_read": "objects", "cors": CORS},
    "quota": {"quota_bytes": QUOTA_BYTES},
    "ctype": {"allowed_content_types": CTYPE_PATTERNS},
}


def admin(url, token, method, path, body=None):
    data = None if body is None else json.dumps(body).encode()
    req = urllib.request.Request(url + "/_admin/v1" + path, data=data, method=method)
    req.add_header("Authorization", "Bearer " + token)
    if data is not None:
        req.add_header("Content-Type", "application/json")
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            raw = r.read()
            return r.status, (json.loads(raw) if raw else None)
    except urllib.error.HTTPError as e:
        raw = e.read()
        try:
            return e.code, json.loads(raw)
        except ValueError:
            return e.code, {"raw": raw.decode("utf-8", "replace")}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--suite", required=True)
    ap.add_argument("--admin-url", required=True)
    ap.add_argument("--admin-token", required=True)
    ap.add_argument("--endpoint", required=True)
    ap.add_argument("--tool-endpoint", required=True)
    ap.add_argument("--domain", default="")
    ap.add_argument("--region", default="us-east-1")
    ap.add_argument("--out", required=True)
    a = ap.parse_args()

    os.makedirs(a.out, exist_ok=True)
    env = {
        "suite": a.suite,
        "endpoint": a.endpoint,
        "tool_endpoint": a.tool_endpoint,
        "domain": a.domain,
        "region": a.region,
        "admin_url": a.admin_url,
        "admin_token": a.admin_token,
        "quota_bytes": QUOTA_BYTES,
        "ctype_patterns": CTYPE_PATTERNS,
        "buckets": {},
    }
    for kind, settings in KINDS.items():
        name = "bvt-%s-%s" % (a.suite, kind)
        body = dict(settings, name=name)
        code, resp = admin(a.admin_url, a.admin_token, "POST", "/buckets", body)
        if code == 409:  # left over from a --keep run: bring the settings back to the baseline
            put = dict(settings)
            code, resp = admin(a.admin_url, a.admin_token, "PUT", "/buckets/" + name, put)
        if code >= 300:
            sys.exit("bootstrap: bucket %s: HTTP %d %s" % (name, code, resp))
        code, tok = admin(
            a.admin_url, a.admin_token, "POST", "/buckets/%s/tokens" % name,
            {"name": "bvt-full", "grants": [{"actions": FULL}]},
        )
        if code != 201:
            sys.exit("bootstrap: token for %s: HTTP %d %s" % (name, code, tok))
        env["buckets"][kind] = {
            "name": name,
            "access_key": tok["access_key_id"],
            "secret_key": tok["secret_access_key"],
            "settings": settings,
        }

    with open(os.path.join(a.out, "env.json"), "w") as f:
        json.dump(env, f, indent=2)

    lines = [
        "# generated by bootstrap.py for suite %s" % a.suite,
        "export BV_SUITE=%s" % a.suite,
        "export BV_ENDPOINT=%s" % a.endpoint,
        "export BV_TOOL_ENDPOINT=%s" % a.tool_endpoint,
        "export BV_DOMAIN=%s" % a.domain,
        "export BV_REGION=%s" % a.region,
        "export BV_ADMIN_URL=%s" % a.admin_url,
        "export BV_ADMIN_TOKEN=%s" % a.admin_token,
        "export BV_QUOTA_BYTES=%d" % QUOTA_BYTES,
        "export BV_ENV_JSON=%s" % os.path.join(os.path.abspath(a.out), "env.json"),
    ]
    for kind, b in env["buckets"].items():
        k = kind.upper()
        lines += [
            "export BV_%s_BUCKET=%s" % (k, b["name"]),
            "export BV_%s_AK=%s" % (k, b["access_key"]),
            "export BV_%s_SK=%s" % (k, b["secret_key"]),
        ]
    with open(os.path.join(a.out, "env.sh"), "w") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
