// Package phpfpm renders and applies the per-app php-fpm pool files nginxpilot
// owns. It is the php-fpm twin of internal/nginxctl: one file per app, validated
// as a set before anything is swapped in, so a bad pool disables one app rather
// than taking the pool manager down with it.
//
// The daemon never starts or supervises php-fpm — the container entrypoint does.
// This package only writes configuration and asks php-fpm to test and reload it.
package phpfpm

import (
	"fmt"
	"os/user"
	"path/filepath"
	"sort"
	"strings"

	"github.com/kalevski/toolcase/nginxpilot/internal/config"
)

// PoolFileName is the deterministic file name for an app's pool.
func PoolFileName(domain string) string {
	return "app-" + config.FileStem(domain) + ".conf"
}

// RenderPool builds the php-fpm pool file for one app.
//
// The isolation floor lives here. A shared pool would run every app as one uid
// with read access to the whole content volume, which makes one line of PHP
// enough to read a competitor's credentials out of their persistent directory.
// Each app therefore gets its own pool, its own uid where one is provisioned,
// and an open_basedir naming exactly its release and its persistent tree.
func RenderPool(cfg *config.Config, app *config.App) string {
	return renderPool(cfg, app, appUser(cfg, app))
}

func renderPool(cfg *config.Config, app *config.App, runUser string) string {
	domain := app.Domain
	appRoot := filepath.Join(cfg.DataDir, "apps", domain)
	release := filepath.Join(appRoot, "current")
	persistent := filepath.Join(appRoot, config.PersistentDirName)
	socket := filepath.Join(socketDir(cfg), domain+".sock")
	tmp := filepath.Join("/tmp", config.FileStem(domain))

	owner := cfg.PHP.SocketOwner
	if owner == "" {
		owner = "nginxpilot"
	}

	var b strings.Builder
	fmt.Fprintf(&b, "; php-fpm pool for %s — generated by nginxpilot. Do not edit.\n", domain)
	fmt.Fprintf(&b, "[%s]\n", domain)
	fmt.Fprintf(&b, "user = %s\n", runUser)
	fmt.Fprintf(&b, "group = %s\n", runUser)
	fmt.Fprintf(&b, "listen = %s\n", socket)
	// Only nginx may connect to the socket; the pool's own uid must not be able
	// to reach another app's socket.
	fmt.Fprintf(&b, "listen.owner = %s\n", owner)
	fmt.Fprintf(&b, "listen.group = %s\n", owner)
	b.WriteString("listen.mode = 0660\n")

	// ondemand is what makes a pool-per-app affordable: an idle app holds no
	// worker, so the isolation story costs memory only while the app is serving.
	b.WriteString("\npm = ondemand\n")
	fmt.Fprintf(&b, "pm.max_children = %d\n", app.PHP.MaxChildrenOrDefault())
	b.WriteString("pm.process_idle_timeout = 30s\n")
	b.WriteString("pm.max_requests = 500\n")

	b.WriteString("\ncatch_workers_output = yes\n")
	b.WriteString("decorate_workers_output = no\n")
	fmt.Fprintf(&b, "access.log = /dev/null\n")

	// open_basedir must name the persistent tree explicitly: the release reaches
	// it through a symlink, and resolving a symlink out of the allowed set is
	// exactly what open_basedir blocks.
	fmt.Fprintf(&b, "\nphp_admin_value[open_basedir] = %s:%s:%s\n", release, persistent, tmp)
	fmt.Fprintf(&b, "php_admin_value[upload_tmp_dir] = %s\n", tmp)
	fmt.Fprintf(&b, "php_admin_value[sys_temp_dir] = %s\n", tmp)
	fmt.Fprintf(&b, "php_admin_value[memory_limit] = %s\n", app.PHP.MemoryLimitOrDefault())

	bodyMiB := app.PHP.MaxBodySizeOrDefault() / (1 << 20)
	if bodyMiB < 1 {
		bodyMiB = 1
	}
	fmt.Fprintf(&b, "php_admin_value[upload_max_filesize] = %dM\n", bodyMiB)
	fmt.Fprintf(&b, "php_admin_value[post_max_size] = %dM\n", bodyMiB)

	// Process-spawning functions are off by default. An app that genuinely needs
	// them is a deploy-server container, not a shared PHP pool.
	b.WriteString("php_admin_value[disable_functions] = exec,passthru,shell_exec,system,proc_open,popen,dl,pcntl_exec,symlink,link,putenv\n")
	b.WriteString("php_admin_flag[allow_url_fopen] = off\n")
	b.WriteString("php_admin_flag[expose_php] = off\n")

	// cgi.fix_pathinfo=0 is the second half of the anti-RCE pair; the vhost only
	// routes the front controller to fastcgi, and this stops php resolving a
	// PATH_INFO suffix onto some other file if a location is ever widened.
	b.WriteString("php_admin_value[cgi.fix_pathinfo] = 0\n")

	// opcache keys by realpath (the vhost sends $realpath_root), so each release
	// is its own cache entry and a swap is picked up without a reload.
	b.WriteString("\nphp_admin_flag[opcache.enable] = on\n")
	b.WriteString("php_admin_value[opcache.validate_timestamps] = 1\n")
	b.WriteString("php_admin_value[opcache.revalidate_freq] = 2\n")

	return b.String()
}

// RenderAll returns the pool file set for every enabled php app, keyed by file
// name, in deterministic order. An app whose user cannot be resolved is left
// out (see RenderAllChecked for the reasons).
func RenderAll(cfg *config.Config) map[string]string {
	files, _ := RenderAllChecked(cfg)
	return files
}

// RenderAllChecked is RenderAll plus the apps it refused to render, keyed by
// pool file name with the reason: an app with no host user of its own and no
// shared-user opt-in gets no pool, so its vhost is quarantined rather than the
// app silently running as a uid every other app shares.
func RenderAllChecked(cfg *config.Config) (files, failed map[string]string) {
	files, failed = map[string]string{}, map[string]string{}
	for i := range cfg.Apps {
		app := &cfg.Apps[i]
		if !app.IsEnabled() || app.RuntimeMode() != config.RuntimePHP {
			continue
		}
		user, err := ResolveUser(cfg, app)
		if err != nil {
			failed[PoolFileName(app.Domain)] = err.Error()
			continue
		}
		files[PoolFileName(app.Domain)] = renderPool(cfg, app, user)
	}
	return files, failed
}

// FileNames returns the rendered file names in sorted order.
func FileNames(files map[string]string) []string {
	names := make([]string, 0, len(files))
	for name := range files {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

// appUser returns the uid the pool runs as. A per-app user is the isolation
// floor; config.PHP.RunAs is the single-tenant fallback for installs that have
// not provisioned per-app accounts.
// userExists is the host user lookup, replaceable in tests.
var userExists = func(name string) bool {
	_, err := user.Lookup(name)
	return err == nil
}

// sharedFallbackUser is the uid an app runs as under php.allow_shared_user when
// it has no user of its own and php.run_as is unset.
const sharedFallbackUser = "nginxpilot"

// ResolveUser picks the uid an app's pool runs as. php.run_as is an explicit
// operator choice and wins. Otherwise the app needs its own app-<stem> user on
// the host; without one the app fails (a clear error, no pool) unless
// php.allow_shared_user opts into the shared fallback.
func ResolveUser(cfg *config.Config, app *config.App) (string, error) {
	if cfg.PHP.RunAs != "" {
		return cfg.PHP.RunAs, nil
	}
	own := "app-" + config.FileStem(app.Domain)
	if userExists(own) {
		return own, nil
	}
	if cfg.PHP.AllowSharedUser {
		return sharedFallbackUser, nil
	}
	return "", fmt.Errorf("host user %q does not exist: create it, set php.run_as, or set php.allow_shared_user: true to run this app as the shared %q user", own, sharedFallbackUser)
}

func appUser(cfg *config.Config, app *config.App) string {
	if cfg.PHP.RunAs != "" {
		return cfg.PHP.RunAs
	}
	return "app-" + config.FileStem(app.Domain)
}

func socketDir(cfg *config.Config) string {
	if cfg.PHP.SocketDir == "" {
		return "/run/php"
	}
	return cfg.PHP.SocketDir
}
