// Package zonefile renders BIND inputs from validated config: one RFC 1035
// master file per zone, and the named.conf fragment that declares them. It is
// pure text generation — no I/O — so it is shared by the apply engine, the
// print-zone / print-include commands and the admin /file endpoint.
package zonefile

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"path/filepath"
	"strings"

	"github.com/kalevski/toolcase/zonewright/internal/config"
)

// header marks every generated file so an operator who opens one knows where
// its source of truth lives.
const header = "; Generated by zonewright — do not edit: changes are overwritten.\n; Source of truth: the zonewright config / admin API.\n"

// FileName is the zone file's basename inside bind.zone_dir. Zone names are
// validated DNS names (no '/'), so this is filesystem-safe.
func FileName(zone string) string { return zone + ".db" }

// Path is the zone file's absolute path.
func Path(cfg *config.Config, zone string) string {
	return filepath.Join(cfg.Bind.ZoneDir, FileName(zone))
}

// Render produces the master file for z with the given SOA serial.
func Render(cfg *config.Config, z *config.Zone, serial uint32) string {
	var b strings.Builder
	b.WriteString(header)
	zoneTTL := cfg.EffectiveTTL(z)
	fmt.Fprintf(&b, "$ORIGIN %s.\n$TTL %d\n\n", z.Name, zoneTTL)

	soa := cfg.EffectiveSOA(z)
	fmt.Fprintf(&b, "@\t%d\tIN\tSOA\t%s %s (\n", zoneTTL, soa.PrimaryNS, RName(soa.AdminEmail))
	fmt.Fprintf(&b, "\t\t\t\t%d\t; serial\n", serial)
	fmt.Fprintf(&b, "\t\t\t\t%d\t; refresh\n", soa.Refresh)
	fmt.Fprintf(&b, "\t\t\t\t%d\t; retry\n", soa.Retry)
	fmt.Fprintf(&b, "\t\t\t\t%d\t; expire\n", soa.Expire)
	fmt.Fprintf(&b, "\t\t\t\t%d )\t; minimum (negative-cache TTL)\n\n", soa.Minimum)

	// Apex NS: the zone's nameserver list first, then any NS records at "@"
	// not already covered by it. One TTL for the RRset — an explicit NS record
	// TTL wins (validation guarantees they agree).
	nsTTL := zoneTTL
	for _, r := range z.Records {
		if r.Name == "@" && r.Type == config.TypeNS && r.TTL != 0 {
			nsTTL = r.TTL
			break
		}
	}
	seenNS := map[string]bool{}
	for _, ns := range cfg.EffectiveNameservers(z) {
		if !seenNS[ns] {
			seenNS[ns] = true
			fmt.Fprintf(&b, "@\t%d\tIN\tNS\t%s\n", nsTTL, ns)
		}
	}
	for _, r := range z.Records {
		if r.Name == "@" && r.Type == config.TypeNS && !seenNS[absolute(r.Value, z.Name)] {
			seenNS[absolute(r.Value, z.Name)] = true
			fmt.Fprintf(&b, "@\t%d\tIN\tNS\t%s\n", nsTTL, r.Value)
		}
	}

	if len(z.Records) > 0 {
		b.WriteString("\n")
	}
	for i := range z.Records {
		r := &z.Records[i]
		if r.Name == "@" && r.Type == config.TypeNS {
			continue // emitted with the apex NS set above
		}
		ttl := r.TTL
		if ttl == 0 {
			ttl = zoneTTL
		}
		fmt.Fprintf(&b, "%s\t%d\tIN\t%s\t%s\n", r.Name, ttl, r.Type, RData(r))
	}
	return b.String()
}

// ContentHash fingerprints everything in the rendered zone except the serial,
// so the serial is bumped exactly when the served data changes.
func ContentHash(cfg *config.Config, z *config.Zone) string {
	sum := sha256.Sum256([]byte(Render(cfg, z, 0)))
	return hex.EncodeToString(sum[:])
}

// RData renders a record's data in zone-file presentation format.
func RData(r *config.Record) string {
	iv := func(p *int) int {
		if p == nil {
			return 0
		}
		return *p
	}
	switch r.Type {
	case config.TypeMX:
		return fmt.Sprintf("%d %s", iv(r.Priority), r.Value)
	case config.TypeSRV:
		return fmt.Sprintf("%d %d %d %s", iv(r.Priority), iv(r.Weight), iv(r.Port), r.Value)
	case config.TypeTXT:
		return TXT(r.Value)
	case config.TypeCAA:
		return fmt.Sprintf("%d %s %s", iv(r.Flags), r.Tag, quote([]byte(r.Value)))
	default:
		return r.Value
	}
}

// TXT renders a TXT payload as one or more quoted character-strings of at
// most 255 bytes each (RFC 1035 §3.3). Splitting happens on raw bytes before
// escaping, so an escape sequence is never cut in half.
func TXT(v string) string {
	raw := []byte(v)
	if len(raw) == 0 {
		return `""`
	}
	var parts []string
	for len(raw) > 0 {
		n := min(len(raw), 255)
		parts = append(parts, quote(raw[:n]))
		raw = raw[n:]
	}
	return strings.Join(parts, " ")
}

// quote escapes a byte string for a zone file: '"' and '\' are backslashed,
// printable ASCII passes through, everything else becomes \DDD.
func quote(raw []byte) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, c := range raw {
		switch {
		case c == '"' || c == '\\':
			b.WriteByte('\\')
			b.WriteByte(c)
		case c >= 0x20 && c <= 0x7e:
			b.WriteByte(c)
		default:
			fmt.Fprintf(&b, "\\%03d", c)
		}
	}
	b.WriteByte('"')
	return b.String()
}

// RName converts an admin e-mail address to the SOA RNAME form: the '@'
// becomes a dot and dots in the local part are escaped.
func RName(email string) string {
	local, domain, _ := strings.Cut(email, "@")
	local = strings.ReplaceAll(local, ".", `\.`)
	return local + "." + strings.TrimSuffix(strings.ToLower(domain), ".") + "."
}

// absolute qualifies a rendered hostname value against the zone, for
// de-duplication only.
func absolute(v, zone string) string {
	switch {
	case v == "@":
		return zone + "."
	case strings.HasSuffix(v, "."):
		return v
	default:
		return v + "." + zone + "."
	}
}

// IncludeZone is one zone statement in the named.conf fragment.
type IncludeZone struct {
	Name          string
	File          string
	AllowTransfer []string
	AlsoNotify    []string
}

// IncludeEntry builds the conf entry for a zone from config.
func IncludeEntry(cfg *config.Config, z *config.Zone) IncludeZone {
	return IncludeZone{
		Name:          z.Name,
		File:          Path(cfg, z.Name),
		AllowTransfer: cfg.EffectiveAllowTransfer(z),
		AlsoNotify:    cfg.EffectiveAlsoNotify(z),
	}
}

// Include renders the named.conf fragment declaring every zone as a primary.
// An empty allow_transfer is rendered as `none` — BIND's historical default
// of letting anyone AXFR the zone is not one zonewright wants to inherit.
func Include(zones []IncludeZone) string {
	var b strings.Builder
	b.WriteString(strings.ReplaceAll(header, "; ", "// "))
	if len(zones) == 0 {
		b.WriteString("// (no zones configured)\n")
	}
	for _, z := range zones {
		fmt.Fprintf(&b, "\nzone %q {\n", z.Name)
		b.WriteString("    type primary;\n")
		fmt.Fprintf(&b, "    file %q;\n", z.File)
		transfer := z.AllowTransfer
		if len(transfer) == 0 {
			transfer = []string{"none"}
		}
		fmt.Fprintf(&b, "    allow-transfer { %s; };\n", strings.Join(transfer, "; "))
		if len(z.AlsoNotify) > 0 {
			b.WriteString("    notify yes;\n")
			fmt.Fprintf(&b, "    also-notify { %s; };\n", strings.Join(z.AlsoNotify, "; "))
		}
		b.WriteString("};\n")
	}
	return b.String()
}
