// Unit coverage for the pure access-list decisions (C1): parse rejections that
// mirror the daemon's rules, the secret-handling gate (no password material in
// fragments), the CIDR shape validator, and golden fragment YAML.

import { describe, it, expect } from 'vitest'
import { isRuleAddr, parseAccessList, renderAccessListFragment } from './access-list'
import { parseProxy, parseRedirect, parseDeadHost, renderProxyFragment } from './routing'

describe('isRuleAddr', () => {
    it('accepts IPs, CIDRs (v4 + v6) and "all"', () => {
        for (const v of ['all', '10.0.0.1', '10.0.0.0/8', '2001:db8::1', '2001:db8::/32', '0.0.0.0/0']) {
            expect(isRuleAddr(v), v).toBe(true)
        }
    })
    it('rejects hostnames, bad prefixes and garbage', () => {
        for (const v of ['example.com', '10.0.0.0/33', '2001:db8::/129', '10.0.0/8', 'deny all;', '10.0.0.256']) {
            expect(isRuleAddr(v), v).toBe(false)
        }
    })
})

describe('parseAccessList', () => {
    it('normalizes a valid list, dropping the satisfy-all default', () => {
        const r = parseAccessList({
            name: 'office',
            satisfy: 'all',
            users: [{ username: 'alice' }],
            rules: [{ allow: '10.0.0.0/8' }, { deny: '203.0.113.7' }],
        })
        expect(r).toEqual({
            ok: true,
            value: {
                name: 'office',
                users: [{ username: 'alice' }],
                rules: [{ allow: '10.0.0.0/8' }, { deny: '203.0.113.7' }],
            },
        })
    })

    it('keeps satisfy any + pass_auth', () => {
        const r = parseAccessList({ name: 'l', satisfy: 'any', pass_auth: true, rules: [{ allow: 'all' }] })
        expect(r.ok).toBe(true)
        if (!r.ok) return
        expect(r.value.satisfy).toBe('any')
        expect(r.value.pass_auth).toBe(true)
    })

    it('rejects bad names and satisfy values', () => {
        expect(parseAccessList({ rules: [{ allow: 'all' }] })).toMatchObject({ ok: false, reason: 'name_required' })
        expect(parseAccessList({ name: 'has-dash' })).toMatchObject({ ok: false, reason: 'bad_name' })
        expect(parseAccessList({ name: 'l', satisfy: 'some' })).toMatchObject({ ok: false, reason: 'bad_satisfy' })
    })

    it('rejects password material in the list body (the dedicated endpoint owns it)', () => {
        expect(parseAccessList({ name: 'l', users: [{ username: 'a', password: 'x' }] })).toMatchObject({
            ok: false,
            reason: 'password_in_fragment',
        })
        expect(parseAccessList({ name: 'l', users: [{ username: 'a', password_hash: '$apr1$x' }] })).toMatchObject({
            ok: false,
            reason: 'password_in_fragment',
        })
    })

    it('rejects malformed users and rules', () => {
        expect(parseAccessList({ name: 'l', users: [{ username: 'a:b' }] })).toMatchObject({
            ok: false,
            reason: 'bad_username',
        })
        expect(parseAccessList({ name: 'l', users: [{ username: 'a' }, { username: 'a' }] })).toMatchObject({
            ok: false,
            reason: 'duplicate_user',
        })
        expect(parseAccessList({ name: 'l', rules: [{}] })).toMatchObject({ ok: false, reason: 'bad_rule' })
        expect(parseAccessList({ name: 'l', rules: [{ allow: '1.2.3.4', deny: '5.6.7.8' }] })).toMatchObject({
            ok: false,
            reason: 'bad_rule',
        })
        expect(parseAccessList({ name: 'l', rules: [{ allow: 'example.com' }] })).toMatchObject({
            ok: false,
            reason: 'bad_rule_addr',
        })
    })
})

describe('renderAccessListFragment', () => {
    it('emits the golden fragment — usernames only, never password material', () => {
        const r = parseAccessList({
            name: 'office',
            satisfy: 'any',
            pass_auth: true,
            users: [{ username: 'alice' }, { username: 'bob' }],
            rules: [{ allow: '10.0.0.0/8' }, { deny: 'all' }],
        })
        expect(r.ok).toBe(true)
        if (!r.ok) return
        expect(renderAccessListFragment(r.value)).toBe(
            [
                '# generated by Perch; managed automatically, do not edit by hand.',
                'access_lists:',
                '  - name: office',
                '    satisfy: any',
                '    pass_auth: true',
                '    users:',
                '      - username: "alice"',
                '      - username: "bob"',
                '    rules:',
                '      - allow: "10.0.0.0/8"',
                '      - deny: "all"',
                '',
            ].join('\n'),
        )
    })
})

describe('access_list references on hosts', () => {
    it('passes a valid reference through on proxy/redirect/dead host', () => {
        const p = parseProxy({ domain: 'a.com', pass: 'http://x:1', access_list: 'office' })
        expect(p.ok && p.value.access_list === 'office').toBe(true)
        if (p.ok) expect(renderProxyFragment(p.value)).toContain('    access_list: office')

        const r = parseRedirect({ domain: 'a.com', to: 'b.com', access_list: 'office' })
        expect(r.ok && r.value.access_list === 'office').toBe(true)

        const d = parseDeadHost({ domain: 'a.com', access_list: 'office' })
        expect(d.ok && d.value.access_list === 'office').toBe(true)
    })

    it('rejects a malformed reference', () => {
        expect(parseProxy({ domain: 'a.com', pass: 'http://x:1', access_list: 'has space' })).toMatchObject({
            ok: false,
            reason: 'bad_access_list',
        })
    })
})
