// Pure rendering of an nginxpilot site fragment (Channel A of the integration
// seam — §4). No `server-only`, no filesystem, no I/O: given a `Site` plus the
// policy-derived knobs (poll interval, gates, private-repo auth), produce the
// exact `sites.d/perch-<siteId>.yml` text and the deterministic, server-generated
// filename. Keeping this layer pure (mirrors `domain/sponsorship-events.ts`) lets
// the fragment schema be unit-tested in isolation, and lets the I/O wrapper in
// `infrastructure/nginxpilot.ts` stay thin.
//
// See notes/static-hosting-app-design.md §4, §9, §16.

import type { Site } from './types'

// ── deterministic, server-generated identifiers (§16: no user input in paths) ──

// Site ids are server-generated (§12), but this module is the last gate before an
// id reaches a filesystem path *and* an OS env-var name, so it validates defensively
// rather than trusting the caller. Filenames tolerate `-`; env-var name components
// do not, so the two derivations differ (see `tokenEnvVarName`).
const SAFE_SITE_ID = /^[A-Za-z0-9_-]{1,64}$/

/** Throw unless `siteId` is a safe, server-generated id (path/env-var-name safe). */
export function assertSafeSiteId(siteId: string): void {
    if (!SAFE_SITE_ID.test(siteId)) {
        throw new Error(
            `[perch] unsafe site id ${JSON.stringify(siteId)}: expected ${SAFE_SITE_ID} ` +
                `(ids are server-generated — never derive a fragment path from user input, §16).`,
        )
    }
}

/** Deterministic fragment filename for a site — `perch-<siteId>.yml` (§4, §12). */
export function fragmentFilename(siteId: string): string {
    assertSafeSiteId(siteId)
    return `perch-${siteId}.yml`
}

/**
 * Env-var NAME that holds the repo credential for a private site (§4, §9, §16) —
 * the value is referenced by name in the fragment and never inlined. Uppercased
 * with id hyphens folded to `_`, since `-` is illegal in a POSIX env-var name.
 */
export function tokenEnvVarName(siteId: string): string {
    assertSafeSiteId(siteId)
    return `PERCH_GH_TOKEN_${siteId.toUpperCase().replace(/-/g, '_')}`
}

// ── fragment rendering (§4) ───────────────────────────────────────────────────

/** Private-repo credential reference for the fragment `auth` block (§9, §16). */
export interface FragmentAuth {
    /**
     * Name of the env var nginxpilot reads the GitHub token from. NOTE: nginxpilot's
     * `github-token` method keys the credential as `token_env` (validated in
     * `internal/config/validate.go` — `key_env` belongs to the `ssh-key` method and
     * is rejected here). The §4 example writes `key_env`, which is a doc slip; the
     * engine-correct key is `token_env`, emitted below. Build it with
     * `tokenEnvVarName(site.id)`.
     */
    tokenEnv: string
}

/** Policy-derived knobs the `Site` row itself doesn't carry (§9, §11, §15). */
export interface FragmentOptions {
    /**
     * Poll cadence floor in seconds, from the owner's effective `PlanLimits.minIntervalSec`
     * (free = 900 → `15m`; gold = 60 → `1m`). Formatted to an nginxpilot Go duration.
     */
    intervalSec: number
    /**
     * Post-fetch gate: nginxpilot won't go live unless these files exist, so a broken
     * or empty build keeps the last-known-good release serving. Defaults to
     * `['index.html']`; pass `[]` to omit the gate.
     */
    requireFile?: string[]
    /**
     * Glob excludes layered on nginxpilot's defaults. Defaults to `['*.map']`; pass
     * `[]` to omit.
     */
    exclude?: string[]
    /**
     * Present only for a private repo (paid tier, §9). Omit for public repos — the v1
     * free tier deploys public repos only and writes no `auth` block (zero secrets).
     */
    auth?: FragmentAuth
}

const DEFAULT_REQUIRE_FILE = ['index.html']
const DEFAULT_EXCLUDE = ['*.map']

/**
 * Render the `sites.d/perch-<siteId>.yml` fragment for one site, exactly per the
 * §4 schema: `domain`, `source.{type,url,branch,interval,subdir,require_file,auth}`,
 * and `exclude`. The repo URL is derived from the site's `repoOwner`/`repoName`; the
 * interval comes from `options.intervalSec`. Secrets are referenced by env-var name
 * only (`auth.token_env`), never inlined (§16).
 */
export function renderFragment(site: Site, options: FragmentOptions): string {
    assertSafeSiteId(site.id)
    const requireFile = options.requireFile ?? DEFAULT_REQUIRE_FILE
    const exclude = options.exclude ?? DEFAULT_EXCLUDE
    const url = `https://github.com/${site.repoOwner}/${site.repoName}.git`

    const lines: string[] = [
        `# ${fragmentFilename(site.id)} — generated by Perch; managed automatically, do not edit by hand.`,
        'sites:',
        `  - domain: ${scalar(site.hostname)}`,
        '    source:',
        '      type: git',
        `      url: ${scalar(url)}`,
        `      branch: ${scalar(site.branch)}`,
        `      interval: ${scalar(formatInterval(options.intervalSec))}`,
    ]
    if (site.subdir) lines.push(`      subdir: ${scalar(site.subdir)}`)
    if (requireFile.length > 0) lines.push(`      require_file: ${flowSeq(requireFile)}`)
    if (options.auth) {
        lines.push('      auth:')
        lines.push('        method: github-token')
        // Engine-correct key for `github-token` is `token_env` (see FragmentAuth).
        lines.push(`        token_env: ${scalar(options.auth.tokenEnv)}`)
    }
    if (exclude.length > 0) lines.push(`    exclude: ${flowSeq(exclude)}`)

    return lines.join('\n') + '\n'
}

/**
 * Format a whole number of seconds as an nginxpilot Go duration: exact hours →
 * `Nh`, exact minutes → `Nm`, else `Ns`. 900 → `15m`, 300 → `5m`, 60 → `1m`,
 * 30 → `30s`. (nginxpilot enforces a 30s floor on its side.)
 */
export function formatInterval(seconds: number): string {
    const s = Math.max(1, Math.floor(seconds))
    if (s % 3600 === 0) return `${s / 3600}h`
    if (s % 60 === 0) return `${s / 60}m`
    return `${s}s`
}

// ── minimal YAML scalar/flow emission ─────────────────────────────────────────
//
// We hand-emit the handful of scalar/array shapes this fixed schema needs rather
// than pull in a YAML dependency. Plain-safe values are written bare (matching the
// §4 example); anything else is double-quoted, which both keeps the YAML valid and
// defuses injection through a value that slipped past upstream validation (§16).

// Bare scalars: start alphanumeric, then only chars that can't break out of a
// plain scalar or smuggle YAML structure. Domains, https URLs, branches, Go
// durations, `dist/`, and `PERCH_GH_TOKEN_*` all qualify; a `*.map` glob (leading
// `*`) or anything with whitespace/quotes/newlines does not.
const PLAIN_SCALAR = /^[A-Za-z0-9][A-Za-z0-9._:/-]*$/

/** Emit a YAML scalar, quoting only when the value isn't plain-safe. */
function scalar(value: string): string {
    if (PLAIN_SCALAR.test(value)) return value
    return quote(value)
}

/** Emit a YAML flow sequence, quoting each item only when needed: `[a, "b*"]`. */
function flowSeq(items: string[]): string {
    return `[${items.map(scalar).join(', ')}]`
}

/** Double-quote a scalar, escaping backslashes, quotes, and control characters. */
function quote(value: string): string {
    const escaped = value
        .replace(/\\/g, '\\\\')
        .replace(/"/g, '\\"')
        .replace(/\n/g, '\\n')
        .replace(/\r/g, '\\r')
        .replace(/\t/g, '\\t')
    return `"${escaped}"`
}
