// Unit coverage for the pure nginxpilot fragment renderer (§4). No filesystem,
// no `server-only` — the I/O wrapper in `infrastructure/nginxpilot.ts` is just
// these functions plus an atomic write, so the load-bearing schema is verified
// here in isolation. The headline check reproduces the §4 example fragment.

import { describe, it, expect } from 'vitest'
import type { Site } from './types'
import {
    assertSafeSiteId,
    formatInterval,
    fragmentFilename,
    renderFragment,
    tokenEnvVarName,
} from './nginxpilot-fragment'

/** The §4 `alice.perch.dev` site, as a `Site` row. */
function aliceSite(overrides: Partial<Site> = {}): Site {
    return {
        id: 'abc123',
        ownerId: 1,
        repoOwner: 'alice',
        repoName: 'portfolio',
        branch: 'gh-pages',
        subdir: 'dist/',
        hostname: 'alice.perch.dev',
        hostKind: 'subdomain',
        status: 'provisioning',
        createdAt: '2026-06-25T00:00:00.000Z',
        updatedAt: '2026-06-25T00:00:00.000Z',
        ...overrides,
    }
}

describe('renderFragment', () => {
    it('reproduces the §4 example fragment for a private site', () => {
        // Matches notes/static-hosting-app-design.md §4 verbatim except for the auth
        // key: nginxpilot's `github-token` method validates `token_env`, not the §4
        // doc's `key_env` (which belongs to `ssh-key`). See FragmentAuth.
        const yaml = renderFragment(aliceSite(), {
            intervalSec: 900,
            requireFile: ['index.html'],
            exclude: ['*.map'],
            auth: { tokenEnv: tokenEnvVarName('abc123') },
        })
        expect(yaml).toBe(
            `# perch-abc123.yml — generated by Perch; managed automatically, do not edit by hand.
sites:
  - domain: alice.perch.dev
    source:
      type: git
      url: https://github.com/alice/portfolio.git
      branch: gh-pages
      interval: 15m
      subdir: dist/
      require_file: [index.html]
      auth:
        method: github-token
        token_env: PERCH_GH_TOKEN_ABC123
    exclude: ["*.map"]
`,
        )
    })

    it('omits the auth block for a public repo (v1 free tier — zero secrets)', () => {
        const yaml = renderFragment(aliceSite(), { intervalSec: 900 })
        expect(yaml).not.toContain('auth:')
        expect(yaml).not.toContain('token_env')
        // The defaults still apply: require_file gate + *.map exclude.
        expect(yaml).toContain('require_file: [index.html]')
        expect(yaml).toContain('exclude: ["*.map"]')
    })

    it('omits subdir when the site has none', () => {
        const yaml = renderFragment(aliceSite({ subdir: undefined }), { intervalSec: 900 })
        expect(yaml).not.toContain('subdir:')
    })

    it('lets callers drop the require_file / exclude defaults with empty arrays', () => {
        const yaml = renderFragment(aliceSite(), { intervalSec: 60, requireFile: [], exclude: [] })
        expect(yaml).not.toContain('require_file:')
        expect(yaml).not.toContain('exclude:')
        expect(yaml).toContain('interval: 1m')
    })

    it('quotes a hostname that tries to smuggle YAML structure (defense in depth, §16)', () => {
        const yaml = renderFragment(aliceSite({ hostname: 'evil\ninjected: true' }), { intervalSec: 900 })
        expect(yaml).toContain('domain: "evil\\ninjected: true"')
    })
})

describe('formatInterval', () => {
    it('formats exact hours/minutes/seconds', () => {
        expect(formatInterval(900)).toBe('15m')
        expect(formatInterval(300)).toBe('5m')
        expect(formatInterval(120)).toBe('2m')
        expect(formatInterval(60)).toBe('1m')
        expect(formatInterval(3600)).toBe('1h')
        expect(formatInterval(45)).toBe('45s')
    })
})

describe('fragmentFilename / tokenEnvVarName', () => {
    it('derives a deterministic filename and env-var name', () => {
        expect(fragmentFilename('abc123')).toBe('perch-abc123.yml')
        expect(tokenEnvVarName('abc123')).toBe('PERCH_GH_TOKEN_ABC123')
        // Hyphens are legal in filenames but folded to `_` for the env-var name.
        expect(fragmentFilename('a-b')).toBe('perch-a-b.yml')
        expect(tokenEnvVarName('a-b')).toBe('PERCH_GH_TOKEN_A_B')
    })

    it('rejects unsafe ids that could escape the fragment path (§16)', () => {
        expect(() => assertSafeSiteId('../etc/passwd')).toThrow()
        expect(() => assertSafeSiteId('a/b')).toThrow()
        expect(() => assertSafeSiteId('a.b')).toThrow()
        expect(() => assertSafeSiteId('')).toThrow()
        expect(() => fragmentFilename('../x')).toThrow()
    })
})
