// Unit coverage for the pure routing decisions behind `services/routing.ts` (the
// `server-only` service can't be imported under vitest). Mirrors the daemon's
// `internal/config/validate.go` rules so the UI gets the same rejections nginxpilot
// would, plus the exact YAML the `POST /upstreams` / `POST /proxies` admin endpoints
// parse.

import { describe, it, expect } from 'vitest'
import { parseUpstream, parseProxy, renderUpstreamFragment, renderProxyFragment } from './routing'

describe('parseUpstream', () => {
    it('normalizes a valid upstream, dropping empty optionals and round_robin default', () => {
        const r = parseUpstream({
            name: 'api_pool',
            balancer: 'round_robin', // the default → omitted
            keepalive: 0, // 0 → omitted
            servers: [
                { address: '10.0.0.1:8080' },
                { address: '10.0.0.2:8080', weight: 2, max_fails: 3, fail_timeout: '30s', backup: true, down: false },
            ],
        })
        expect(r.ok).toBe(true)
        if (!r.ok) return
        expect(r.value).toEqual({
            name: 'api_pool',
            servers: [
                { address: '10.0.0.1:8080' },
                { address: '10.0.0.2:8080', weight: 2, max_fails: 3, fail_timeout: '30s', backup: true },
            ],
        })
    })

    it('keeps a non-default balancer and a positive keepalive', () => {
        const r = parseUpstream({ name: 'p', balancer: 'least_conn', keepalive: 32, servers: [{ address: 'a:1' }] })
        expect(r.ok).toBe(true)
        if (!r.ok) return
        expect(r.value.balancer).toBe('least_conn')
        expect(r.value.keepalive).toBe(32)
    })

    it('rejects a missing/invalid name (must match the nginx identifier regex)', () => {
        expect(parseUpstream({ servers: [{ address: 'a:1' }] })).toMatchObject({ ok: false, reason: 'name_required' })
        expect(parseUpstream({ name: 'has-dash', servers: [{ address: 'a:1' }] })).toMatchObject({
            ok: false,
            reason: 'bad_name',
        })
        expect(parseUpstream({ name: 'has space', servers: [{ address: 'a:1' }] })).toMatchObject({
            ok: false,
            reason: 'bad_name',
        })
    })

    it('rejects an unknown balancer', () => {
        expect(parseUpstream({ name: 'p', balancer: 'magic', servers: [{ address: 'a:1' }] })).toMatchObject({
            ok: false,
            reason: 'bad_balancer',
        })
    })

    it('requires at least one server, each with an address', () => {
        expect(parseUpstream({ name: 'p', servers: [] })).toMatchObject({ ok: false, reason: 'no_servers' })
        expect(parseUpstream({ name: 'p' })).toMatchObject({ ok: false, reason: 'no_servers' })
        expect(parseUpstream({ name: 'p', servers: [{ weight: 1 }] })).toMatchObject({
            ok: false,
            reason: 'address_required',
        })
    })

    it('rejects a negative weight / max_fails / keepalive', () => {
        expect(parseUpstream({ name: 'p', servers: [{ address: 'a:1', weight: -1 }] })).toMatchObject({
            ok: false,
            reason: 'bad_weight',
        })
        expect(parseUpstream({ name: 'p', keepalive: -1, servers: [{ address: 'a:1' }] })).toMatchObject({
            ok: false,
            reason: 'bad_keepalive',
        })
    })
})

describe('renderUpstreamFragment', () => {
    it('emits valid YAML matching the POST /upstreams schema', () => {
        const r = parseUpstream({
            name: 'api_pool',
            balancer: 'least_conn',
            keepalive: 32,
            servers: [{ address: '10.0.0.1:8080' }, { address: '10.0.0.2:8080', weight: 2, backup: true }],
        })
        expect(r.ok).toBe(true)
        if (!r.ok) return
        expect(renderUpstreamFragment(r.value)).toBe(
            [
                '# generated by Perch; managed automatically, do not edit by hand.',
                'upstreams:',
                '  - name: api_pool',
                '    balancer: least_conn',
                '    keepalive: 32',
                '    servers:',
                '      - address: 10.0.0.1:8080',
                '      - address: 10.0.0.2:8080',
                '        weight: 2',
                '        backup: true',
                '',
            ].join('\n'),
        )
    })

    it('quotes an address that is not plain-safe', () => {
        const yaml = renderUpstreamFragment({ name: 'p', servers: [{ address: 'has space' }] })
        expect(yaml).toContain('- address: "has space"')
    })
})

describe('parseProxy', () => {
    it('normalizes an inline-pass proxy, dropping the default listen', () => {
        const r = parseProxy({ domain: 'API.example.com', listen: 80, pass: 'http://127.0.0.1:9000' })
        expect(r.ok).toBe(true)
        if (!r.ok) return
        expect(r.value).toEqual({ domain: 'api.example.com', pass: 'http://127.0.0.1:9000' })
    })

    it('keeps a non-default listen and an upstream target', () => {
        const r = parseProxy({ domain: 'a.com', listen: 8080, upstream: 'api_pool' })
        expect(r.ok).toBe(true)
        if (!r.ok) return
        expect(r.value).toMatchObject({ listen: 8080, upstream: 'api_pool' })
    })

    it('allows a locations-only proxy with no default target', () => {
        const r = parseProxy({
            domain: 'a.com',
            locations: [{ path: '/api', upstream: 'api_pool' }, { path: '/ws', pass: 'http://x:1', websocket: true }],
        })
        expect(r.ok).toBe(true)
        if (!r.ok) return
        expect(r.value.locations).toEqual([
            { path: '/api', upstream: 'api_pool' },
            { path: '/ws', pass: 'http://x:1', websocket: true },
        ])
    })

    it('lets a location inherit the proxy default target', () => {
        const r = parseProxy({ domain: 'a.com', upstream: 'pool', locations: [{ path: '/api' }] })
        expect(r.ok).toBe(true)
        if (!r.ok) return
        expect(r.value.locations).toEqual([{ path: '/api' }])
    })

    it('rejects a missing domain and a wildcard', () => {
        expect(parseProxy({ pass: 'http://x:1' })).toMatchObject({ ok: false, reason: 'domain_required' })
        expect(parseProxy({ domain: '*.example.com', pass: 'http://x:1' })).toMatchObject({
            ok: false,
            reason: 'wildcard',
        })
    })

    it('rejects an out-of-range listen port', () => {
        expect(parseProxy({ domain: 'a.com', listen: 70000, pass: 'http://x:1' })).toMatchObject({
            ok: false,
            reason: 'bad_listen',
        })
    })

    it('rejects upstream + pass at once, and a non-http pass', () => {
        expect(parseProxy({ domain: 'a.com', upstream: 'p', pass: 'http://x:1' })).toMatchObject({
            ok: false,
            reason: 'bad_target',
        })
        expect(parseProxy({ domain: 'a.com', pass: 'ftp://x' })).toMatchObject({ ok: false, reason: 'bad_target' })
    })

    it('requires a complete target when there are no locations', () => {
        expect(parseProxy({ domain: 'a.com' })).toMatchObject({ ok: false, reason: 'bad_target' })
    })

    it('rejects a location path that does not start with /', () => {
        expect(parseProxy({ domain: 'a.com', locations: [{ path: 'api', upstream: 'p' }] })).toMatchObject({
            ok: false,
            reason: 'bad_path',
        })
    })
})

describe('renderProxyFragment', () => {
    it('emits valid YAML matching the POST /proxies schema', () => {
        const r = parseProxy({
            domain: 'api.example.com',
            listen: 8080,
            upstream: 'api_pool',
            client_max_body_size: '512MiB',
            locations: [{ path: '/ws', pass: 'http://127.0.0.1:9000', websocket: true }],
        })
        expect(r.ok).toBe(true)
        if (!r.ok) return
        expect(renderProxyFragment(r.value)).toBe(
            [
                '# generated by Perch; managed automatically, do not edit by hand.',
                'proxies:',
                '  - domain: api.example.com',
                '    listen: 8080',
                '    upstream: api_pool',
                '    client_max_body_size: 512MiB',
                '    locations:',
                // A path starts with '/', so the conservative scalar emitter quotes it
                // (valid YAML; nginxpilot parses "/ws" to the same string).
                '      - path: "/ws"',
                '        pass: http://127.0.0.1:9000',
                '        websocket: true',
                '',
            ].join('\n'),
        )
    })
})
